### ISSUE TITLE
Request for backward compatibility of %-formatting in ansi.py

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1025]
#### Brief summary of issue / Description of requested feature:
Most of my players are from mush backgrounds and really love using % formatting for messages,
particularly %r for newlines, or %t for tabs. Color codes using that formatting is also a pretty big deal for them, as we have a crafting system that people create really elaborate designs for. I saw in the newest version of evennia that this no longer appeared to be supported, and although this seems trivial and cosmetic, it'd be almost a show-stopper for a lot of my players. I'd really like to have a %-format still be supported in ansi.py, or have some way to extend/override the regexes to add it myself. Apologies if there already is some method of doing this, I didn't see anything when I glanced through.

**Comment by BlauFeuer** [comment]
It seems like at some point `%` was removed and replaced with `|`, while `{` continued to be used in source code.   I've been using `|` in all my source code and wondering how long it will be before `{` is phased out. 

I'd definitely rather see `%` used for in-game markup than `{` and I've been actively changing source code to get away from the use of `{`.

I've gotten used to using the `|` character for markup in-game.   If `%` replaces `{`, and `|` still works, I'm fine with that, but there really should be a more of a discussion on this so it doesn't become a problem again in the future.

**Comment by Griatch** [comment]
%c-type formatting was deprecated for 3 years after which it was finally removed last year without any issue or complaints of compatibility. Using % is not a good fit for use in Python strings, which is why it was phased out in the first place - and Python as well as Evennia try to abide to the principle of "there should be only one and only one best way to do things". Also {-type coloration is planned to be phased out once deprecation period is over and the strings inside the engine has been converted to |-form. This is nothing unusual for software - there's plenty of time to transition to the new way. 

I suggest one of three options: 

1. Parse-and-replace existing strings to the correct syntax (it's a one-time adjustment) and then simply let your players know what the correct syntax is.
2. Create a pre-parser in your typeclasses' msg() method that parse for the particular color markers you want to support and convert them to color markers Evennia understands, like `%cr` -> `|r`. 
3. Lastly, we *could* make the ansi parser more easily replaceable. The `parse_ansi()` method takes an argument `parser` that defaults to Evennia's core Parser class. We could have protocols like telnet assign this based on a setting. This would be a new Feature Request/PR if so. Reimplementing a full ansi handler for this seems like a bit too much work for the benefit though (plus you'll lose the ability to get upstream bug fixes and updates to it). So 2. above is what I would recommend. 

Closing this (you can still comment here though if desired).

**Comment by TehomCD** [comment]
Yeah, 2 makes sense, and it'd be easy to extend that to continue to support the { format when it's removed for players who like that also. Thanks, Griatch!
