### ISSUE TITLE
Feature request: overriding admin classes

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1029]
It would be nice if there was some way for us to override the admin classes used for the defined evennia models - I believe that we can't just straight-up create our own admin classes and register them, because you can't register the same model twice, and registering a proxy class would have both of them show up in django admin. What I'm sort of picturing is something like:

settings.ADMIN_OVERRIDES = { 'objectdb': 'web.admin_overrides.typeclasses.AdminObjectDB'}, and then in admin objects, checking if the model name is in the dictionary and if the path is valid, using that instead for registering the admin class, and otherwise using the predefined one.

The primary motivation for this would be changing things like the list display with properties that might be specific to the game, as well as customizing the search fields.

**Comment by Griatch** [comment]
I'd need to examine this further, but I'd imagine the admin views (the admin.py files) are just pointed to by normal url.py in some automated way (you don't see it normally since the admin urls are imported from the django admin package). So if one were to overload those urls in your own url.py to point to your own admin view in mygame that should work. Maybe? 

I've not actually tried it myself yet, but if  someone does test it before I get to it, let us know in this thread - It sounds like the most sane way to handle it, if it's possible.

**Comment by TehomCD** [comment]
I discovered that while trying to register a class that is already registered in admin will raise an exception, you can simply call 'admin.site.unregister(model)' and then register it with your own admin class.
