### ISSUE TITLE
SESSION_HANLDER.get_puppet() shows a None object.

### ISSUE THREAD

**Issue by duanuys** [evennia/evennia#1036]
#### Brief summary of issue / Description of requested feature:
Part of my 'who' command get all the sessions via the session_handler. The method get_session() brings all session objects, but when converted to puppet() at least one is always a None. This is fixed when I do a cold shut down. 

I do not get any error messages at all. Just a bug i find worth noting. 

#### Steps to reproduce the issue / Reasons for adding feature:

1. Be on Mud
2. Have people connect, leave, idle -timeout
3. Eventually a session stays behind with a puppet of None

**Comment by BlauFeuer** [comment]
It could be entirely normal to see a None for Character _or_ Player:

`character = session.get_puppet()` can be `None` when `@OOC`.

`player = session.get_player()` can be `None` pre-login.

In the default who command, `if show_session_data:` code gives more information that might give you a clue as to the session origin.  When you shut down the portal, of course it's going to disconnect a normal session, too - so nothing in you described situation is abnormal yet.

Could you possibly write a more detailed version of the who command, similar to the default one to give you more information on the origin of the session, or if you think perhaps your custom who command is not yielding the information you want, attach it and we can tell you how to filter out `None` for players in it.

**Comment by duanuys** [comment]
I managed to find a way to filter out the `None` types for sessions, but I am just worried that it might accumulate over time or clog up the DB eventually. Below is the custom code for my who command. It doesn't differ much from the default who, but any other suggestions would be appreciated thank you.


```
	def func(self):
		"""
		Get all connected players by polling session.
		"""
		session_list = SESSIONS.get_sessions()
	
		#nplayers = (SESSIONS.player_count())
		nplayers = 0

		who_string = ''
		mortals = "\n\n---[ {yMortals{n ]---\n";
		mortal_list = []
		imms = "\n---[ {rImmortals{n ] ---\n";
		imm_list = []
		for session in session_list:
			if not session.logged_in: continue
			
			player = session.get_puppet()
			if player is not None: nplayers += 1
			try:
				if GET_LEVEL(player) < BUILDER():
					mortal_list.append([str(GET_LEVEL(player)),
					                    player.name.capitalize(),
					                    player.db.title,
					                   ['<{m' + flag.replace("_", " ").lower().title() + '{n>' for flag in player.db.prf_flags],
					                   ['<{r' + flag.replace("_", " ").lower().title() + '{n>' for flag in player.db.plr_flags]]
									)
				
				if GET_LEVEL(player) > BUILDER():
					imm_list.append([str(GET_WIZI_NAME(player)),
					                 player.name.capitalize(),
					                 player.db.title,
					                 ['<{m' + flag.replace("_", " ").lower().title() + '{n>' for flag in player.db.prf_flags],
					                ['<{r' + flag.replace("_", " ").lower().title() + '{n>' for flag in player.db.plr_flags]]
					                )
			except: pass
			
		who_string += mortals
		for mortal in mortal_list:
			who_string += "[%10s]    %s %s\n" % (mortal[0], mortal[1], mortal[2])
		
		who_string += imms
		for imm in imm_list:
			who_string += "[%20s]  %s %s %s\n" % (imm[0], ' '.join(imm[3] + imm[4]), imm[1], imm[2])
		
		who_string += "\n\nThere %s {m%s{n player%s and {r%d{n immortal%s online." % ('are' if nplayers > 1 else 'is',
		                                                                              str(nplayers),
		                                                                              's' if nplayers > 1 else '',
		                                                                              len(imm_list),
		                                                                              's' if len(imm_list) > 1 else '')
		
		self.msg(who_string)
```

**Comment by BlauFeuer** [comment]
It seems as if your `None` entries in who are from pre-log in sessions that are sitting idle and not logging in for some reason.

 By default, your superuser account would see the IP address of the incoming session in the who command output.  While others should have the pre-login sessions filtered out, you probably want to list them along with their IP address and connection type for your superuser.

Then if you see a pattern of malicious intent, you can act accordingly with that particular IP address.

However, if you suspect the active sessions are simply coming from a source where the person connected but forgot to log in, you might eventually determine who it is and mention it to them.

Additionally, if you believe the sessions are accumulating and want to assume it's a bug, it's best to have superuser able to see them in the who list instead of ignoring them and not know their source.  I have not seen this problem, but if you are, the more information you can provide us, the better chance we would have of reproducing it and correcting it, assuming it is actually a bug.

Most mu* will disconnect pre-login sessions if they are idle or do not log in after a few minutes, however I have seen some mu* that allow users to hang out at pre-login and do specific activities or observe global channel messages (such as quest completions or mob boss kills).

Evennia likely does not disconnect pre-login sessions - but it could be a feature request to enable a timeout.  I would not expect it to be an optional behavior one way or the other, so as to be a game-specific choice.

**Comment by duanuys** [comment]
Thank you for your feedback. I will definitely scout it out for a bit and come back if it is in fact a bug.
