### ISSUE TITLE
Demo server Traceback: `get weapon` @ Stone sarcophagus may fail to yield weapon

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1044]
#### Brief summary of issue / Description of requested feature:

`get weapon` @ Stone sarcophagus may fail to yield weapon, but yields Traceback of spawn error.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `get weapon` @ Stone sarcophagus
**Only occurs when receiving a particular weapon.**

#### Error output / Expected result of feature
```
Traceback (most recent call last):
  File "/home/griatch/evennia/evennia/commands/cmdhandler.py", line 464, in _run_command
    ret = yield cmd.func()
  File "/home/griatch/evennia/evennia/contrib/tutorial_world/objects.py", line 1007, in func
    self.obj.produce_weapon(self.caller)
  File "/home/griatch/evennia/evennia/contrib/tutorial_world/objects.py", line 1064, in produce_weapon
    wpn = spawn(WEAPON_PROTOTYPES[prototype], prototype_parents=WEAPON_PROTOTYPES)[0]
KeyError: 'ornate_longsword'

An untrapped error occurred.
(Traceback was logged 2016-09-06 14:17:04-0000).
```

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Evennia 0.6.0 (rev 614a991) demo server

**Comment by Griatch** [comment]
Turns out this was not an Evennia bug but a pure demo game bug. This was due to me loading a pre-exising database that had the longsword stored with the old name `ornate_longsword`. The new code calls it `ornate longsword` (with a space). It tried to use the old name to load the new. After just renaming this in the Attribute on the demo, this is fixed. Next time I reset the demo I'll rebuild the tutorial world from the batch script instead, then this won't be a problem.
