### ISSUE TITLE
Bug: passing objects to options in msg() will generate a pickling error

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1066]
#### Brief summary of issue / Description of requested feature:
So I had a 'shout' command that would pass a message to exits, who would then check whether to pass the message along to their destination. In the options dict for msg(), I was passing along the room that was the origin of the location, as well as a list that recorded each room that had seen the message to avoid duplicate messages - when they saw the message, they were appended to the list. Having either objects in the list or as the origin generated a traceback that noted a pickling error, as seen here: http://pastebin.com/W2Ng3YSe 

#### Steps to reproduce the issue / Reasons for adding feature:

1. @py self.msg("testing", options={'foo':self})

#### Error output / Expected result of feature
The above traceback, noting function object has no __qualname__ attribute

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
The workaround I'm doing is just passing object.ids to options.

**Comment by Griatch** [comment]
This is the expected behavior; `msg()` is used to send data to the Portal (and by extension to the clients). The `options` are used by the Portal-side protocols to customize the final step of sending the data to the client (for example to toggle ANSI parsing etc which happens differently depending on the client). The Portal nor the Clients have database access and so have no use for database ids, nor can it recover database objects on the other side of the AMP connection. It could never do this, it was never the purpose of the Portal. Data is pickled across the AMP connection (so you can e.g. send lists), but it does not parse for database objects (which cannot be pickled) since the Portal should have no database access and could not re-load them on the Portal side anyway. 

Using `msg()` to send data to Exits sounds like the wrong use of `msg()` overall; As said, the `msg()` goes to the Portal, and the client can't handle raw objects. If you rather refer to something like `msg_contents` (not raw `msg`), then you must clean the kwarg before you pass it to `msg`; rather than using `msg_contents` you must  instead loop over `self.contents` to have full control over how to treat each message.
