### ISSUE TITLE
Bug: @players dbref was wrong

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#1067]
#### Brief summary of issue / Description of requested feature:
@players dbref was wrong

#### Steps to reproduce the issue / Reasons for adding feature:

1. command '@objects' dbref was right
2.  but command '@players' dbref was wrong
3.  '@players' dbref is just an order (e.g. #1, #2, #3, #4, ...)

**Comment by Griatch** [comment]
@aceamro 

From what I understand you are likely misinterpreting what those `#dbrefs` are. A `#dbref`is a unique database-id of the entries of *a specific database table in the database*.  The `@players` command lists the `#dbrefs` of the *PlayerDB* database table while `@objects` show `#dbrefs` from the *ObjectDB* database table. Each table has separate ranges of `#dbrefs` that increase independently. So it's not an error to have, for example, a large number of Object-dbrefs while having only a few Player-dbrefs. 

Closing this. If I misunderstood you and there is an actual bug here you can still comment and request to re-open.
