### ISSUE TITLE
Allow single quotes in character names

### ISSUE THREAD

**Issue by robbintt** [evennia/evennia#1081]
Update regular expressions to allow single quotes in character names.

**Comment by BlauFeuer** [comment]
Do you mean "player" names?  I have not had any problems with single quotes in rooms, characters, exits, or things.  Places like Hawai'i, Maui, O‘ahy, Kaho‘olawe, Lana‘i, Moloka‘i, Kaua‘i, and Ni‘ihau... or possessives, like Lady's purse, a character named Pth’thya-l'ya, or O’Brien, D’Angelo.

I'm not sure the bulk of the code can handle player names with apostrophes.  I've seen strange issues since forcing a player name in the database.

**Comment by robbintt** [comment]
Corrected, thanks.

**Comment by Griatch** [comment]
If this is actually about Players rather than Characters, this seems to be a rephrasing of  bug #1076 into a feature request? Better to handle the solution of Player names with apostrophes in #1076 rather than opening two issues. Closing this. If I misunderstood and there is indeed an issue with Characters, reply here and I can reopen this.

**Comment by robbintt** [comment]
This is a feature request.
