### ISSUE TITLE
Autoconnects in Atlantis client don't work for Evennia

### ISSUE THREAD

**Issue by rozzingit** [evennia/evennia#1122]
#### Brief summary of issue / Description of requested feature:

Evennia doesn't seem to play well with the autoconnect feature on the [Atlantis client](http://riverdark.net/atlantis/), requiring typing out the connection command every time.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Save a world in Atlantis's address book with character login details.
2. Connect to Evennia.
3. Get feedback instead of logging in automatically.

#### Error output / Expected result of feature

Auto-connection attempts are often spit back as if they were preceded by a mess of characters, such as:
`Command 'ÿûcon Character Password' is not available. Type "help" for help.`

Or even as much mess as:
`Command 'ÿûÿúj%ÿðÿûÿýVÿþFÿþEÿþÉÿþ[connect Character Password' is not available. Type "help" for help.`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

@packetdancer, the creator of Atlantis, can probably help with this.  I know she was poking at things on her end, and I'm sure she'd be happy to share Atlantis files.

**Comment by Packetdancer** [comment]
For what it's worth, the issue seems to be that Atlantis' connection flow gets Evennia's parser into a weird state; the characters in question map out as Telnet IAC sequences, at least in some of my testing.  Waiting two seconds or so to allow all IAC negotiation to complete and then entering the login by hand seems to work fine, however.

I've managed to reproduce it with at least one other MU* client as well, an old one called Mudwalker.

I've been trying to debug this in my spare time in hopes of generating a patch, but I've been swamped with my day job and that's as far as I've gotten yet, since it's been a while since I tried to dig into Twisted for anything.  Even more obnoxiously, the bug doesn't present reliably on my test Evennia install to debug in the first place, while it presents 100% of the time on Arx's Evennia install (0.6.0 301efe4).

**Comment by Griatch** [comment]
The reason for this is not clear, but sounds likely to be due to timing. Evennia's telnet connection happens at Evennia's Portal layer, which then needs to inform the Server about the new connection. But several MUD-specific telnet negotiations like TTYPE requires several exchanges between the server and portal (their speed depending on the network connection) meaning the Portal will update the session again when it has all the (potentially delayed) info. While this sync is normally very fast, the timing may vary depending on the hardware. The automatic login sending data faster than the sync can happen should normally be fine - the data should be queued. Maybe there is something going wrong in that queuing mechanism for this particular state of the connection, definitely worth looking into. 

@Packetdancer 
Thanks for looking into this as well, always good to see active client devs around!

**Comment by Griatch** [comment]
I thought I could check this using some other clients, but truth is I have now tested a whole bunch of standard clients (well as standard as things get in mu world), including tintin++ and potato, mudlet, mushclient and others supporting auto-login we need. So far I cannot replicate this problem on any of them. I log in immediately or sometimes with half a second delay. Some other clients send auto-login info in a DIKU format (name as a single command, then the password as another command) and won't work but at no point have I observed any garbled text. 

Unfortunately I do not own a mac for testing Atlantis, so I'm at an impasse at this point. Maybe someone else can look into it. The first information needed would be debug information 
about what exactly is sent to and from Evennia:

- Adding a print statement `print("portalsessionhandler.data_in:", session, kwargs)` at https://github.com/evennia/evennia/blob/master/evennia/server/portal/portalsessionhandler.py#L357
- Adding a print statement `print("portalsessionhandler.data_out:", session, kwargs)` at  https://github.com/evennia/evennia/blob/master/evennia/server/portal/portalsessionhandler.py#L402 (this second one may fail if there are weird characters in the output at this point, one may need to experiment with force-converting it to a string with `str()`.)
- If the characters being returned are telnet IAC sequences, the client's TTYPE handshake might be confused somehow with the data. I would need the actual character codes coming out of the server to determine that.

**Comment by Packetdancer** [comment]
Sorry, I never did add my further investigations.

Weirdly, I still cannot reproduce this properly on my own Evennia install.  I see a different issue entirely (namely, the automatic login doesn't work AT ALL, because Atlantis apparently sends things so quickly that not everything's connected up; it never even hits data_in, but when I enter things by hand it works fine).  If I add an event in Atlantis to send the login again a couple of seconds later, it works fine on my test game.

However, on Arx, the first login seems to be dropped, but if I add the automated login event, I get what Roz describes above.  So if I let Atlantis just log in Aislin or Hana, nothing happens and I still sit at the login screen until I enter the connect command manually.  If I add an event to send the login command after connecting (which still happens very rapidly), that's when I get the garbage data that Roz describes above.

I cannot reproduce this on any other Evennia server I've attempted since starting to investigate; it *only* happens on Arx (though the automated login being eaten happens on all of them).  Unfortunately, I have no way to further investigate this from the server side on Arx; we might need to tag Tehom into the process.

**Comment by Packetdancer** [comment]
I should add that, just for the sake of sanity checking, I also shut down the test Evennia server and ran a MUX 2.10 server on the same machine/port, containing a user with the same name/password.

Autoconnect worked fine on MUX2, but shutting the MUX down and switching back to Evennia still left me at the login screen.

**Comment by Griatch** [comment]
@packetdancer So does Atlantis wait for the connection to finish and then immediately send the "connect username password" string, or does it wait for the telnet subnegotiations first? 

I will try to build a faux client that very quickly sends the login info to test. To try to reproduce the situation of what happens at the very first connect - on the Atlantis homepage I see it supports MCCP (which Evennia supports) and MCP (which Evennia does not). I don't see a mention of TTYPE, NAWS, MSDP/GMCP, just to confirm those can be ruled out (not all clients document all their telnet support).

**Comment by Packetdancer** [comment]
TTYPE, NAWS, and CHARSET are supported, yes.  TTYPE should return 'Atlantis' for the client information.

The connection string is sent immediately upon connection, rather than waiting for telnet negotiation; I used to do it the other way, but encountered several MUD variants that would not begin telnet negotiation until they received text, so I ended up switching the logic.

**Comment by Packetdancer** [comment]
(I can also connect Atlantis to a testbed server for you, if you want to compare directly.)

**Comment by Griatch** [comment]
Thanks, that might indeed be useful in the future, can't check it out right now though. Will see if it's a timing issue first, by making a very fast-sending dummy client.

**Comment by TehomCD** [comment]
I can't offhand think of anything Arx would be doing that would be different from a vanilla Evennia install as far as the login process goes. I'm pretty clueless when it comes to network stuff though, so if you can think of anything that might cause a problem from Evennia's settings file, I could list out the relevant settings from Arx to take a look.

**Comment by Griatch** [comment]
@packetdancer, @TehomCD: To test this, I created the most slimline and fast telnet client imaginable: It connects to a game and immediately on connection sends the "connect name password" string and prints what it gets back. 

In testing I do see garbled text returned, this is due to Evennia immediately sending the telnet negotiation upon connection (which my dummy client of course can't handle). This is expected behavior, it's the handshake telling the client what the server supports and asking the client to report its status. After seeing this string however, Evennia then correctly logs me in, so even with this extremely fast login I cannot reproduce the issue. 

Translated to numbers, this is the telnet handshake Evennia sends (adding spaces for readability): 

    255 253 31 255 253 24 255 251 86 255 251 70 255 251 69 255 251 201 255 251 91

Which means 

    IAC DO NAWS      # ask client to report its window size
    IAC DO TTYPE     # ask client to identify itself and its capabilities
    IAC WILL MCCP    # server offers stream compression if client wants it
    IAC WILL MSSP    # server offers to report its status to a Mud listing if client wants it
    IAC WILL MSDP    # server offers out-of-band MSDP data services if client wants it
    IAC WILL GMCP    # server offers out-of-band GMCP data services if client wants it
    IAC WILL MXP     # server offers MUD extensions (clickable links) if client wants it

I have run the speed-connect dummy client both locally, against the Evennia demo server and against Arx (logging in as guest). In all cases I login correctly. My simple dummy client of course just prints the initial telnet negotiation string. I suspect Atlantis should *not* be printing IAC-prefixed instructions to the output regardless of when it arrives, but I don't recall exactly how the protocol looks on the client side. 

At this point I don't know if it's much more I can do to test this - Evennia behaves as expected (according to the standard specification) and is actually *very* fast about it. I don't know if a MUSH server is just slower or deliberately delays the handshake but as far as Evennia is concerned, everything appears to react and be processed at max speed; with this simple client the entire login and authentication process happens in about a tenth of a second or so (1/2 a second remotely on Arx). 

As far as I know, neither the telnet client nor the -server are dictated by the protocol to await the completion of the telnet handshake before allowing data transfer. Could maybe Atlantis be expecting a delay upon connect that it doesn't see with Evennia? If this could be shown to be the case we could delay things on the Evennia side I guess, but it would have to be a general synthetic slowdown since this all happens long before the TTYPE negotiation has completed and Evennia knows which client has connected.

**Comment by Packetdancer** [comment]
I should note it's not actually *Atlantis* showing the garbled text.  What happens is the garbled text is returned in the 'no such command' portion from Evennia.

Specifically, it seems that the Telnet IAC sequences that Atlantis sends back are captured in Evennia's INPUT buffer, and treated as part of the command entered.  For instance (copied from my own login window right now):

Command 'ÿûÿúR0ÿðÿûÿýVÿþFÿþEÿþÉÿþ[connect Aislin <password>' is not available. Type "help" for help.

This is the thing that only happens on Arx.  On other games, the autoconnect attempt is merely silently eaten.

**Comment by Griatch** [comment]
@Packetdancer 

Hm, I see what you mean: Would it be correct to say that Atlantis returns the telnet handshake sent by Evennia just *before* the login text, and that is what is coming back?

**Comment by Griatch** [comment]
Is there some way to decode exactly what Atlantis is sending out (in telnet instructions) compared to what you get back?

**Comment by Packetdancer** [comment]
Unfortunately, not easily.  The problem is that Atlantis 1.x no longer compiles on modern macOS X (though still runs fine), which is why I've been working on a complete clean rewrite for modern macOS.  I may be able to go dig up my older 10.6 image and run Atlantis in the debugger, however.

**Comment by Packetdancer** [comment]
(That said, yes, from what I can see it seems to be correct that Atlantis's telnet handshake response is getting sent just before the login text, and so somehow gets caught up in the input buffer.)

**Comment by Griatch** [comment]
@Packetdancer: I need to see what is coming in to try to figure out where things to wrong, because it's not obvious in the input parser. Basically, anything starting with IAC will be whiffed off to be handled as a telnet instruction, so if the IAC-prefixed handshake is sent just *before* the command text, for example without a line break, it would make more sense for it to just be eaten and disappear (which you see locally) than the IAC instruction ending up being treated as a user command input (like seen on Arx). 

This could be useful to test if you have a local setup of Evennia (since you get a loss of data there). Maybe we could get @TehomCD to put this printout in Arx too to see if one can see what goes in when things go awry: 

On the lines above https://github.com/evennia/evennia/blob/master/evennia/server/portal/telnet.py#L192 
```python
    print ("telnet in:", data, self.iaw_mode)
    if data.startswith(chr(255)):
        print ("Telnet IAC:", " ".join(str(ord(ch)) for ch in data))
    else:
        print ("No IAC detected.")
```
If it would be possible to get that printout from Atlantis autoconnecting we might get a bit closer to the solution.

**Comment by Packetdancer** [comment]
So, here's the log from my testbed game.  You can see the login is genuinely received, but it never processes it; there's never the actual 'Session logged in!' notice.  

```
2016-11-25T09:16:51+0000 [stdout#info] portalsessionhandler.data_out: <evennia.server.portal.telnet.TelnetProtocol object at 0x10570b8d0> {'text': [["{b=============================================================={n\n Welcome to {gPaxtest{n, version 0.6.0 (rev 317b456)!\n\n If you have an existing account, connect to it by typing:\n      {wconnect <username> <password>{n\n If you need to create an account, type (without the <>'s):\n      {wcreate <username> <password>{n\n\n If you have spaces in your username, enclose it in quotes.\n Enter {whelp{n for more info. {wlook{n will re-show this screen.\n{b=============================================================={n"], {'options': {}}]}
2016-11-25T09:16:51+0000 [stdout#info] ('telnet in:', '\xff\xfb\x1f\xff\xfa\x1f\x00R\x000\xff\xf0\xff\xfb\x18\xff\xfdV\xff\xfeF\xff\xfeE\xff\xfe\xc9\xff\xfe[connect Pax testme\n', False)
2016-11-25T09:16:51+0000 [stdout#info] ('Telnet IAC:', '255 251 31 255 250 31 0 82 0 48 255 240 255 251 24 255 253 86 255 254 70 255 254 69 255 254 201 255 254 91 99 111 110 110 101 99 116 32 80 97 120 32 116 101 115 116 109 101 10')
2016-11-25T09:16:51+0000 [stdout#info] ('telnet in:', '\xff\xfa\x18\x00Atlantis\xff\xf0', False)
2016-11-25T09:16:51+0000 [stdout#info] ('Telnet IAC:', '255 250 24 0 65 116 108 97 110 116 105 115 255 240')
2016-11-25T09:16:51+0000 [stdout#info] ('telnet in:', '\xff\xfa\x18\x00Atlantis-256color\xff\xf0', False)
2016-11-25T09:16:51+0000 [stdout#info] ('Telnet IAC:', '255 250 24 0 65 116 108 97 110 116 105 115 45 50 53 54 99 111 108 111 114 255 240')
2016-11-25T09:16:51+0000 [stdout#info] ('telnet in:', '\xff\xfa\x18\x00xterm-256color\xff\xf0', False)
2016-11-25T09:16:51+0000 [stdout#info] ('Telnet IAC:', '255 250 24 0 120 116 101 114 109 45 50 53 54 99 111 108 111 114 255 240')
```

I am, however, now also able to produce the same issue I see on Arx if I use Atlantis' event system to send a "connect Pax testme" line immediately on connection; in that case, the event one is sent before the normal autoconnect, and the line with the IAC is parsed by the command parser and rejected (hene the garbage text Roz reports), in which case we get:


```
2016-11-25T09:25:35+0000 [stdout#info] portalsessionhandler.data_out: <evennia.server.portal.telnet.TelnetProtocol object at 0x105724790> {'text': [["{b=============================================================={n\n Welcome to {gPaxtest{n, version 0.6.0 (rev 317b456)!\n\n If you have an existing account, connect to it by typing:\n      {wconnect <username> <password>{n\n If you need to create an account, type (without the <>'s):\n      {wcreate <username> <password>{n\n\n If you have spaces in your username, enclose it in quotes.\n Enter {whelp{n for more info. {wlook{n will re-show this screen.\n{b=============================================================={n"], {'options': {}}]}
2016-11-25T09:25:35+0000 [stdout#info] ('telnet in:', 'connect Pax testme\n\xff\xfb\x1f\xff\xfa\x1f\x00R\x000\xff\xf0\xff\xfb\x18\xff\xfdV\xff\xfeF\xff\xfeE\xff\xfe\xc9\xff\xfe[connect Pax testme\n', False)
2016-11-25T09:25:35+0000 [stdout#info] No IAC detected.
2016-11-25T09:25:35+0000 [stdout#info] portalsessionhandler.data_in: <evennia.server.portal.telnet.TelnetProtocol object at 0x105724790> {'text': 'connect Pax testme'}
2016-11-25T09:25:35+0000 [stdout#info] portalsessionhandler.data_in: <evennia.server.portal.telnet.TelnetProtocol object at 0x105724790> {'text': '\xff\xfb\x1f\xff\xfa\x1f\x00R\x000\xff\xf0\xff\xfb\x18\xff\xfdV\xff\xfeF\xff\xfeE\xff\xfe\xc9\xff\xfe[connect Pax testme'}
2016-11-25T09:25:36+0000 [stdout#info] Session logged in!
2016-11-25T09:25:36+0000 [stdout#info] portalsessionhandler.data_out: <evennia.server.portal.telnet.TelnetProtocol object at 0x105724790> {'text': [['[MudInfo] [MudInfo, 2016-11-25(09:25)]: |GPax connected|n'], {'options': {'from_channel': 2}}]}
2016-11-25T09:25:36+0000 [stdout#info] portalsessionhandler.data_out: <evennia.server.portal.telnet.TelnetProtocol object at 0x105724790> {'text': [['\nYou become {cPax{n.\n'], {'options': {}}]}
2016-11-25T09:25:36+0000 [stdout#info] portalsessionhandler.data_out: <evennia.server.portal.telnet.TelnetProtocol object at 0x105724790> {'text': [['{cLimbo(#2){n\nWelcome to your new {wEvennia{n-based game! Visit http://www.evennia.com if you need\nhelp, want to contribute, report issues or just join the community.\nAs Player #1 you can create a demo/tutorial area with {w@batchcommand tutorial_world.build{n.'], {'options': {}}]}
2016-11-25T09:25:36+0000 [stdout#info] portalsessionhandler.data_out: <evennia.server.portal.telnet.TelnetProtocol object at 0x105724790> {'text': [['Command \'\xc3\xbf\xc3\xbb\x1f\xc3\xbf\xc3\xba\x1f\x00R\x000\xc3\xbf\xc3\xb0\xc3\xbf\xc3\xbb\x18\xc3\xbf\xc3\xbdV\xc3\xbf\xc3\xbeF\xc3\xbf\xc3\xbeE\xc3\xbf\xc3\xbe\xc3\x89\xc3\xbf\xc3\xbe[connect Pax testme\' is not available. Type "help" for help.'], {'options': {}}]}
```

**Comment by Packetdancer** [comment]
Yeah, looking deeper at telnet.py, it only seems to check the first byte of data for IAC, and it never seems to parse other commands out.  If I use a TCP proxy to split the telnet and connection sequences into two separate writes, it works fine.  But if it receives them in the same telnet_in call, things go sideways; either the first part is an IAC (in which case any actual text is eaten and discarded), or the first part is not an IAC sequence (in which case it's never parsed as such, and ends up in the command buffer).

Based on this, I could write/test a patch and submit a pull request, but if you've got the bandwidth it's probably faster for you to do so; you know your code better than I do, to know if there's any consequences to the tweak. :)

**Comment by TehomCD** [comment]
Just to follow up and confirm what @Packetdancer saw with Arx's logs, here's a sample of a player trying to autoconnect with Atlantis, I believe:
`2016-11-25T04:14:40-0500 [stdout#info] No IAC detected.
2016-11-25T04:14:40-0500 [stdout#info] ('telnet in:', '\xff\xfa\x1f\x00\\\x00"\xff\xf0\xff\xfb\x18\xff\xfdV\xff\xfeF\xff\xfeE\xff\xfe\xc9\xff\xfe[connect [REDACTED]\n', False)
2016-11-25T04:14:40-0500 [stdout#info] ('Telnet IAC:', '255 250 31 0 92 0 34 255 240 255 251 24 255 253 86 255 254 70 255 254 69 255 254 201 255 254 91 99 111 110 110 101 99 116 32 83 111 112 104 105 101 32 108 105 103 104 116 98 114 105 110 103 101 114 10')
2016-11-25T04:14:40-0500 [stdout#info] ('telnet in:', '\xff\xfa\x18\x00Atlantis\xff\xf0', False)
2016-11-25T04:14:40-0500 [stdout#info] ('Telnet IAC:', '255 250 24 0 65 116 108 97 110 116 105 115 255 240')
2016-11-25T04:14:40-0500 [stdout#info] ('telnet in:', '\xff\xfa\x18\x00Atlantis-256color\xff\xf0', False)
2016-11-25T04:14:40-0500 [stdout#info] ('Telnet IAC:', '255 250 24 0 65 116 108 97 110 116 105 115 45 50 53 54 99 111 108 111 114 255 240')
2016-11-25T04:14:40-0500 [stdout#info] ('telnet in:', '\xff\xfa\x18\x00xterm-256color\xff\xf0', False)
2016-11-25T04:14:40-0500 [stdout#info] ('Telnet IAC:', '255 250 24 0 120 116 101 114 109 45 50 53 54 99 111 108 111 114 255 240')`

**Comment by Griatch** [comment]
@Packetdancer Cool, now we are getting somewhere! As you say, Evennia's telnet parser detects the IAC only if it's the first on the line. It looks like it should really be pre-splitting the data on `\n\r` (or, even safer, split it on IAC itself) and then loop over all subsections and check `subdata.startswith(IAC)`. 

Any change to the IAC parsing may have potential consequences with particular clients (it's surprising how sensitive this can be), but this should hopefully be a safe extension.I won't have time to do code until this evenening or until the weekend, so if you want to suggest a PR, feel free! 

One thing that confuses me however is with this line,

    2016-11-25T09:25:35+0000 [stdout#info] ('telnet in:', 'connect Pax testme\n\xff\xfb\x1f\xff\xfa\x1f\x00R\x000\xff\xf0\xff\xfb\x18\xff\xfdV\xff\xfeF\xff\xfeE\xff\xfe\xc9\xff\xfe[connect Pax testme\n', False)

I read this as `<loginstring> + <telnet instruction> + <loginstring>`. The first `<loginstring>` comes from the debug event you created I take it. But where is the second coming from? Is this the "normal" auto-login string? But normally, Atlantis does not send that first debug event - and this is necessary in order to bypass Evennia's IAC check. So why does the "garbled text+command" error appear on Arx, presumably without the user having set up that initial event?

**Comment by Packetdancer** [comment]
You're correct; that first one comes from the debug event.  However, anyone can create the debug event using Atlantis' visual event-creation system, and a number of Arx players do in fact do so in order to provide some measure of auto-login.  Hence where the garbage data comes from.

**Comment by Griatch** [comment]
Ah, so it's actually a reduntant thing, that explains it. Of course, ince working, using both an event *and* the auto-login feature will actually give an error on the auto-login (since at that point the user is already connected).

**Comment by Packetdancer** [comment]
Right.  Of course, if you use the event but turn off the autologin, then you log in fine but get the "no such command" on whatever you first type once connected, because the IAC goo is still sitting in line_buffer waiting for the next linefeed.  Next linefeed?  That line_buffer is happily eaten.

As for the split on IAC, that'd almost work, but the issue is that you'll still have the last sequence (IAC DON'T MXP) immediately before connect.  So you'd end up breaking it down and getting "\xFF\xFE\x5Bconnect Pax testme" and you'd still have the same problem, where the 'connect Pax testme' was eaten by TelnetProtocol.

Basically, the fix is twofold.  First, the portion that checks for IAC codes needs to preserve the rest of 'data' (rather than just eating it wholesale if the first character is an IAC) and put any non-Telnet data into line_buffer for the next time through.  This fixes the actual autoconnect case.  Unfortunately, as I haven't touched Twisted in ages, I'll admit I don't remember what the best way to do that would be; TelnetProtocol doesn't seem to spit out the remainder into anything useful to grab and process it.  (no rawDataReceived, it doesn't go into lineReceived as with StatefulTelnetProtocol, etc.)

Second, the portion that handles leftover data needs to actually parse that leftover data to make sure it doesn't contain telnet codes, which fixes the 'garbage data' issue; if it doesn't, then you just have a blob of telnet negotiation responses in the line_buffer.  That fixes the situation with the test command added in, and is least a fairly straightforward fix.

**Comment by Griatch** [comment]
Fair points. I guess *in principle* one could regex the whole thing to split out IAC-prefixed byte codes. The system must also handle telnet codes split over multiple data packets. I'd need to actually toy with it to see how to make it actually efficient. As far as I know, Twisted's telnet doesn't itself offer a parsing mechanism for it but that said this is one of the oldest part of the codebase so it could be worth looking into again.

**Comment by Griatch** [comment]
Looking more at this, I think there could be some considerable cleanup in the telnet protocol to better make use of Twisted's functionality. That goes beyond a simple patch though; I'll look into this in the next few days.

**Comment by Packetdancer** [comment]
I suspect the best approach is to take the input buffer, run through and find any IAC character, then parse the following bytes to get the appropriate sequence.  Once done, remove that sequence from the input buffer, then parse the remainder as actual input.  (After all, while it's unbelievably unlikely that you'll have a telnet sequence somewhere in the middle of a line of input, rather than before/after the main text, there's nothing in the protocol specification that actually prohibits a client doing so.)

If I have time this weekend, I may try to brush off Twisted and see if I can remember the best way to do something like this within the Twisted transport/protocol design, in which case I'll get you a patch.  Otherwise, I'll just leave this to you.

Either way, I'm glad we tracked down the root cause!

**Comment by Griatch** [comment]
@Packetdancer, @TehomCD: I made a rewrite of the Telnet protocol to basically fall back fully to Twisted's own parser; things have improved with that since Evennia originally created its telnet module many a year ago. I *think* this should resolve this issue, but please check with your respective setups.

**Comment by TehomCD** [comment]
Tentatively appears to be working - a player reported that their auto-login is now functioning.

**Comment by rozzingit** [comment]
The player was totally me screaming loudly in excitement.

**Comment by TehomCD** [comment]
This seemed to introduce a new issue for a different client. A player using "duckclient" (who names these things?) says that their connection is terminated immediately after they see the login screen.

**Comment by BlauFeuer** [comment]
Broken for me, using BeipMU.  I suspected it would break for other clients, too. Griatch is working on something that will split the lines when sent like this: ('data:', 'look\nlook\n')

**Comment by Griatch** [comment]
Sigh. One should really not touch these things.

**Comment by TehomCD** [comment]
I'm not sure if this was covered by what @BlauFeuer was seeing, but this also seems to introduce breaking up long text strings into separate commands by adding a carriage return at some character limit: can test by sending yourself a page of some extremely long text string, or trying to set a desc of a long text string, etc, where you'll see `Command <some portion of the text string after a cutoff> is not available.`

**Comment by BlauFeuer** [comment]
Not what I was seeing or mentioning, but I think it's a symptom of twisted's length limit, and for some reason it just splits it at a certain character length limit, adding another knot to the Gordian rope.

**Comment by Griatch** [comment]
I added an update to handling the line breaks, mainly in response to @BlauFeuer's original feedback.

@TehomCD  Not sure why there would be an insta-death of the duckclient. I cannot reproduce the cutoff of page with the latest code (nor with the previous commit) using `@py self.player.execute_cmd("page self = %s" % ("blah " * 1000))`. Could you give an example of a failing string getting spurious line breaks?

**Comment by BlauFeuer** [comment]
That works on auto-login and pre-login, too.  I haven't seen the long line split yet. 

And it does close the door on DuckClient v3.8 on connect.

**Comment by TehomCD** [comment]
Just tested, and your latest change fixed the line break issue with very long commands. Duckclient is still having issues though, so that appears to be unrelated.

**Comment by BlauFeuer** [comment]
I confirmed that the DuckClient issue is unrelated to this fix by using the pre-updated version and seeing the same problem.  It would be a new issue.

**Comment by Griatch** [comment]
So I fixed the DuckClient issue, it was unrelated to this particular issue but rather due to DuckClient sending its TTYPE in a slightly different format than other clients. 

It seems the revisions fixed the remaining problems. It seems this closes this issue unless @Packetdancer sees some remaining errors for her setup.

**Comment by Packetdancer** [comment]
Nope!  That deals with the issue I saw from Atlantis' side, and looking at the code, it looks like it'll handle any reasonable Telnet control sequence situation I can think of.  Thank you! :)

**Comment by Griatch** [comment]
Excellent, thanks yourself (and the others in this thread) for all the help!
