### ISSUE TITLE
default command 'allcom' traceback with no arguments

### ISSUE THREAD

**Issue by ANiChowy** [evennia/evennia#1123]
#### Brief summary of issue / Description of requested feature:
Vanilla install. Server initially ran with mulitsession mode at it's default, changed to 2 later.
'allcom' with no arguments present throws a traceback.

input/output:
http://pastebin.com/XPQQDNFt

#### Steps to reproduce the issue / Reasons for adding feature:

1. 'allcom'
2. traceback expected as output

#### Error output / Expected result of feature

intended behavior via help : "Without argument, works like comlist."

traceback from terminal:

2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent c
all last):
2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::]   File "e:\code\mud\even
nia\evennia\commands\cmdhandler.py", line 489, in _run_command
2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::]     yield cmd.parse()
2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::]   File "e:\code\mud\even
nia\evennia\commands\default\muxcommand.py", line 141, in parse
2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::]     self.character = sel
f.caller.get_puppet(self.session)
2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::]   File "e:\code\mud\even
nia\evennia\players\players.py", line 329, in get_puppet
2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::]     return session.puppe
t
2016-11-15T09:38:05-0500 [AMPProtocol,0,127.0.0.1] [::] AttributeError: 'NoneTyp
e' object has no attribute 'puppet'

(http://pastebin.com/Rm3368DX)

**Comment by ANiChowy** [comment]
for session rerouting to function, all commands should have references to self instead of caller,

in allcom's definition, it has this line when no arguments are supplied:
'caller.execute_cmd("@channels")' (line 220, comms.py)

this seems like the likely culprit to me?

**Comment by TehomCD** [comment]
It looks like player.execute_cmd() will fail when not passed a session argument due to https://github.com/evennia/evennia/blob/master/evennia/players/players.py#L450 - it'll call cmdhandler with session=None, which leaders to cmd.session = None, which leads to parse() generating an AttributeError for a MuxPlayerCommand by calling get_puppet(None), which raises the attribute error through None.puppet. So the solution would be changing caller.execute_cmd to also pass along session=self.session, most likely.

**Comment by Griatch** [comment]
In lower multisession modes there is only one session while for higher modes there is no way to know which session is necessarily sending it (and assuming the first or pick one if there is only one will lead to hard-to-track bugs). So that makes some sense. However, also NPCs should be able to use `execute_cmd` so it should not traceback on a lack of Session.
