### ISSUE TITLE
Heartbeat shows as � character when UTF-8 is enabled with the blowtorch client.

### ISSUE THREAD

**Issue by jrsteensen** [evennia/evennia#1144]
#### Brief summary of issue / Description of requested feature:
Heartbeat shows as � character when UTF-8 is enabled with the blowtorch client.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Log onto evennia with Blowtorch Client
2. Wait for Heartbeat

#### Error output / Expected result of feature
For each heartbeat, a � character appears on the same line.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Running latest Evennia: rev 3109633

**Comment by jrsteensen** [comment]
Under any other encoding, various other characters are shown for the heartbeat. So UTF-8 is irrelevant to this issue with the Blowtorch client.

**Comment by BlauFeuer** [comment]
Just like Mukluk, this is a known issue in Blowtorch - and it's quite simply due to both of those clients not complying with Telnet protocol, specifically when it receives the "Interpret as Command" (IAC) escape character (FF).

A work-around for those using clients like this is to send the command `@option NOPKEEPALIVE=off` for the session, or use the `/save` parameter to disable it for that Evennia player permanently.

**Comment by jrsteensen** [comment]
I do have this worked around with a gag trigger on the heartbeat character in Blowtorch. I'll add it to the wiki as a workaround.

**Comment by BlauFeuer** [comment]
The caveat is that when NOPKEEPALIVE is disabled that there is no more heartbeat

Clients making a connection through a buggy router that is pruning the connections and causing disconnects will not be "kept alive". The client may experience disconnects that would otherwise be avoided.  Using TCP/IP keepalive is the best option.

**Comment by jrsteensen** [comment]
Thanks BlauFeuer. Updated [wiki](https://github.com/evennia/evennia/wiki/Client-Support-Grid).
