### ISSUE TITLE
Merge GenderSub and RPSystem Contribs?

### ISSUE THREAD

**Issue by jrsteensen** [evennia/evennia#1151]
#### Brief summary of issue / Description of requested feature:  
Gender substitution is a fairly basic and extremely widespread feature on RP games.
Request is for gendersub to be merged with the RPSystem contrib, so one can simply call the RP system.

**Comment by BlauFeuer** [comment]
Specifically, you're talking about adding singular pronoun substitution into RPSystem's emote command such that it's based on a character's gender attribute.  In English, the singular pronouns have five cases: absolute, subjective, objective, possessive, and reflexive, In Tiny-mu* systems, it is common for the substitution system to have the symbol letter capitalized if the substitution should also be.

Name                   | Symbol  | gender identity pronouns
-----------------------|:----------:|-------------
absolute possessive   | a/A | his/hers/its
subjective pronouns  | s/S | he/she/it
objective pronouns    | o/O | him/her/it
possessive pronouns | p/P | his/hers/its
reflexive pronouns     | r/R |himself/herself/itself

In RP, it's also not uncommon for non-gender identity pronouns to be preferred, and in some of those cases, the plural pronoun "they" can be used in singular in the five modes in an effort to simply: their, they, them, theirs, themself.  In that case, there's no gender substitution taking place at all.

**Comment by jrsteensen** [comment]
@BlauFeuer : You absolutely nailed it.

**Comment by BlauFeuer** [comment]
The problem with merging the GenderSub contrib is that it's currently incomplete as a pronoun substitution system.

The GenderSub contrib is currently missing the reflexive case, and the term "neutral" does not mean "neuter", instead it _now_ means "ambiguous"  (even though it is still labeled as "neutral") per the suggested change #1146 

While this is fine for characters, it fails for objects that are actually neutral, meaning that the contrib only extends pronouns to class GenderCharacter and no other.   The problem comes when you want to include pronouns substitution to the RP System, which does include neutral items that are best singularly identified with the pronoun "it".

The ball, it rolls away. _not_ The ball, they rolls away.

**Comment by Griatch** [comment]
The RPSystem contrib uses _director stance_ emoting rather than _actor stance_ emoting. This neatly bypasses the nonsense of needing to know grammar terms to roleplay - just write what you refer to and don't care about from whose perspective your text will be read. Which is, IMO, a much easier thing for users to handle than having to build their emotes with a grammar-aware mini-language ala certain RPIs. 

So no, I won't spend any time adding gender substitution to the RPSystem when I specifically created it to get away from it.
