### ISSUE TITLE
Player using TinyFugue has xterm256 turn off whenever server reloads

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1218]
#### Brief summary of issue / Description of requested feature:
A player using the TinyFugue client reports that his xterm256, which is enabled by default when he logs in, for some reason turns off whenever the server reloads. He uses `@option/save xterm256=True` to reenable it, but he always sees it toggle off on server restarts.

#### Steps to reproduce the issue / Reasons for adding feature:

1. I'm assuming it's the TinyFugue client, since I can't think of anything else it could be.

#### Error output / Expected result of feature
xterm256 support turning off on a server `@reload`.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I'm using the default `@options` command, and I don't have anything else that in Arx that would produce this behavior as far as I know, so I'm assuming it's some weird client issue.

**Comment by Griatch** [comment]
@tehom I made a small change that allowed actually setting the option even though the client does not support it. I tested it both with Tinyfugue 4.0 stable (which does not support xterm256 at all) and the latest Tinyfugue 5.0 beta 8. Saving the `xterm256` setting in `@options` works for both and survive a both a shutdown and a reload continuously. 
Closing this. If the problem persists ... it might be related to your other issues since that would suggest the Server cannot correctly update itself to the Portal (saving the options to the portal at a reload for example).
