### ISSUE TITLE
Feature request: Disabling auto-login from website based on Player typeclass

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1247]
#### Brief summary of issue / Description of requested feature:
I have a player typeclass that should never use the auto-connect functionality from the website. I'd really like a hook to be checked before it's used, but I'm unsure where the code is that actually does the auto-connect to write it as a PR.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Prevent auto-connection/login on website and with web client based on Player typeclass.

#### Error output / Expected result of feature
Force players to have to log in manually for specific accounts.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Just a hook that would return a default value for things to continually working as normal that I could override in the appropriate typeclass would be great. Like:
```
def do_auto_connect(self):
    return True
```
as the default, and have it check `player.do_auto_connect` before doing the auto-connection and logging in on the website.

**Comment by Griatch** [comment]
See #1063; the auto-login functionality is going to change, see if that change fits your need. Either way this is indeed a separate functionality not covered by other changes as far as I can tell.
The auto-login mechanism is found both in the website views and in the portalsessionhandler since it makes use of Django''s secure Web sessions. 

It is not ideal to add a typeclass hook since the auto-login is unique to the web client and the server should generally not need to know which client is being used.  Worth pondering. 

Out of curiosity,  which of you players should not auto-login?

**Comment by TehomCD** [comment]
It's our guest typeclass - players can't log into them normally, only with a specific command from the connection screen, but the auto-connection functionality bypasses that. The issue it was causing is after multisession mode was enabled, the auto-connect would mean that the assignment of guests could cause different players to wind up on the same account. 

Anyway, from the link you provided, the change listed there should resolve it - as long as they're logged out of the website upon disconnecting, they shouldn't be able to reconnect to an occupied guest and cause the problem.

**Comment by Griatch** [comment]
I'm marking this here to note that it will close with the closing of #1063.

**Comment by Griatch** [comment]
Closed with the merger of `devel` branch.
