### ISSUE TITLE
Bug: Simpledoor does not report its open/close state properly

### ISSUE THREAD

**Issue by lmclarke** [evennia/evennia#1269]
#### Brief summary of issue
simpledoor.py's doors don't open and close.

#### Steps to reproduce the issue

1. Enable the simpledoor.py module
2. Create a door with "@open doorway:contrib.simpledoor.SimpleDoor = otherroom"
3. Close the new exit with "close doorway." It will report that you closed it.
4. Open the closed exit with "open doorway." It will report that it's already open, when it should not be -- it should be closed.

**Comment by vlegoff** [comment]
After testing, this issue is due to the fact that the state of a door (opened or closed) relies on locks.  The superuser isn't influenced by locks.  If you try the same thing while `@quell-ed` or with another character, the issue doesn't occur.  With a superuser, you can enter `close doorway` repeated times and always get the message "You close doorway." although the door is already closed at this point.  Similarly, a superuser can never use the `open` command, it will always be open for him/her.

@Griatch: I can try to fix this by relying on other things than locks to determine if a door is open or closed.  But it seems it's not really a bug, more a demonstration of the power of the superuser over its environment.

**Comment by BlauFeuer** [comment]
With Superuser power comes Superuser understanding requirement.

The tutorial gives a notice upon entry suggesting `@quell` - similarly, the door actions that are lock-affected could check and notify, or perhaps just the constructor actions might test and notice similarly, so that when a superuser makes a simple door, the superuser is reminded that its functions are for the less powerful types,

**Comment by Griatch** [comment]
I added a mention at the header of the simpledoor module about the effect of being superuser. Closing this.
