### ISSUE TITLE
should this print the raw string?

### ISSUE THREAD

**Issue by texdarkstar** [evennia/evennia#1301]
I have a prompt being stored on my character object.

    prompt = "\n> \n\n"

This is what I get when I use @examine on myself.

    prompt = 
    > 
    

Should this instead show the raw string?

**Comment by BlauFeuer** [comment]
`@set me/prompt = r"\n> \n\n"` seems to store the string raw and displays it back raw.

**Comment by BlauFeuer** [comment]
`@set me/prompt = |/> |/|/` stores the prompt as markup, which is then interpreted when rendered as the prompt, but not when examined.  Putting actual \n in the string would render them back as new lines when examined.

**Comment by texdarkstar** [comment]
Strange.
I used @set self/testattr = '\n> \n\n', and used @examine self, I saw the raw string then.
The only difference is that the prompt var was created with at_object_creation.

**Comment by texdarkstar** [comment]
Not sure if this is normal behavior, it just looks weird to me.

**Comment by BlauFeuer** [comment]
If you use `@py` to simulate how it will be in code, you will literally be storing new lines in a string,

That's how they'll be displayed.   `@py self.db.prompt = '\n> \n\n'` then `ex me/prompt` will simulate having done the same in code, and display as newlines. In code, you'd probably want to do `@py self.db.prompt = '|/> |/|/'` instead of literally storing new lines. New lines are not interpreted into markup, but markup will be interpreted into new lines when output by the msg method.

**Comment by texdarkstar** [comment]
Slightly off topic, what is markup?
Is it in the docs somewhere?

**Comment by BlauFeuer** [comment]
In-game, try `@color ansi` for a brief markup reference.

In the wiki, see https://github.com/evennia/evennia/wiki/TextTags and
https://github.com/evennia/evennia/wiki/Understanding-Color-Tags

**Comment by texdarkstar** [comment]
Ahh. Thanks!
