### ISSUE TITLE
Feature Request: evennia pdf manual

### ISSUE THREAD

**Issue by texdarkstar** [evennia/evennia#1328]
Would it be possible for you guys to make the evennia wiki into a downloadable pdf, so it could be read offline or on a e-reader, etc?

**Comment by jprinc16** [comment]
[EvenniaWiki.pdf](https://github.com/evennia/evennia/files/1034284/EvenniaWiki.pdf)

Enjoy.

**Comment by texdarkstar** [comment]
Nice! It still needs to be connected to the internet to use the links though. Still, very cool.

**Comment by Griatch** [comment]
Nice @Jace84, looking good! I should probably point out to @texdarkstar though that Evennia *does* have a PDF manual built from the wiki. You can find it [here to read online](http://evennia.readthedocs.io/en/latest/) and (here in PDF form)[https://media.readthedocs.org/pdf/evennia/latest/evennia.pdf]. It's also available as epub and html formats. Our version does not include some of the graphics Jace's version has though, so that's a nice complement. :) 
At any rate, I think we can close this.

**Comment by texdarkstar** [comment]
I did not know that @Griatch, thanks for pointing that out.

**Comment by benabhi** [comment]
The pdf is still version 0.6 where i can find the actual 0.7 docs in pdf? 
I see some changes like HIERARCHY ^^

Sry for my english.

**Comment by benabhi** [comment]
Sorry for the double post but I do not know if closed issues are seen by administrators I really need the pdf of the latest version of evennia especially for the convenience of reading them offline. On the other hand I do not know how many changes were made since version 0.6.

Again I apologize and I am still waiting for a more recent compilation of the documentation in readthedocs.

Keep up the great work that you are doing. By far the best mud engine that exists: D

**Comment by Griatch** [comment]
@benabhi The update and building of the readthedocs version is not automated, unfortunately. The one that's up should be the 0.7 version but sometimes I've found the version is not updated as I expect on RtD. But I'll double-check!

**Comment by Griatch** [comment]
@benabhi There, I built the latest docs now. The old one was actually 0.7, but I had forgotten to change the version in the sphinx config file, sorry. This one is up-to-date with latest master though, for sure.

**Comment by benabhi** [comment]
@Griatch Thanks!!  seems to work fine now :D
