### ISSUE TITLE
Add support for Telnet Go-Ahead

### ISSUE THREAD

**Issue by vadi2** [evennia/evennia#1330]
#### Brief summary of issue / Description of requested feature:
Telnet Go-Ahead, or GA, decimal code 249, can be put on the end of the data output - this helps the receiving client know it received all data in case data was split across multiple network packets. Such splitting is a pretty scenario when games utilise out-of-band protocols to transmit a lot of data (say when a player enters a room, GMCP could be used to transmit all items and players in it).

It would be pretty nice if Evennia supported this to make the clients job easier.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use Mudlet to connect, observe <no GA> bottom right:
![selection_124](https://cloud.githubusercontent.com/assets/110988/26561082/b67e706c-44bb-11e7-8f28-237587a3fd77.png)
2. When GA is available, observe automatic network ping:
![selection_125](https://cloud.githubusercontent.com/assets/110988/26561085/c063872a-44bb-11e7-86df-56bfd4bf99d9.png)

**Comment by Griatch** [comment]
When using the `msg(prompt='mytext') message for sending a custom prompt, a IAC + GA is automatically appended - this is the common way clients like Tintin++ use to identify a prompt and place it in a fixed location in the interface. 

Could you elaborate on the conditions under which condition you like IAC + GA to be passed? For GMCP/MSDP?

I have some issues comparing my output to yours since on my screen (hi-res laptop screen using Linux mint with Cinnamon desktop), the status line in the bottom right is very crammed and I've not found a way in the settings to resize it: 

![image](https://cloud.githubusercontent.com/assets/294267/26760290/f6771770-4914-11e7-98f8-70a9fe408546.png)

**Comment by vadi2** [comment]
That looks like correct - I was going off Arx not sending a IAC + GA, perhaps it's limited to that deployment only?

HiDPI is something we're working on in https://github.com/Mudlet/Mudlet/issues/800.

**Comment by Griatch** [comment]
@vadi2 No, that is actually by adding IAC + GA for GMCP, sorry. Adding it to GMCP/MSDP messages is something we could do easily, not sure if it would affect any other client with such support though.

**Comment by vadi2** [comment]
I'm not sure what's the relationship here to an out of band protocol - even without any enabled, it something that could be sent. Am I misunderstanding you?

I understand your concern about it affecting anything - we have the same issue whenever we change on the other side of the fence. It's never a pleasant experience to be doing any low-level telnet changes.

That said, all the major clients I know of - mudlet, zmud, cmud, mushclient, and the basic telnet will not have an issue with this very basic telnet option, that comes from having played MUDs for over a decade on a game that supprots it. At minimum it could be enabled for mudlet only - it won't have issues for certain.

**Comment by Griatch** [comment]
@vadi2 Well, we have people using clients, both legacy ones and on mobile, that can't report line breaks properly, so something like GA is not at all guaranteed to work over the board. But that said, it's a simple thing to add for us with potential good use by clients. So it's now added, thanks for the prompt discussion!
