### ISSUE TITLE
The fix for #310 stops escaping HTML in the webclient

### ISSUE THREAD

**Issue by j-f1** [evennia/evennia#1369]
#### Brief summary of the issue:
The fix for #310 stopped Evennia from modifying the content of the output of the `@py` command. This causes HTML to be passed through without escaping

#### Steps to reproduce the issue:

Run `@py '<script>alert("xss!!1")</script><h1>This is an H1</h1>'`

#### Expected output:
```
>>> '<script>alert("xss!!1")</script><h1>This is an H1</h1>'
<script>alert("xss!!1")</script><h1>This is an H1</h1>
```

#### Actual output:
<pre><code>
>>> '<h1>This is an H1</h1>'
<h1>This is an H1</h1>
</pre></code>

as well as two `alert()` boxes saying “xss!!1”

#### More info:

This also causes a problem when printing out objects, because the default return value of `__str__` looks like this:

```
<object object at 0x1002cd090>
```

This renders a literal `<object>` element into the webclient.

**Comment by Griatch** [comment]
Confirmed on `devel` too. This is not intended behavior; even though `@py` is a privileged command the output in the client should not depend on which protocol you send it to. That is, text output to the (default) web client should behave and look similarly to its telnet/ssh counterparts.

**Comment by chainsol** [comment]
I can put a PR through today to fix, if you wish, I think. I have a branch that should fix it.

**Comment by BlauFeuer** [comment]
I thought this _was_ expected behavior, since escaping is done in the msg method, so "output in the client should not depend on which protocol you send it to." only via msg method.  When sending otherwise, the output should be literal and subject to client interpretation.

If not, then how does one send literal output for testing?  By reversing the behavior, meaning all output acts as if it went through msg method, unless explicitly going through message method with a raw kwarg?

**Comment by Griatch** [comment]
@BlauFeuer Clearly custom outputfuncs shold be able to output whatever the developer wants to pass to the client. To homogenize output of the `text` outputfunc however, HTML should be escaped when passed through the `text` outputfunc of the webclient. This is not something to change at the  `msg` level but rather at the protocol level.

**Comment by chainsol** [comment]
@Griatch Isn't the problem here that "raw" is meant to not deal with the client at all? The non-raw msg function already handles the protocol side - if one adds a flag to the @py command that defaults it to not using msg's raw argument, this problem is gone.

**Comment by BlauFeuer** [comment]
@Griatch  You misunderstand - nothing needs to be changed at msg level, but rather `@py '<script>alert("xss!!1")</script><h1>This is an H1</h1>'` should be @py self.msg('<script>alert("xss!!1")</script><h1>This is an H1</h1>')` for the expected behavior.  e.g. msg method does the job, but output otherwise is sent independent of client or protocol, as the users of `@py` should understand how output works, and be allowed to send literal messages out.

At least consider a `@py/raw` to bypass this feature request, if you're going to now send all output through any kind of processing. Unless I'm sending a message to the client, I don't expect any client or protocol specific processing.

**Comment by chainsol** [comment]
@BlauFeuer I think that was one of the suggestions, add a /raw flag to the @py command, so you could keep that behavior if you wanted it. It's what the branch I have does - just added a raw flag to the @py command.

**Comment by Griatch** [comment]
Hm, I would be up for a `@py/raw` option if that is desired.

**Comment by Griatch** [comment]
@BlauFeuer But I see your point concering `@py` and expected behavior. I'll need to ponder that a bit.

**Comment by chainsol** [comment]
@Griatch @BlauFeuer Let me know - and maybe we can see what others think about it. I know @vlegoff has also expressed interest in an @py/raw flag - the current behavior can be quite annoying when attempting to, for instance, look at a list of objects.

**Comment by BlauFeuer** [comment]
I agree that the current default behavior can be confusing in specific circumstances when it's not expected. The end goal should probably be to display it in a manner that offers "the least amount of surprise".

I'm not at all against changing it and adding display options. For debugging (for instance, look at a list of objects via `repr()`), I'm now in the habit of using `print()` and viewing the console directly in the same way I was in the habit of using `self.msg()` to avoid the current behavior's quirks.

The `@py` command options could just provide a predictable encapsulation and display behaviors, with the default being the most common expected behavior, whatever offers the least amount of surprise.

**Comment by chainsol** [comment]
I remember why I didn't PR this - that "fix" should probably reintroduce the old behavior #310 talks about. I'll double check that, but I think that's one more facet to the problem.

**Comment by Griatch** [comment]
Discussing this back and forth, this appears to be the best solution:

1. Have `@py` keep returning `raw=True` output, same as now.
2. Make a new escape mechanism in `text2html` that escapes existing html code going out. This makes the escape unique to the web client on the protocol level.
3. Provide a new `/raw` switch in `@py` to also turn *that* escaping off, for those that want to see html parsing in the webclient etc.

**Comment by Griatch** [comment]
This is implemented in develop branch.
