### ISSUE TITLE
Feature Request: More security-related info sent to console/logged by the network portal

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1383]
#### Brief summary of issue / Description of requested feature:
As mentioned in #1375 , failed login attempts and temporary account lock-outs are not sent to console or logged, nor are connections that never reach the login authentication point.

#### Reasons for adding feature:
Security in the form of malicious activity detection/documentation, and getting a better idea of who/how many connections never result in any login attempt, failed or otherwise.

#### Error output / Expected result of feature
Similar to the entry for a successful login:
`2417-04-30T06:33:20+0000 [AMPProtocol,0,127.0.0.1] [..] Logged in: Golem(player 17) 8.282.39.12 (1 session(s) total)`
Perhaps something like:
`2417-04-30T06:33:20+0000 [AMPProtocol,0,127.0.0.1] [..] Failed to log in: Golem(player 17) 8.282.39.12 (1 session(s) total)`
and
`2417-04-30T06:33:20+0000 [AMPProtocol,0,127.0.0.1] [..] Connection established with 8.282.39.12 (1 session(s) from that address total)`

Finally, something similar for a temporary account lockout on multiple login failures:
`2417-04-30T06:33:20+0000 [AMPProtocol,0,127.0.0.1] [..] Locked out: Golem(player 17) 8.282.39.12 (5 failed login attempts total in last 2 minutes)`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

master/devel branch as appropriate, though this doesn't seem like a major change.

**Comment by Griatch** [comment]
This sounds like a good idea .

**Comment by strikaco** [comment]
This is definitely sorely needed. It would be great if we could capture the time, IP address and player object (whether accessed or denied), and effective character (where applicable) as CSV for things like:

* Login events
* Login timeouts
* Login failure
* Logout events
* Lockout events (too many failed password attempts)
* Ban/unban events
* Puppet events + target character name and dbref
* (optional, but useful for exploit detection and object auditing) All raw commands submitted by the players

This would make it easy to write a dashboard command (`@audit`) that allows wizard-class users to review and filter security events related to a player name, IP address, character, or even object (though aliases might skew this). Questions such as:

* "Who was puppeting this character on this date?"
* "Show me the unique IP addresses that have accessed this player account."
* "Show me all player accounts that this IP address is associated with."
* "Show me all the characters this player has ever puppeted, and when."
* "Show me all players who have puppeted this character."
* "I thought I banned this moron. Who the hell unbanned him, and when?"
* "Who stole my car, who has ever come into possession of it and who has it now?"

...could all be answered with a blind `grep` and some filtering or done completely in Python using iteration (slow, but assures cross-compatibility). This completely decouples security metrics from the core functionality-- no cycles are wasted serializing and deserializing lists and hitting DB to update attributes; resources are only consumed when the data is needed and the logs themselves could even be forwarded via filebeat/logstash for more advanced auditing pipelines and use cases.

I can handle writing such a command to handle the analytics but I don't understand the codebase well enough to enhance the logging beyond its current implementation.

**Comment by whitenoiseoss** [comment]
This is a feature that should be present, but I would add some additional thoughts:

- Last good login address, last bad login address, number of unsuccessful attempts since last login, timestamp of last unsuccessful login, and timestamp of last successful login should all be database fields to monitor the "current" state. If this is cause for alarm, automated or otherwise, logs should be consulted for a historical account.
- The logs being in CSV is a poor choice. Logs like this should be in a syslog format so they are easily scannable by humans. Syslog is also a very standard format for such information, so there are plenty of libraries in Python and third-party services for parsing things from a Syslog format for automated analysis. These logs could be managed automatically with log rotation.
- Not using a database for historical accounts is for the following reason: Without code to automatically prune said database, this database after running through tests and over years would eventually need to be pruned and this is an administrative overhead that most users of Evennia are not prepared for. It is a reality of production software and services, but that should not be carried over into Evennia due to the difference in community.

As in most things with Evennia, within reason, features should be designed around the lowest level of technical understanding that we could put them at while still being useful. If more advanced users want more advanced behavior, that should be up to them to introduce. For example, with a syslog-formatted log file of security events, one could create a dashboard with Kibana and Logstash and even have automated alerts.

**Comment by Griatch** [comment]
Since there appears to be some contention about it, I'm reiterating (like Blau does in the first sentence) a cross-reference to @tekmunkey's feature request #1375 which first brought up the missing IP logging. That one (the original post, the way I interpreted it) suggested storing said IP data on the Player (and possibly on the Character too), whereas this feature requests is similar except suggests using a log file rather than an in-database store.

**Comment by strikaco** [comment]
> The logs being in CSV is a poor choice. Logs like this should be in a syslog format so they are easily scannable by humans. 

Fair enough. I suggested csv for the sake of minimizing verbosity (only really need the 4 data points), but it wouldn't do anybody who looked at the log any good to just see a big list of nondescript...stuff.

**Comment by robotfactory** [comment]
Has there been any progress on this feature since PR #1390? Just trying to triage an old issue or two.

**Comment by Griatch** [comment]
No, #1390 is closed but is instead handled by #1535 which has, unfortunately gone stale with no updates after the first round of PR feedback.

**Comment by strikaco** [comment]
I believe the logging aspect of this is complete? If I missed anything, let me know and I'll add it.

**Comment by Griatch** [comment]
I think this is implemented. We are still missing a per-account IP store as suggested in #1375.
