### ISSUE TITLE
Tests failed for in-game python contrib

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1388]
#### Brief summary of issue / Description of requested feature:
I'm finally trying to start writing unit tests for some of my own code, and was trying to get the test runner working right for my own settings file. It threw syntax errors on the unit tests for the in-game python contrib with an error I'm really unfamiliar with:

```
======================================================================
ERROR: test_accept (evennia.contrib.ingame_python.tests.TestCmdCallback)
Accept an callback.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\arx\evennia\evennia\contrib\ingame_python\tests.py", line 252, in setUp
    "evennia.contrib.ingame_python.scripts.EventHandler")
  File "c:\arx\evennia\evennia\utils\create.py", line 178, in create_script
    typeclass = class_from_module(typeclass, settings.TYPECLASS_PATHS)
  File "c:\arx\evennia\evennia\utils\utils.py", line 1357, in class_from_module
    mod = import_module(testpath, package="evennia")
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
SyntaxError: unqualified exec is not allowed in function 'call' it contains a nested function with free variables (scripts.py, line 448)
```

The above error repeated for each unit test.

Looking at this [stackoverflow post](https://stackoverflow.com/questions/9195309/any-explanation-of-execs-behavior), it seems that it's a python 2.x problem - in 3.x, exec() is a function, which is how it was used there, but previously it needs to be qualified with the 'in' syntax if there's generators used in the function it's called.

#### Steps to reproduce the issue / Reasons for adding feature:

1. I ran `evennia test --settings settings.py evennia`
2. Saw above error

#### Error output / Expected result of feature
Above traceback for each unit test.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Some sort of compatibility fix so it runs in both python 2.7 and 3.x? I'm not sure what a good solution is there.

**Comment by Griatch** [comment]
I have asked @v-legoff and he'll take a peek since he's the author of the contrib.

**Comment by vlegoff** [comment]
It's a surprising error.  From what I get, I assume you didn't change anything in the contrib code (particularly in the `evennia/contrib/ingame_python/scripts.py` file).  The `SyntaxError` happens when dynamically loading this module with `class_from_module`.  It definitely doesn't raise `SyntaxError` in my tests, with a fresh install.  Could you test with a fresh install (and perhaps make sure this file hasn't been modified)?  I have no idea what else it could be, but I'll check to make sure.

**Comment by TehomCD** [comment]
I did a fresh install and got the error again when running `evennia test evennia` immediately after finishing installation/migration steps. Maybe it's specific to my environment, for some reason?  The test machine I'm seeing the error on is running Windows 7.

**Comment by Griatch** [comment]
@TehomCD I also cannot replicate your issue on master, but I wonder if you might have some remnants of the devel branch in your system, since I did see something like this in the IGP on the devel branch, and fixed it some time ago.

**Comment by Griatch** [comment]
I don't see any issues like this on the `devel` branch but I don't know which custom settings to test. @TehomCD, do you still see this with `devel`? If you do, it would be interesting to see which of your custom settings trigger it ... 
> Note: this is *not* a duplicate of #1396 since this issue explicitly uses the game dir's settings and can be expected to not necessarily pass tests. But the reported issue with the IGPS is weird and would be good to figure out.

**Comment by TehomCD** [comment]
Unfortunately, after upgrading my fresh install from earlier to `devel` branch, I still see the same error (except the SyntaxError from scripts.py is now on line 457 rather than 448).

**Comment by vlegoff** [comment]
@TehomCD I may have the beginning of an answer.  Which Python version and environment do you use?  This would work on cPython (Python 2.7.13).  The error you gets seems to indicate `exec` with local variables isn't allowed, which sounds a little like a different version of Python, perhaps more secure.  You could probably use `exec` with only one argument: `exec("print(2 + 3)")`.  However, if you specify a second and third arguments (with the dictionary of global/local variables), your Python environment might not appreciate it.  Unfortunately the IGSP has to provide variables to the callback you call in order to provide the user with variables she can use.  If this is a bug due to PyPy or another Python environment I'm not familiar with, I would be happy to fix it, if it can be fixed.

**Comment by vlegoff** [comment]
I found the issue (kind of).  It's not due to the Python machine.  Rather, the syntax used to `exec` is obviously not supported on your Python version.  This is a Python-3 syntax, which explains why i went for it.  It is supported on 2.7 though (or at least, the last sub-versions of 2.7).  I am testing the older syntax right now, which is far less readable to me, but it's just a line to change.  If it works I will open a PR against devel, not knowing if it solves the issue for you however.

**Comment by TehomCD** [comment]
2.7.8 is the python version I had installed, so if the syntax was only supported on 2.7.13, that probably was what did it.

**Comment by Griatch** [comment]
This was interesting, and worth keeping in mind! Closing.
