### ISSUE TITLE
Bug: Issues with ANSIString

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1392]
#### Brief summary of issue

This was originally brought up by @tekmunkey [here](https://github.com/evennia/evennia/pull/1386). The `ANSIString.center` is failing. 

    Using @py, 3 arguments gets:

    >>> from evennia.utils.ansi import ANSIString; teststr = ANSIString("|h|rMy testing string|n");self.msg(teststr.center(78,"-",2))
    TypeError: wrapped() takes at most 3 arguments (4 given)

    Using @py, 2 arguments gets:

    >>> from evennia.utils.ansi import ANSIString; teststr = ANSIString("|h|rMy testing string|n");self.msg(teststr.center(78,"-"))
    Done (use self.msg() if you want to catch output)

#### Error output / Expected result of feature

See above.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

It is possible that The latter issue may be an error with the outputhandler and a direct ANSIString - it may not identify as a "string" and thus mix up the outputfunc which in the case of a non-string should have the look `(name, (args), {kwargs})` (where the various parts are optional).

**Comment by Kelketek** [comment]
@tekmunkey @Griatch 

The exception being thrown is a documentation issue. The code is working as expected-- the `difference` argument is dynamically generated by the function decorator `_spacing_preflight` to account for the offset of ANSI codes added to the string. ANSIString is supposed to be used identically to unicode save for one particularly notable exception (there may be others, perhaps something with regex, but I'm unaware of them):

The use of string.join on an ANSIString results in bogus output, due to string.join being implemented in Python C code and only checking if the target object is of unicode type before proceeding. Since ANSIString is a subclass of unicode, it gets handled at the raw level and its internal tables are dropped. You have to use ANSIString.join, or first convert the ANSIString to a string. I should have documented this and did not. So let's not consider this issue closed until I've made the necessary documentation adjustments.

I suspect the issue with .msg() not sending the right data may actually be due to this quirk of its behavior. I'm looking into it now.
