### ISSUE TITLE
Feature Request: Have `|-` parse as fix-width instead of tab-stop

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1393]
#### Brief summary of issue / Description of requested feature:

This was originally reported by Tekmunkey [here](https://github.com/evennia/evennia/pull/1386):

> |- doesn't parse usefully, coming out as a tabstop which is counted as 1 character which in the end a client terminal may parse into 4, 6, 8, or wtf-ever number of characters. Whether you're centering or wrapping that text, it's going to come out WRONG on the client terminal. For that reason alone, it needed replacement with something that parses tabstops into a uniform number of absolute spaces, so when you present wrapped or centered or justified text you know it's going to stay that way.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This is a trivial change, but makes sense for those wanting to use the tab symbol for formatting.

**Comment by Kelketek** [comment]
@Griatch @tekmunkey 

While I can't imagine there would be many instances where one would actually want a tab, if we're going to recognize a tab ANSI character, we should probably treat it as one. To do otherwise would break expectation.

I'm a little confused on why one can't just use four spaces if that's what they desire. The special feature of doing ANSI is that you can expect the right terminal codes to be sent. But you have access to the space bar on your keyboard, and it's easy to send in most clients. Tab is not easy to send in most clients, hence the need for a shortcut.

**Comment by BlauFeuer** [comment]
I actually use `|-` to literally send a tab character from in-game, I don't mind the change of what `|-` sends, but then how does one send an actual tab-stop?

Maybe move tab to `|>` or `|/` instead, or add a new mapping for tab-stop.  The question then is, for the use case described, how does one symbolically set the tab stops for the line, or will this just be a hard space times "4, 6, 8, or wtf-ever number of characters. "

**Comment by DamnedScholar** [comment]
`|t` is currently not used (according to [this page](https://github.com/evennia/evennia/wiki/TextTags)) and would be the most logical mark for a tab character, given that other platforms people come from use tags like `\t` and `%t`.

I will say that a lot of people in the MUSH community are going to be used to declaring spaces with those tab characters, and when that happens, the spacing is always the same. I understand why it's not necessary to have a fixed-width spacer tag in Python, but I believe that having a tag that does that would provide a lot of marginal utility to people who are comfortable writing descs with that available. Either `|-` or `|t` could be a fixed-width spacer, but I think that `|-` makes more sense since `|t` would be best to refer to the *actual* tab.

**Comment by Kelketek** [comment]
@DamnedScholar If it's a common thing people expect coming from MUSHland, I'm not opposed to that. But yes, it should be a marker different from Tab, if so.

**Comment by tekmunkey** [comment]
Whether you use `|-` or `|t` is totally irrelevant.  The problem is that a tabstop is a tabstop.  It's 0x09 in ASCII code, which is `len($strVar)`=>1 in every programming language ever.  The problem is that there are umpteen and a half telnet clients out there and they all interpret 0x09 differently.  In one 0x09 is 4 spaces, in another it's 6 spaces, in another it's 8, in another it's actually user-configurable.

In all cases, when you attempt to textwrap or left or right justify text containing user input where the user included a tab replacement because they weren't aware of this fact, the justification is all wrong on every terminal that isn't either the exact same client as theirs or else the exact same client as theirs and also the exact same user configuration as theirs.

**Comment by BlauFeuer** [comment]
@tekmunkey  **Don't use tabs if you wanted X number of spaces**.  A tab will move the cursor to the next tab stop defined on that terminal or client, so yes, you can't use tabs to do text justification.

So now you're asking for something that is server-side predictable for this use, but haven't really specified how it should behave. You're "wanting to use the tab symbol for formatting."  There's already a text justification utility, and other formatting functions though.

For this to be implemented, one needs to define what "fix-width" is, which means either defining your new code as X number of spaces, or having some mechanism to define tab stops on a line and jump ahead to them on this new code.

**Comment by DamnedScholar** [comment]
> Don't use tabs if you wanted X number of spaces.

This is true generally, but it has *long* been a feature of MUSHes that tabs do precisely that. It seems clear to me that the people doing formatting on Deep Shadows were expecting that behavior, and others will likely desire it as well.

> one needs to define what "fix-width" is

We just need to make an arbitrary decision: 4, 5, 6, or 8. I like 4, because the longer the spacer is, the fewer situations it will be useful for.

**Comment by BlauFeuer** [comment]
At this point it's sounding like a game-specific change -- one that can be mapped in settings.py such that a certain code becomes translated to a certain number of spaces.

But as a feature request, we're considering what to define it for every Evennia game out of the box,

**Comment by Griatch** [comment]
I think it sounds like a good idea to simply have one version (say `|-`) which is always, say 4 spaces (like Python standard), and another (say `|t` or `|>`) which is the actual tab character with all its possible problems for those that really needs to send the TAB for some reason.

**Comment by Kelketek** [comment]
@BlauFeuer I don't think it's necessarily game specific. If MUSHes do this standard, and one of our biggest audiences is people from MUSHland trying to find something new to work with, we should have a comparable feature for that if it's not going to cause problems to implement. I concur with @Griatch and @DamnedScholar on it being four spaces and having tab retained as a separate code.

**Comment by BlauFeuer** [comment]
@Kelketek if mu-X does something, that's a specific to mu-X. If you want a game like mu-X, then you can add changes within the framework to be more like mu-X, but the logic of making Evennia more like mu-X for every possible value of X when these changes restrict the framework isn't a good idea.

Adding things to be more like mu-X is different entirely, and I'm not against that.

`|t` for tab seems good.  `|-` seems good for 4 spaces.  The more advanced implementation for this feature might be for `|>` to space fill to the next defined tab stop, where tab stops are a list of column positions defined server-side, not client side, which is almost always different with every client, like tekmunkey said.

**Comment by DamnedScholar** [comment]
> the logic of making Evennia more like mu-X for every possible value of X when these changes restrict the framework isn't a good idea.

I think we all agree on that.

> The more advanced implementation for this feature might be for |> to space fill to the next defined tab stop

That sounds cool.

**Comment by chainsol** [comment]
Just to chime in here, I'd say that I agree on the usage of |- for 4 spaces, and |t for an actual tab.

**Comment by Griatch** [comment]
@BlauFeuer I think in this case, the use of a "fixed-tab" is a potentially useful formatting tool regardless of which MU-style it originates from. A space-fill is an interesting idea too, as an alternative to the variability of the tab character. But I would imagine that for most uses, multiple "fixed" tabs would be more than enough for most formatting needs. Heck, I honestly never used the tab in normal text myself...

**Comment by BlauFeuer** [comment]
My argument wasn't against "fixed-tab" or for Evennia being more like MUSH, it was to try to define what "fixed-tab" means, which could be game-specific, and could be mapped in settings.py as-is.

Yes, the tab character is of limited use as a formatting character, but my argument was against wholesale replacement or removal of it as-is, but again, if needed, it could be mapped back in with settings.py.

I just think we shouldn't think so small, adding features that can already be done game-side when the real value added is making the framework more powerful so people can do custom things without needing a feature request to change Evennia server code.

For this feature, specifically, it would be more powerful as a formatting tool if there was a tab stop column list and outgoing text space filled on a `|>` to the next tab stop, like the original intention of the tab character.  But if you just wanted an indent, `|-` works for `|_|_|_|_`

**Comment by Griatch** [comment]
@BlauFeuer I think the (technical) problem with using `|>` as a settable tab like you propose is that it adds another type of ansi tag - one that is aware of its position on the line. The idea is not bad but this is not something the current tags support (they have no concept at all of line widths or formatting at all, they just replace individual characters). As such I think it might be better to split something like that into a separate feature request rather than the simple split of 4-spaces and tabs into two tags covered here.

**Comment by Griatch** [comment]
I added the simple fix of changing `|-` to 4-space indent and added `|t` for the TAB character, so closing this. A more elaborate further expansion with a different type of tab structure would be better served by a separate Feature request. :)

**Comment by tekmunkey** [comment]
@BlauFeuer could you possibly troll any more blatantly?  I muted the thread so you @tekmunkey me.  We're talking about inserting tabs into text so you talk about hitting the tab key.  Derpa derpa derrr.  Derail conversations much?  Can I possibly post anything anywhere without you starting a flamewar of raw stupidity?  

You don't even know what you're babbling about.  MUSH has the exact same problem Evennia did when I wrote the code that fixed it.  It reads %t as a single character and that screws up the wrap() function.  Jesus.
