### ISSUE TITLE
Tutorial World build fails under Evennia 0.7

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1450]
#### Brief summary of issue / Description of requested feature:
\@batchcommand seems to fail under Evennia 0.7

#### Steps to reproduce the issue / Reasons for adding feature:

1. Start a new instance of Evennia 0.7
2. Follow the directions to create the tutorial_world
3. Tutorial world doesn't get created correctly - missing areas, descriptions, etc

#### Error output / Expected result of feature
Instead of creating the world and describing everything, we get errors about not being able to find a command. It seems to ignore the @setdesc command, and the current batchcommand Evennia provides still uses @desc, so it fails anyway.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Any version of 0.7 seems to have this issue.

**Comment by Griatch** [comment]
@chainsol Actually the build-level `@setdesc` was really intended to (still) be called `@desc` while only the character-level `desc` was renamed to `setdesc`. This is done due to the new prefix-ignore feature - the idea is that at no place in the default commands should only an `@` separate two very different command names I fixed that now, correctly setting the key of `@setdesc` to `@decs` (even the in-func doc had the right help string so it was just the `key` and header that hadn't been updated. So the tutorial descriptions work now. I didn't see any failure of areas themselves getting built though, did I miss something there? Waiting to close this until you can reply.

**Comment by chainsol** [comment]
The tutorial world works great now! Thanks for clarifying and renaming this issue - I'm going to close it now that it's fixed.

However, Ainneve's batchcommands seem to break the parser somehow - it skips commands entirely. Perhaps it's formatted wrong, or something of that nature - but I'm going to open an issue against Ainneve's repo instead.
