### ISSUE TITLE
Feature Request: Allow players to delete an account

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1533]
#### Brief summary of issue / Description of requested feature:
There's currently no way for a player to delete their own account. For instance, there was a bug on the Evennia demo server, and I have an account without a character - not so nice that I can't delete the account.

#### Steps to reproduce the issue / Reasons for adding feature:
In addition to fixing situations like mine, someone who might not want their account anymore could free up their username.

#### Error output / Expected result of feature
Allow players to delete their own account, perhaps with a confirmation.

**Comment by strikaco** [comment]
Does this only apply to childless accounts? 

If not, I would be wary of delegating an administrative task with permanence to a minimally-authenticated user. Without 2FA you're giving delete privileges to a potentially fraudulent user, the victim of whom is at the mercy of your backup policy. It's safer to just set is_active to false and call it a day (much easier to undo if needed).

**Comment by chainsol** [comment]
I suppose that's true, perhaps allowing an email confirmation? We don't require emails on user sign up though.

**Comment by Griatch** [comment]
As mentioned, this is not a good idea to allow a regular player to do. Another issue, beyond malevolent deletion is that stuff like ban/IP info and other future security info we may deem useful to store about an account is also stored on the account level. So deleting this (which would then allow you to create it again since there is then no collision) would be a neat way to wipe the slate clean.

An erroneous account is something worthty of contacting admins - who are *also* recommended to not ever actually delete an account if they can avoid it. So I don't think this is a feature we want. Closing.
