### ISSUE TITLE
Feature Request: Allow MAX_NR_CHARACTERS to be set in MULITSESSION_MODE 0 and 1

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1547]
#### Brief summary of issue / Description of requested feature:
It would be nice if we could set the max number of characters under MM 0 and 1.

#### Steps to reproduce the issue / Reasons for adding feature:
This seems to be a common request, and currently we force `MAX_NR_CHARACTERS` to 1 under both MM 0 and 1.

#### Error output / Expected result of feature
Allow multiple characters, but one session at a time.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This shouldn't be too hard - I guess make the character select show up if one has set `MAX_NR_CHARACTERS` greater than 1?

**Comment by BlauFeuer** [comment]
Yes, it's possible to _have_ more than one character per account in this mode, but can't use them concurrently, and currently can't use the character creation command to make them.

Character select could show if `len(_playable_characters)` > 1, while `MAX_NR_CHARACTERS` should probably just be for limiting creating more.

**Comment by chainsol** [comment]
Right, but right now we force `MAX_NR_CHARACTERS` to be 1 no matter what, right? (assuming one is in MM 0 or 1)

**Comment by BlauFeuer** [comment]
I'm up for this feature, but don't users expect to just puppet their `_last_puppet` character on login by default?

Another setting?

**Comment by TehomCD** [comment]
Related to that, we may want to change some of the attributes like `_last_puppet` into properties/methods (get_default_puppet()?) that return the currently used attributes as their default. That'll allow for easier overriding of the behavior if games want to have custom logic that should alter what they return, such as returning a 'main' character they've defined by some other attribute instead of just the last one played or whatever.

**Comment by chainsol** [comment]
@BlauFeuer I would say that would be expected - however isn't the default behaviour under higher `MULTISESSION_MODE`s to show the character select screen? I do like auto-puppeting, but it could be a per-game or per-account setting, not necessarily something core Evennia has to do.

**Comment by BlauFeuer** [comment]
Yes @chainsol , it should be a per-game or per-account thing and if the framework allows it, I'd set up an account setting for the users to decide.

But due to the previous default behavior, I know it would just confuse some people to suddenly be given a menu, because they're used to landing inside their character on login, then using `@ic <other character>` to switch, because we're manually making multiple characters for those who request it, despite the lower MULTISESSION_MODE.

That is to say that I like the current default behavior regarding character login menu, but if it was mandated by settings or easily modified, then when it changes, I'll know what to do.  Otherwise I completely agree with you on defaulting, but not restricting `MAX_NR_CHARACTERS` to 1 in any mode.

**Comment by Griatch** [comment]
Implemented in Evennia 0.8.
