### ISSUE TITLE
MAX_COMMAND_RATE didn't appear to work

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1556]
#### Brief summary of issue / Description of requested feature:
So a player purely by accident sent a huge, huge number of commands into his input window, and locked up our server for a good few minutes. We have checks on sending massive amounts of text in a single command, but it hadn't occurred to me when they're all valid input strings. MAX_COMMAND_RATE was set to the default of 80, but it didn't appear to provide any protection against this, and I have no idea why.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Apparently he meant to log a long session and accidentally copied all of his command strings, and re-sent them.

#### Error output / Expected result of feature
Server lock for a pretty long time. Things catching on fire. Wailing, gnashing of teeth. A few stray cats probably died.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
No idea why MAX_COMMAND_RATE didn't protect against this.

**Comment by Griatch** [comment]
`MAX_COMMAND_RATE` has been tested with the dummyrunner trying its best to flood the server. But maybe there is some issue in protecting against sending one long line-break separated string, that'd be the a possible thing to look into here.

**Comment by TehomCD** [comment]
The player followed up with me, and said that he was getting feedback from the server of the error message from COMMAND_RATE_WARNING, so that part was working at least. So I'm not sure if the lockup was the portal just freezing up as it dutifully went through relaying all those messages, or what.

**Comment by TehomCD** [comment]
The player said it was an entire night's input log, so they were guessing somewhere in the range of 4000 commands as their ballpark. So maybe it was just purely traffic - is there any way for Evennia to really handle that, or would that require things like load balancers and such?

**Comment by Griatch** [comment]
4000 commands doesn't sound like very much in bytes ... Evennia should handle that fine in pure network performance. So worth looking into. But if it was a pure DDOS thing then no you'll never be able to handle that really - you'll always have a CPU limit  since you'll have to perform operations on the incoming data, even if it is to turn it away. That's something you'd need to handle by putting an external rate-limiter in front of the port. Load balancers wouldn't really work since that'd suggest you had multiple Evennia instances to spread the load across.

**Comment by Griatch** [comment]
@TehomCD I tested this in the following way (linux)

First I made a text file `cmds.txt` with 4000 commands, one per line:

```
connect myaccount mypass
look
look
..
quit
```

(the last `quit` is not actually run since the limiter swallows it, so that's not really needed). Next I ran

    cat cmds.txt | curl telnet://localhost:4000 

The result is a wall of `You entered commands too fast. Wait a moment and try again.` I don't even have time to switch over to the game to see if there is a slowdown before its over. 

I tried with 

    cat cmds.txt | curl telnet://localhost:4000  2>&1 | grep Limbo > output.txt 
    # (Ctrl-C after a while)
    wc -l output.txt
        140 output.txt

So 140 `look` commands were actually being processed and returned. Not sure how this relates to a `MAX_CMD_RATE` of 80, I would have expected this value to be either 80 or 160. It's however clear that the limiter is working - Increasing the number of commands to 10 000 led me to count 146 commands go through, but at 20 000 we are down to 140 again - so it might be some timing issue there. 

Now, I'm just sending `look` commands. Maybe that user sent heavier fare. It would be interesting to know what they were since it would appear only 140 of them in sequence brought your server to a halt ...

**Comment by TehomCD** [comment]
Look and inventory generally seem like the fastest commands to execute because everything is fully cached, but maybe it was just him doing 80 (or 140? odd that it let you do more) much more demanding commands. If they were all commands that printed out a large EvTable, that might have done it - those can take a few seconds at a time. The way he described it, though, it should have mostly just been communication commands. So if just spamming raw commands doesn't seem to cause an issue, probably the sanest thing for me to do is just to lower the `MAX_COMMAND_RATE` to a much lower value, like 10 or lower.

I just tested a little bit myself with a `MAX_COMMAND_RATE` of 1 doing fairly server-intensive commands, like printing out a big EvTable, where it never seems to get the rate limit due to the commands taking several seconds to execute, even when I queue them in rapidly: just a lengthy pause and then spam of the output of several commands. Does that sound like the correct behavior? Maybe for a test try to make, say, 100 dummy channels with long-ish descriptions so they take up multiple lines or so and then change the command to `@channels` or some such.

**Comment by Griatch** [comment]
The risk with setting a lower `MAX_COMMAND_RATE` is that *everything* from the client passes through this filter. This includes OOB commands which could be problematic if you support that. 
Not sure offhand the behavior for 1/s rate limits, I suspect the limiter has to actually run for a second before it can reliably tell that you are sending too many commands - so during that second you *can* put in more commands than the rate limit. It's a tricky thing to do this check overall, since the alternative would be to try to do some sort of interpretation based on the time since the last command - which means that you could hit even a very high limit based on two very close-together commands even if those two were the only commands you sent that second.

**Comment by Griatch** [comment]
@TehomCD After some thought I have reworked the throttle managing the `MAX_COMMAND_RATE`. It should be more exact now since it doesn't have to wait a full second before starting limiting. This is how it works now: 

1. On startup we figure out `MIN_COMMAND_DISTANCE = 1 / MAX_COMMAND_RATE`. We also reset `command_count=0` and `last_reset_time=time.time()` on the session as it first connects.
2. Session sends command. We record the current time as `now`.
3. If `now - session.last_reset_time > ` then it's time to reset the `command_count` 0 and `last_reset_time` to `now`.
4. Increase counter.
5. If `command_count * MIN_COMMAND_DISTANCE > 1` it means we have no more 'room' for commands this second. We send the too-fast message. Otherwise we pass on as normal. 

As far as I can tell, this will always let through `<= MAX_COMMAND_RATE` commands no matter what.

**Comment by Griatch** [comment]
@TehomCD I will now mark this as closed. We can reopen if the issue re-emerges.
