### ISSUE TITLE
Feature Request: at_channel_msg_receive and at_channel_msg_send hooks

### ISSUE THREAD

**Issue by arumford** [evennia/evennia#1566]
#### Brief summary of issue / Description of requested feature:
Hooks on Object that tracks then the object receives from or sends to a channel versus a standard msg().  
Arguments would include the reference to the channel object that sent the message.

#### Steps to reproduce the issue / Reasons for adding feature:

1. In my particular case, I have extended Channel and have objects using them for communication.  Then I need to refer the message up to the user after some checking and processing. 

#### Error output / Expected result of feature
hook fires when a message is received from a channel and includes the reference to the channel object.

**Comment by Griatch** [comment]
@grungies1138 Actually, thinking about it, this is already supported, it's used by e.g. the bots, which use this to detect when a channel speaks to it as well as when sending. Basically, the DefaultChannel will put `"from_channel=<channel>"` in the `options` dict of the bot's `msg` method. The `from_obj` is the person speaking on the channel. 
Since the bot is connected to the outside word (such as listening to an external IRC channel), it uses the `execute_cmd` as input handler. You can see how it works here: https://github.com/evennia/evennia/blob/master/evennia/accounts/bots.py#L253

Closing.
