### ISSUE TITLE
[Suggestion] Add content ordering

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1567]
#### Brief summary of issue / Description of requested feature:

So far, objects have no way to remember their order in a given location.  If one move A and B in X, `X.contents` might display B and A instead of A and B.  I suggest here a solution to have objects remember the order in which they were moved in a location.

#### Steps to reproduce the issue / Reasons for adding feature:

1. The order might be important to keep, particularly in a room with many objects or a character inventory.
2. For games that have multiple level containers, having them stored in a random order might disconcert the player, particularly when using the `1-X` macro for searches.
3. It seems adding ordering won't alter anyone's current implementation, either because they use a different sorting systems, or because they will benefit from it.
4. Python 3.5 and up has implemented sorted dictionaries as default (meaning `dict` is sorted).  When Evennia will move to Python 3 with its heavy reliance on `dict` already, having the ordered maintained will bring interesting side-effects.

#### Error output / Expected result of feature

When we move A in X, then B in X, `X.contents` should remember A was moved before B.

#### Proposed implementation

I suggest a few steps here that might be implemented to achieve this behavior while maintaining performance:

1. Add a new field to ObjectDB, that could be named `moved_pos`.
2. Anytime the object's location is changed, the value of this field would take the maximum position (an integer).  This position will be then increased by 1.
3. Evennia will store its current maximum position in `ServerConf`.
4. When `obj.contents` is called, it should add an `ORDER BY` to sort by positioning.
5. A migration could be added to both add this field and place the position (including changing the stored maximum position in `ServerConf`).  Obviously, the original ordering wouldn't be accurate if data already exists.

#### Alternative implementations

- Having an integer kept globally that will increase every time might scare some developers, since only a basic operation (location change) would trigger an increase.  It is unlikely this number would reach a very high position (in the billionth unity).  We can compromise by having the timestamp stored, but notice that it might not be as efficient, particularly when we move several objects "at once".
- Another option would be to dismiss `ServerConf` altogether.  When an object is added to a location, it will get the maximum (`+ 1`) position.  This seems simple, actually, but it might also be less performance-friendly, I don't know.  We might be able to cache the maximum position in individual objects to avoid calculating each time.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

- Evennia master

**Comment by Griatch** [comment]
@v-legoff The `.contents` cache (in the `ContentsHandler`) is indeed a dict so the order is in principle random. But the matches you see with `1-X, 2-X ...` etc are not based on the contents-handler, it's based on the database query result and that very display is completely in the hand of the dev to override as they see fit (using the `SEARCH_AT_RESULT` and `SEARCH_MULTIMATCH_TEMPLATE` settings). I think there are some mixups of terms here. 

We could of course sort the cache in the `ContentsHandler` by `id` and use a `SortedDict` to guarantee the order. Likewise we could order the order in our default `SEARCH_AT_RESULT` function in the same way. But your suggestion is not dealing with the order-security though, but retaining the order of objects moved into each location which is a different thing. I must admit I see no reason whatsoever to introduce such a functionality in core; not only does it add a (completely arbitrary) new database field, I fail to see the advantage of it. I can see the advantage of having a *consistent* sorting, but not of remembering which order an object entered the room. The latter sounds, if anything, highly game-dependent. 

I'm willing to hear further arguments but as it is I'm leaning towards not adding this.

**Comment by vlegoff** [comment]
I understand your point.  Although it would add a little complexity and might slightly affect performance, I still believe it would be interesting, for two reasons:

1. It's not that arbitrary in my opinion.  Having Evennia remember in what order things are placed in another object location sounds like an important feature... and not that game-dependent.  As said, if a game developer wishes for a different ordering, he still can replace this one.  However...
2. As it is, I don't know of many ways this feature could be added to a single game without much more overhead (particularly since we cannot edit `DefaultObject` as game developers).  It would still be possible of course (probably through attributes, not a database field, which might not be great for performance in the end) but sounds a bit complicated in comparison.

So that's my reasoning for defending this issue.  On the other hand, obviously no one has ever complained about the fact Evennia doesn't remember the order in which objects are placed.  So it doesn't sound like a very necessary improvement to core.  But I would like to hear other's point of view on this issue.  I haven't seen "random ordering" on a lot of games as far as I can remember.

**Comment by BlauFeuer** [comment]
Containers (rooms, inventories, objects containing other objects) in many of the mu* I have seen display contents ordered with the most recently arrived first, and in fact many players strive to be the earliest to arrive and still remaining in the "bottom spot".  

I have been asked about this by exactly one user why Evennia does not do this, and I explained that contents are displayed in random order.  We do group contents in rooms with characters first, and we do keep track of when someone arrived and how many times via timestamps and counters - there's very little cost to it, but we have yet to bother sorting contents listings in any way, though once the data is available, sorting is a simple matter.  It is simply something we haven't done yet in our game code.

It's not uncommon for mu* to timestamp each object's last operation. Here is an example from a TinyMU:
```
Created:  Mon Sep 12 15:55:12 PDT 2012
Modified: Fri Feb  9 08:19:37 PST 2018
Lastused: Fri Feb  9 08:19:39 PST 2018
```

For this very application, `Lastused` is used, as moving the object is considered using it.

**Comment by chainsol** [comment]
Hmm, @BlauFeuer makes a good point with that. We could add those timestamps as database fields and then leave it up to each game to decide how to use it?

**Comment by Griatch** [comment]
@BlauFeuer I like the concept of storing modified/lastused more than having a field only for moving. As @chainsol points out, one could use those fields for other things. In evennia's case `modified` would always be set on a moved object since that would change the object's `location` field. Under what conditions would you separate between `modified` and `lastused`? I'd not be too happy to have to write to the object when, say, an Attribute on it is changed for example.

**Comment by BlauFeuer** [comment]
I don't really know the answer to that, Griatch. A move is like a lastused in that it's like touching the file, but there are other ways to use an object.  It may very well be that these mu* are not ordering contents by `modified` or `lastused` at all, but simply ordering them in memory because their contents is ordered.

Somehow that is persisted, because order is maintained after these types of mu* are stopped and started.  Are they doing something inefficient or is it smarter than our system in that it maintains ordering of contents by arrival?

The way I would handle this in my game (and unless this can be easily build into the `ContentsHandler`, I really think it's destined to be a game-specific feature) is store a dict of arrived objects in an attribute with a value being a timestamp, then sort contents based on timestamp keyed by each object.   I already keep track of arrival times for other reasons, so the cost of storing and reading the information is worth it for auditing purposes (as I also store WHERE it came from when it arrived).

The ingame uses of this additional information can allow a character to detect that a rock fell from the sky, or who spammed the room with several hundred spawned rubber duck objects.  It's a reasonable feature, and debatable as to if it needs to be part of the core framework.

**Comment by taladan** [comment]
Is there a reason that you can't use an [ordered dictionary](https://docs.python.org/2/library/collections.html#collections.OrderedDict) to handle content ordering?  Maybe I don't understand the complexity involved.

**Comment by TehomCD** [comment]
Contents is a cache of objects representing the many-to-one relationship of ObjectDB models which have the object as their location. The cache is stored as a dict, but could be an OrderedDict or whatever, certainly. What Griatch pointed out is that deciding how to sort them is game-dependent, and creating an additional database field just to support sorting is a very major change.

Introducing a last_modified datetime field might not be a bad idea. Objects need to do a save every time they move due to their location changing, so we're hitting the database already. The field could support additional functionality such as knowing when to purge soft-deleted objects by their last_modified field indicating when they were marked for deletion, for example.

**Comment by Griatch** [comment]
With Evennia 0.9 and Python 3.7, dicts are now ordered by default. Further sorting needs to be done manually per-game. Closing.
