### ISSUE TITLE
Inflect not pluralizing colored keys correctly

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1572]
#### Brief summary of issue / Description of requested feature:

The `plural` functionality added in https://github.com/evennia/evennia/pull/1385 is using the `inflect` library to automate pluralization. This is however not correctly handling when color codes are added in the `get_display_name` stage.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Make an object's `get_display_name` return a colored key, like ` '|cChar|n'`. 
2. Add multiple such objects and view them in room.
3. Inflect fails, 

#### Error output / Expected result of feature

Traceback. See @BlauFeuer's pastebin of the error [here](https://pastebin.com/ZJHsdkwt).

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This is due to the `inflect` library not being aware of color codes. Somehow this need to be handled for pluralization to work.

**Comment by BlauFeuer** [comment]
The context of my issue with it is that my game code's `get_display_name` returns the cyan name if  `self` (the object's typeclass) is a Character, therefore, during the unit test, which creates a character, inflect is given the decorated display name of the instance instead of its key.

This is of course as expected, but inflect doesn't want our color decorations or if we are builder, does not need the extra part that shows the dbref.  Should we then strip colors and dbrefs from the string first before giving it to inflect to search for plurals?

**Comment by BlauFeuer** [comment]
To run unit tests in my game code, I first alter:

```
diff --git a/evennia/objects/objects.py b/evennia/objects/objects.py
index 9e4d8d5..cb74f5c 100644
--- a/evennia/objects/objects.py
+++ b/evennia/objects/objects.py
@@ -302,7 +302,7 @@ class DefaultObject(with_metaclass(TypeclassBase, ObjectDB)):
             singular (str): The singular form to display.
             plural (str): The determined plural form of the key, including the count.
         """
-        key = kwargs.get("key", self.key)
+        key = self.key
         plural = _INFLECT.plural(key, 2)
         plural = "%s %s" % (_INFLECT.number_to_words(count, threshold=12), plural)
         singular = _INFLECT.an(key)

```
