### ISSUE TITLE
Feature Request: `@tel` Locks

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1579]
#### Brief summary of issue / Description of requested feature:
It would be nice if `@tel` supported locks for destination and object being teleported.

#### Steps to reproduce the issue / Reasons for adding feature:
In a core Evennia game right now, `@tel` can teleport anything to anyone, as long as one has access to the command. This can get...interesting. One can teleport themselves to anywhere and anyone, as long as you know either the name or the dbid. For instance...one can teleport another player into the dark room of the Evennia tutorial, over and over.

This also can be dangerous - one can teleport the Apparition anywhere they want as well.

#### Error output / Expected result of feature
The ability to set locks on a room/object to both restrict being teleported to and being teleported at all.

For instance, the Apparition could have a lock like `tel:false()`, so that it can't be teleported, and Limbo could have a lock like `tel_to:has_account()`.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
The `@tel` command itself could check these locks before going through with a teleport - literally in the line before `move_to` is called. Check `destination.access(obj_to_teleport, 'tel_to')` and `obj_to_teleport.access(caller, 'tel')`, and refuse to run the `move_to` if both checks don't pass.

**Comment by BlauFeuer** [comment]
You're going to take away my ability to loose the Apparition?  I always put it back when I'm done, though.

My game replaces CmdTeleport, so I really don't have an opinion on this other than to say that non-superuser staff shouldn't be prevented from doing the same thing most users are, but user-restrictions are a good idea, to prevent abuses.

**Comment by Griatch** [comment]
Yeah, this is probably a good idea. :)

**Comment by chainsol** [comment]
Hehe, sorry Griatch! Don't mean to be a pain, but finding little issues is fun.

BlauFeuer: A teleport permission would work, i would suggest the `perm(Admin)` lockfunc, making it work like `tel:perm(Admin) or perm(teleport)` for the apparition.

**Comment by BlauFeuer** [comment]
My concern was more that users would try to restrict staff by setting restrictive locks, but some non-superuser staff should probably just be fully immune from the teleport lock entirely.

And I'm glad someone's taking on these little issues, because they're larger in perspective of users' eyes, and trying to explain to them that it's that way in the default game doesn't go very far.

**Comment by chainsol** [comment]
Hmmm, OK, that's doable too - in the `CmdTeleport` itself then, one could just bypass the check if the caller passes perm(teleport) or perm(Admin).

**Comment by strikaco** [comment]
I'm not sure `tel` is the best choice of *name* for such a lock given that there is also already a `tell` lock. This would create ambiguity and any typos would interfere with a communications framework.

This operation involves moving an object from one location to another, no different than moving files around a filesystem or moving pieces around a game board. `move:perm(Builders) or perm(moving)` would be a better candidate for such a lock.

**Comment by Griatch** [comment]
I added `teleport` and `teleport_here` lock checks to the `tel` command so as to allow to optionally limit teleporting an object or limiting teleporting to a destination. `Admin` permissions and higher will always be able to teleport.

@strikaco I didn't want to add a generic lock-name like `move` because then one would reasonably expect the regular move operations to check this lock when it is instead handled by the `traverse` lock of exits.  It's a different thing to move normally to a location and teleport to it, so I think it makes sense to name the teleport locks more specifically.

Implemented in `develop` branch. Closing.
