### ISSUE TITLE
Feature Request: Auto-clean stale pid files

### ISSUE THREAD

**Issue by taladan** [evennia/evennia#1597]
More of a feature request

Currently if evennia hasn't stopped correctly, it can leave stale pid files in the game/server directory.
Doesn't it make sense to either have `evennia stop` clean up those pid files?  I know it currently reports their existance, but would it cause problems to have it automatically clean up stale pid files?  Or maybe have `evennia start` check and clean up stale pid info?

Server info:
Evennia 0.7.0 (rev b3e97b5c) (rev b3e97b5c)
    OS: posix
    Python: 2.7.14
    Twisted: 16.0.0
    Django: 1.11.10

**Comment by Griatch** [comment]
PiD files are generally left behind when killing the server in an abnormal way - by turning off the computer or by using `kill -9`. In those situations `stop` cannot do any cleanup since it has no time to run. One  could in principle do cleanup on `start`, yes. However, since the process management will change dramatically in Evennia 0.8 (see e.g. [this blog post](https://evennia.blogspot.se/2018/01/kicking-into-gear-from-distance.html) for a preview), it probably makes little sense to start implementing changes like this in 0.7.

**Comment by Griatch** [comment]
Closing this, it will be handled as part of the 0.8 changes.
