### ISSUE TITLE
Feature Request: contrib.rpsystem: Handle capitalization of sdescs in emotes

### ISSUE THREAD

**Issue by uint** [evennia/evennia#1620]
#### Description of requested feature:

Currently, sdescs are always displayed as they are - capitalized or not - without regard for whether they are placed at the beginning of a sentence or not. It would be great if there was a way to achieve proper punctuation.

#### Reasons for adding feature:

1. Grammar and presentation
2. A game will never look like an RPI without this.

#### Current output

<pre>
Slowly pacing, <b>Some person</b> gives the new shoes a try.
</pre>

#### Expected result of feature

<pre>
Slowly pacing, <b>some person</b> gives the new shoes a try.
<b>Some person</b> gives the new shoes a try.
Clack, clack, clack... <b>Some person</b> gives the new shoes a try.
</pre>

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

I'd like to work on this in a PR. I just need a little direction. I see two routes.

1. When targetting in an emote, the user can either `/target` or `/Target`, and the capitalization gets handled accordingly for those receivers who get the sdesc. My preference, though I understand this would make the `emote` command more complicated for the end user.
2. Automatic handling of capitalization. Some bits of prose can be challenging/impossible to figure out by code, however. Consider these:

  <pre>
  "I don't know..." <b>a lanky Brit</b> says.
  "I don't know..." <b>A lanky Brit</b> sighs and leaves, those words hanging in the air.
  </pre>

What would be preferable?

**Comment by Griatch** [comment]
Hm. I believe retaining capitalization as given by the user gives the most power to the user while keeping it intuitive. As you point out - auto-capitalization can be a little wonky.

However, how do you handle this is recogs? If you recog 'a tall man' with "Sebastian" or with, say, "my uncle", should you be able to capitalize that freely too, or should it retain whatever capitalization you recog:ed with?

**Comment by uint** [comment]
I think the 'alias' stored should be exactly what the user used with recog. Then, when the recog'd character is targetted in an emote, it should be printed as-is **unless** it is determined to be at the beginning of a sentence, in which case it is capitalized. So 'Sebastian' would always be printed as 'Sebastian', but 'my uncle' could become 'My uncle' at the beginning of a sentence.

Now, if we're assuming automatic capitalization, the code would determine whether a particular place is a beginning of a sentence. If manual, the user would do that (with emote syntax).

**Comment by InspectorCaracal** [comment]
I don't know what the status of this is, but I've been playing with something along these lines for my own project and I managed to come up with something that works and isn't horrible, so I figured I'd drop what I worked out in here.

Parsing sentences for auto-capitalization is kind of a nightmare and I'm always more of a fan of letting players have more control over what their emotes look like, so I went for the /target vs /Target method, combined with the prefix for `at_before_say` and `anonymous_add="first"` marked for capitalization.

I wanted to stick with the existing format logic as closely as possible, which is context agnostic, so instead of any major structural changes, I just changed the mapping dict values. Instead of being `obj`, it's a tuple of `(obj, capital)` where capital is either **True** or **False**. However, since a single object can be referenced multiple times, this means that you need to be able to correctly identify /target versus /Target in the *same* emote. To handle that, I append a 'c' to the dbref key if it's capitalized so it's a separate entry in the mapping dict (and changed `_RE_REF` and `_RE_REF_LANG` to be able to match both versions separately).

The actual capitalization part is via the `capital` flag being passed to the process_sdesc/recog functions. `process_recog` just passes it on when it calls `process_sdesc`, which then checks the flag and, if True, sets the first character to uppercase.

The end result:

* The sdesc automatically appended to the beginning of a message, e.g. `say` commands, has the first letter capitalized
* Any sdesc referenced by /Target has the first letter capitalized.
* Any sdesc referenced by /target is displayed as originally entered.
* Any other capitalization is preserved as-entered.

I don't _think_ there's any cleaner way of flagging initial-caps versus as-entered besides separating the mapping keys. Anything else would require the mapping to be context aware, which increases the complexity enormously and quite frankly I don't know how to do.

**Comment by Griatch** [comment]
This was now implemented in develop branch. This will close when that branch merges.
