### ISSUE TITLE
Runaway Memory Allocation

### ISSUE THREAD

**Issue by friarzen** [evennia/evennia#1642]
#### Brief summary of issue / Description of requested feature:

large complex objects being assigned to a .db. object causes an infinite memory allocation.

#### Steps to reproduce the issue / Reasons for adding feature:

1.  Add:
```
class Room(DefaultRoom):
    """
    """
    def at_object_creation(self):
        """
        500x250
        """
        roommap = []
        for y in range(0,250):
            row = [ {"color": "|111", "symbol": u"." } ] * 500
            roommap.append( row )
        self.db.roommap = roommap
    pass
```
2. run game...watch it work as expected.
3. change:  y in range(0,2500) and row to be * 5000 and update Limbo, game explodes in memory alloc.

#### Error output / Expected result of feature

The game loop thread locks up with cpu at 100% and memory allocated climbs until the machine runs out of memory and kills the process (at least, once my dev machine's 16Gig ram + 8Gig swap are exhausted).

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

This was tested against develop branch on a newly created game.

**Comment by Griatch** [comment]
The dict you are repeating has a size of [518 bytes](https://code.tutsplus.com/tutorials/understand-how-much-memory-your-python-objects-use--cms-25609). You then repeat that 5000 times per row (ignoring size of the list), and then each row 2500 times: 518 * 5000 * 2500 = 6475000000 bytes, or 6.4GB. I'd say it's not surprising it takes 100% CPU for a long while to build such a list - and appending in a normal for-loop nonetheless, where less compiler optimization is possible. 

I don't know why your memory would run out. You might want to put a print in there to see if you ever get past the loop and into the Attribute-assignment step. I can imagine that pickling a 6GB attribute can take some time and cause a lot of memory overhead. At any rate, this is hardly something that would be feasible in a realistic game, nor something we could protect against, it sounds more like something you'd need operating-system limits to control.

**Comment by Griatch** [comment]
@friarzen Closing this for now, comment and ask to reopen if if any new info comes to light that would make this an Evennia-related issue.

**Comment by strikaco** [comment]
> @ Griatch You might want to put a print in there to see if you ever get past the loop and into the Attribute-assignment step.

I don't think he would ever get there the way this is written. He'd be more likely to encounter application errors earlier in the process by refactoring the loop to be *less* optimal:

```
# sloppy example-- writes to DB on every iteration
self.db.roommap = []
for y in range(0,250):
    row = [ {"color": "|111", "symbol": u"." } ] * 500
    self.db.roommap.append( row )
```
> At any rate, this is hardly something that would be feasible in a realistic game, nor something we could protect against, it sounds more like something you'd need operating-system limits to control.

I agree with your assessment but offer some counterpoints to your conclusion.

Python does not enforce type checking and Evennia is excellent about trying to serialize anything you throw at it so it's all-too-easy to get away with pickling things you definitely shouldn't. Anybody can forget to set boundaries on an otherwise simple structure (like using a `list` when you need a `deque`) and end up with a poorly-scaled bucket of data whose storage mechanism does not warn of known storage limitations or impending serialization failure until it happens.

Before the OS even becomes a factor, even *if* one had the computational resources to pickle a 6GB object (most instances seem to be deployed to shared-resource VPS boxes), after some period of degraded server performance the product would likely get rejected by the DB anyway-- stock SQLite and most legacy relational databases won't take strings or blobs exceeding 1-2GB. My "sloppier" example should at least start yielding errors at the first instance of data loss instead of letting him generate 4 more gigabytes that cannot be stored.

Consider git's model-- meant for tracking string changes among files, it will complain about enabling LFS support if you commit large files and reject them altogether once too large. It would not be too wild to do the same; better than nothing, `sys.getsizeof` should suffice for checking the size of growing objects upon serialization and once it passes the 50%/75%-of-limit mark, it would be gracious to spew warnings about the object's size to the log so one has time to refactor before experiencing data loss. If it can't be written, simply dump it to disk (so it persists *somewhere* other than RAM) and raise exceptions upon object access until someone intervenes.
