### ISSUE TITLE
Security issue: XSS in web client

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#1739]
#### Brief summary of issue / Description of requested feature:

I received another communication from a user concerning a possible webclient exploit:

> OK, potentially more seriously I just managed to XSS the web client. This one's in the MXP url substitution and is an interactive XSS, so of a lower risk than anything non-interactive:
> 
> ```tell me=|lcsay My cookies are: \"+document.cookie])//|ltClick Here for Prizes!|le```
>
> This could be sent to any other player, and clicking the link will execute arbitrary JavaScript.
>
> XSS could then be used to hijack the admin session via the admin interface, etc.

#### Steps to reproduce the issue / Reasons for adding feature:

See above. 

#### Error output / Expected result of feature

The MXP parser component of the HTML should be expanded to filter out things like this.

**Comment by strikaco** [comment]
I'm not convinced the solution lies with MXP.

The string in question is not a valid HTML fragment nor is it renderable by Python. Checking for `*document.cookie*` isn't enough-- you can try to scrub keywords, but since it's Javascript I'm sure this guy will pop up again with another exploit in short order by obfuscating the same code he just sent you. So to do any sort of sanitizing at the MXP level you'd have to anticipate every Javascript obfuscation method conceivable while interpreting the whole thing as a string...in Python. You'd go from spending your time developing a MUD framework to spending all your time maintaining a very crappy and easily-outwitted antivirus engine. :)

The stated problem seems to be that the webclient itself will render arbitrary data in a language that only it can interpret. The webclient freely rendering that which is escaped by default in Django is a design inconsistency, especially since they share the same data-- similar code could just as easily be injected into attributes if the webclient renders HTML all the same.

**Comment by Griatch** [comment]
@strikaco The sole purpose of the MXP link ought to be to fire a given MUD command; so the available strings it should accept might be possible to limit? 

It's not JS, but we can for example perfectly handle the case of storing `"@set me <h1>This is big text!</h1>"` - looking at that with `examine me` in the webclient will not cause any html to be executed (it's different if you look at the attribute with `@py`  as mentioned in #1369).  I'm probably not fully understanding how the "document.cookie" exploit works though.

**Comment by strikaco** [comment]
Well the *issue* isn't with HTML strings, it's with the arbitrary fragments of Javascript that get injected into a command and remain inert until transitioning from the Python ecosystem and into Javascript. This is the fundamental mechanism that code injection exploits-- when you don't validate input (or output), it matriculates through your systems and APIs until the injected code manifests itself in a manner you didn't intend. Here it sails right through Django until it explodes in a Javascript client.

`document.cookie` means nothing in Python/Django but once JS interprets it it becomes part of a greater operation. Same with `eval('doc' + 'u' + 'ment' + '.' + 'coo' + 'kie');` (but this *should* be stopped by CSP...)

People have literally been at this for over 20 years now. I see new obfuscation methods weekly.
https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

Here's what the *actual* rendered string comes across as once the webclient renders it...
```
<a id="mxplink" href="#" onclick="Evennia.msg("text",["say My cookies are: \\"+document.cookie])//"],{});return false;">Click Here for Prizes!</a>
```

...which, being a valid HTML fragment, is now capable of being sanitized by the `bleach` library without us needing to reinvent a wheel.

```
>>>> import bleach
# bleach can be configured to preserve things like id, i'm just lazy-- the point is to kill the onclick
>>>> bleach.clean('<a id="mxplink" href="#" onclick="Evennia.msg("text",["say My cookies are: \\"+document.cookie])//"],{});return false;">Click Here for Prizes!</a>')
'<a href="#">Click Here for Prizes!</a>'

```

Without understanding anything about how the webclient works, my recommendation is this: set up an `/api/sanitize` endpoint. Before the webclient updates the document, throw the string it intends to present against `/api/sanitize`. It should get a sanitized string back. Given the malicious string presented, the result is safe to display-- `<a href="#">Click Here for Prizes!</a>` will go nowhere.

**Comment by chainsol** [comment]
The problem is that MXP is meant to allow clickable links that affect the client - run a command, for instance, to allow clicking "east" to go east.

Your suggestion would remove that functionality.

**Comment by friarzen** [comment]
This is essentially a case of the client not protecting itself/user from a malicious server.
The usual approach is to sanitize ALL input from the server by performing the HTML rendering client side and tyrannically controlling what gets added to the DOM.  As chainsol mentioned, however, from what I can see the whole point of MXP is to pass a link that is "intentional XSS".  I think the solution for this will require a combination of new outputFuncs and client side rendering, so that the client side can sanitize Text outputfunc messages that it receives and do something different with the new MXP outputFunc's data.  One approach would be to match the MXP requested-action to a predetermined list of allowed client actions.
`outputFunc ("MXP", ["east"])` for example would trigger the client's `mxp_east()` function

**Comment by Griatch** [comment]
Not sure I know how to proceed with this one :)

**Comment by friarzen** [comment]
Since the Server and the Webclient are both under the control of the same administrators, we can't guard against malicious game servers (bad actors can always modify their game code to do evil).  The case we really need to guard against is "random evil player" sending malicious payloads to other innocent players.  This is essentially an extension of the reasoning/design behind inlinefuncs().  We need a way to force separate the code being executed on the webclient from whatever input the player actually sent.  Currently, the MXP code creates <a id='mxplink' href="#" onClick="do stuff evil stuff here">
We need to change that to onClick="only do approved client-side func() here with possibly evil data"

**Comment by whitenoiseoss** [comment]
This issue seems impossible to fully deal with, as chainsol points out it's part of the functionality of the feature itself. As in, **this is an inherently risky protocol to run.**
Representing Evennia, I would probably just make that known in documentation very plainly and with fanfare around it so people know it should be locked down.

As possible solutions:
I have never played a MUD that makes heavy use of MXP, so I don't know how people typically use it. However, blacklisting/removing anything will be a losing battle. Any blacklist anything in the security realm is defeatable. Is it possible to whitelist MXP usage to a-zA-Z? Or is this just parsed along with everything else in a way where that's not feasible?

**Comment by Griatch** [comment]
Thinking about this more, I think the way I'll resolve this and get the best of both worlds is to default to only *outgoing* MXP being allowed - that is, you can create MXP in code (such as clickable links in menus) but anyone cannot add MXP from the game. It could be a default setting. People wanting the full MXP experience then need to activate this explicitly and will have to accept the risks.

**Comment by Griatch** [comment]
This is resolved in `develop` branch, via adding support both for disabling MXP as well as allow it to be one-directional (that is, the server can send but the client may not embed MXP links in its input).
