### ISSUE TITLE
Add references to flatpages, sites admin on the EVENNIA_ADMIN template

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1744]
#### Brief summary of issue / Description of requested feature:
Evennia ships with the Flatpages contrib installed and enabled. Like the Help Entry system it's a very useful interface for non-web-developers to contribute content, but it isn't obvious that it exists, how to access it or how to use it.

The Django Sites framework is also installed and enabled; the settings file is dismissive of the `SITE_ID` value but as set any reference to the template tag `{{ domain }}` will return `example.com`. This includes the built-in Django password reset workflow which is also enabled by default. We should expect users to want to be able to change this post-installation but we don't make it obvious how to do so. Failure to do this results in emailed password tokens referencing `example.com` instead of the actual domain. It also breaks the `get_absolute_url()`/`View on Site` features in the Admin pane which depend on this being set properly.

The only way devs would learn of either of these features is if they clicked through to the default Django Admin page and understood what all the registered apps are.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Set `EVENNIA_ADMIN = True`
2. Go to `/admin`
3. Behold

#### Error output / Expected result of feature
This is an easy fix. These features should have a line item on the Evennia Admin template explaining what they are and their use. Something like:

* Pages: "Create, edit or publish web pages without needing to know how to code."
* Domains: "Whether you're setting up your first game or running multiple games using the same codebase, configure your domain name(s) here."

**Comment by strikaco** [comment]
> It also breaks the `get_absolute_url()`/`View on Site` features in the Admin pane which depend on this being set properly.

It turns out not setting up Sites/`SITE_ID` properly also impacts the flatpages admin pane too-- when you go to create a page, you're expected to select a site to post it to. On a stock install, `example.com` is the only option!

**Comment by Griatch** [comment]
@strikaco: Added. Creating a page, you get an option to create the domain directly (instead of example.com), and it looks like you then have to manually edit `settings.SITE_ID` to match the site-id you just created. It seems to be an unexpectedly clumsy work flow. The admin site for the flatpages should probably customized to show the ID clearer; the domain could probably also be managed as an inline from the Pages admin since it would seem an Evennia game would generally only use one domain linked to one settings.SITE_ID. That's for another day though. 

Closing this as implemented..
