### ISSUE TITLE
Gametime w/ Custom Calendar tutorial questions

### ISSUE THREAD

**Issue by thenomain** [evennia/evennia#1753]
#### Brief summary of issue / Description of requested feature:

https://github.com/evennia/evennia/wiki/Gametime-Tutorial#a-game-time-with-a-custom-calendar

"In our case the game time starts at year 0, month 0, day 0, and at midnight."

This raises one big question to me: Is there a 'Month 0' and 'Day 0' that will come up every year/month? If so, why?

If not, I think the tutorial would be better if the game starts on 'month 1, day 1' (Even though the real world calendar has no 'year 0', that also looks out of place.) Even if the reason for this is normal code logic, the players will probably not have exposure to this logic.

Thanks.

**Comment by Griatch** [comment]
The `custom_gametime` module is adopted and broken out of the original gametime code which had this functionality in-built for a long time (making it a contrib made it more modular). It works with 0 simply because it made for a homogenous API for all different units in the `realtime_to_gametime` function: 

```python
realtime_to_gametime(secs=0, mins=0, hrs=0, days=0, weeks=0,
                     months=0, yrs=0, format=False):
    ...
```

These days however, the default gametime module is actually using Python's` `datetime` module that that does *not* accept month=0 and day=0, making the custom behavior inconsistent with the default, as mentioned. 

So I think it makes sense to change the custom time module to be consistent with the default behavior and start counting month and day from 1 rather than 0 (raising an error if giving 0).

**Comment by Griatch** [comment]
Changed days, weeks and months to start from 1 rather than 0 in the contrib. Implemented in develop.
