### ISSUE TITLE
spawn and return_parents

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#1775]
#### Brief summary of issue / Description of requested feature:
using spawn(return_parents=True) seems to return all the prototypes available, instead of the specific parent

#### Steps to reproduce the issue / Reasons for adding feature:
spawn({'prototype_parent':'kobold'}, return_parents=True) 

Kobold is a prototype saved inside the module.

#### Error output / Expected result of feature
Returns a dictionary of what appears to be all my prototypes, including the specified one. Using spawn without return_parents correctly creates the specified prototype.

**Comment by Griatch** [comment]
@kaleara This is expected behavior; the `protparents` (note the plural), is the entire protparents structure available to the prototype at the time of creation. This is created on the fly by the spawn function and the fact that it can be returned is a legacy way to obtain the choices available. 

What would you have expected this to return? Only the "kobold" parent? The kobold parent along with the tree of parents kobold inherits from too?

**Comment by kaleara** [comment]
Yeah, I half thought that might be the case, but based on the wiki article and the api docs, I expected it to return kobold (and any parents kobold might have, which would explain the plural). The way it behaves still works for my purposes, since I am simply trying to validate that a key exists as a prototype.

**Comment by Griatch** [comment]
@kaleara I have updated the `spawn` docstring to better explain what the `protparents` kwarg does. Will also take a second look at the wiki. Closing.
