### ISSUE TITLE
@examine, @olc, and @set attribute categories!

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#1805]
#### Brief summary of issue / Description of requested feature:
@examine and @olc's attribute displays do not seem to show the category an Attribute belongs to.

Not sure if @set can set attribute-categories either. IT really needs to be able to do that!

#### Steps to reproduce the issue / Reasons for adding feature:

1. @py self.attributes.set('test', category='booga', value=5)
2. @examine self
3. Nope, no category for that... it's a problem if you have two attributes of the same name and different categories!

#### Error output / Expected result of feature
See above.

I think it would be good to use the same notation for attributes and tags.
test[booga] = 5

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

**Comment by aarcro** [comment]
This will impact #1928 Might need a different syntax for category `set test{booga}[0] = 5` or maybe deal with tags explicitly `set/category test = booga`

**Comment by Griatch** [comment]
@aarcro The syntax for setting tag categories is like this: 

    tag obj = tagname : tagcategory

it sounds like it would make sense to mimic this for `set`. The problem is that `set` can accept a much larger variety of values (like `dict`s which also have `:` in them). So most likely this syntax would be easier to parse: 

    set obj/attrname : category = value

The alternative would be 

    set obj/attrname = value : category

This is closer to the syntax of `tag` means having to be careful so as to not confuse that last `: category` with any other structure being a part of the value.

**Comment by aarcro** [comment]
I think I like the first option. category is really metadata on the attrname, so I think it makes sense to go prior to the `=` (And it does make the parsing easier).

Do we need a different command to change category or assign one on an attr that doesn't already have one? Or are categories only used at create time, and for disambiguation?

**Comment by Griatch** [comment]
Changed `set` and `examine` to support/view `category` with the given syntax.

Haven't touched `olc` at this point, thinking about if I should make this a contrib instead, it's not used very much ...
