### ISSUE TITLE
Prompt is not displayed properly anymore in the 0.9 webclient.

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1858]
Prompt is displayed in the lower left corner of the window in the webclient instead like it used to be - in it's own special field above the input pane.

OS: Debian 9.9 with LXDE
Browser: Firefox 60.7.1esr (the default one from apt)

![2019-06-30-123443_1366x768_scrot](https://user-images.githubusercontent.com/50782109/60395423-8b0c7e80-9b33-11e9-88e0-b926836e2adf.png)

**Comment by Griatch** [comment]
The reason is likely because of the new multple-input panes: It's not clear to which input-pane a prompt should be attached, especially since you can now move them around freely on the screen. Maybe one should keep the prompt where it is at the bottom, but make the bottom row its own so it doesn't hover above other things?

**Comment by BP-Santo** [comment]
There is empty space on the right of the Input tab title for the input pane - a prompt could be assigned to an input tab and appear in that very space. Possibly enabling also say prompt2 being send to input pane2?

**Comment by Griatch** [comment]
If you move panes together they will be grouped into tabs that will that space, unfortunately.

**Comment by BP-Santo** [comment]
Howabout... it gets to live on the bottom of the main output pane, just taking one line tall space there with some padding above it? Each output panes could capture their own prompt too.

**Comment by Griatch** [comment]
This was implemented and fixed in #1884. Closing.
