### ISSUE TITLE
up/down arrow in ssh connections

### ISSUE THREAD

**Issue by aogier** [evennia/evennia#1896]
Hello, I'ts a couple days I'm studying ssh internals (hence the PR yak shaving :P) because It works generally better than telnet on my system:

 * `<enter>` work correctly (apparently a non-busybox client problem, that's another story)
 * up/down arrows works as expected, scrolling through history

I'd like to hack a `<tab>` support for available commands, that would be great for an Evennia-based sideproject I'm working on, but I'm having an hard time figuring out the whole architecture. Have you perhaps got some useful pointer you can give to me in order to find where non-printable input get processed?

Thanks in advance, and have a nice day!

**Comment by Griatch** [comment]
FYI, noone uses raw `telnet` unless they are masochists. ;) I use terminal-based `tintin++` and see both correct use of `<enter>` as well as arrow-up to go through history. Another common terminal client for linux is `tinyfugue`. 

But anyway, The non-printable input, you mean input from the client? For telnet, this would be GMCP/MSDP subnegotiation. There is no SSH standard for supplying the same as far as I know, and no mud clients that support it. Maybe some sort of per-character mode, maybe? 

For input, you'd need some way for the SSH connection to separate a line-send from an "invisible" OOB (Out-Of-Band) message. Today, the SSH input is always handled as text, see here: 
- https://github.com/evennia/evennia/blob/master/evennia/server/portal/ssh.py#L221
- Compare for example the same line for the telnet_oob MSDP communication protocol: https://github.com/evennia/evennia/blob/master/evennia/server/portal/telnet_oob.py#L361

For output, you'd then also need a way to send OOB communication over SSH. That'd mean converting an outputfunc into something to send on the wire over SSH. 
- Sending of non-text OOB methods is not currently supported on SSH since there is no commonly used standard for it: https://github.com/evennia/evennia/blob/master/evennia/server/portal/ssh.py#L324
- Compare the same for telnet, which routes to GMCP/MSDP: https://github.com/evennia/evennia/blob/master/evennia/server/portal/telnet.py#L384

If so, it would go out through the [send_default](https://github.com/evennia/evennia/blob/master/evennia/server/portal/ssh.py#L324) method of the ssh

**Comment by Griatch** [comment]
Since there was no further follow-up on this, I'm closing this.
