### ISSUE TITLE
websocket breaks multline input to py

### ISSUE THREAD

**Issue by aarcro** [evennia/evennia#1935]
#### Brief summary of issue / Description of requested feature:

When using the websocket client to interact with a python shell, only the first line is handled by python, the rest of the lines are handled by the game engine

#### Steps to reproduce the issue / Reasons for adding feature:

1. open `/webclient/`
2. connect with developer account
3. `py`
4. input multiple lines into the input box (shift-enter for line breaks)

#### Error output / Expected result of feature

Expected: multiple lines of python execute (including indented blocks)

Actual: The fist line is executed as python, the second and following are treated as game commands.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Reproducible on `master`

[Example screen session](https://www.dropbox.com/s/kvie3ikxb7872nz/multiline-py.gif?dl=0)

**Comment by friarzen** [comment]
Hmm...this is a tough one actually.  Shift-enter multi-line input was added to allow simple command-after-command scripting, so things like "go west 3 times, down, attack thing, chug potion" would work.  This implies we need some way to input multiple lines as a single line (and probably an option setting for which should be default for this users playstyle).

**Comment by aarcro** [comment]
It doesn't need to be "multiple lines as a single line". Sending each line singly would work, except that stripping the leading white space doesn't let you send indented python code.

I don't think the JS client is splitting on newline and sending each as a message, some how it is already sending all the lines in one message. The handling only routes the first line to the interpreter.

So this issue is specifically that:

```
print('hi')
print('there')
```
as a single input fails, when sending each line separately would succeed.

**Comment by friarzen** [comment]
Well, I haven't checked how @py with no arguments handles waiting for new input lines, but I suspect it is reading whatever comes in the next inputfunc, multi-line or otherwise.

What I do know is that the webclient DOES currently split any multi-line input into multiple distinct calls to evennia.msg() via the onSend() plugin callback chain.   See [default_in.js](https://github.com/evennia/evennia/blob/master/evennia/web/webclient/static/webclient/js/plugins/default_in.js) lines 31-34, which eventually ends at the webclient_gui.js's [onSend()](https://github.com/evennia/evennia/blob/master/evennia/web/webclient/static/webclient/js/webclient_gui.js)

**Comment by Griatch** [comment]
I have fixed the webclient so that it does not aggressively trim command input whitespace. So if entering one-by-line code into py, it should now work the same way as with a telnet client. 

Entering multiple lines in one go in the input pane will still not work correctly with `py` at this time. This is not unique to the webclient, the same seems to be the case if sending from a telnet client with a multi-line input pane.

**Comment by Griatch** [comment]
With this example: 

```python
> py 
for i in range(10):
    print(i) 
>>>
Command 'print(i)' is not available. Type "help" for help.
````

- Explicitly entering a line feed after each line above produce the correct result. The error is when entering it all at once in the webclient multi-line input pane. 
- When sending multiple lines from the same input pane, the web client will will split each line into a separate command `text` inputcommand. This _would seem_ to be the correct operation, but for some reason the `py` parser does not react to the commands sent after the first one - but instead reacts as above. 
- The telnet client works differently - it will split by line at the protocol level. When trying with a multi-line supporting telnet client (Potato), this worked correctly (except potato does not allow entering an empty string, so one must end with a single space in order to make the code execute).

**Comment by aarcro** [comment]
I was still seeing that leading white space from the webclient was not respected to create an indented block inside a `py` session. And I found some things!

evennia/commands/cmdhandler.py around line 664: `raw_string = raw_string.strip()` This is what's dropping the leading spaces when sending lines to `py`

evennia/commands/default/system.py around 362: `line = yield(prompt)` I'm guessing this has something to do with accepting the multi line input.

**Comment by Griatch** [comment]
@aarcro Remember that you need to reload the Portal as well if you want to apply this change - so `evennia reboot`, not just `evennia reload`.

**Comment by aarcro** [comment]
Hmm.. didn't know what the difference was. I think I normally do reboot, pretty sure I restarted the whole docker and force reloaded the page, but I'll try again.

**Comment by Griatch** [comment]
@aarcro Any updates?

**Comment by Griatch** [comment]
Since I've not heard any more replies on this, I presume this is resolved now. Closing.
