### ISSUE TITLE
Clothing contrib will make look command not work on self

### ISSUE THREAD

**Issue by Panzerbyte** [evennia/evennia#1948]
#### Brief summary of issue / Description of requested feature:
After having installed the clothing contrib, restarted the server and having forced the Character typeclass on my character, the 'look' command no longer works on self. It simply will not give any response or error. The clothing contrib commands work as intended, and can create and wear clothing with it.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Install clothing contrib as described in the file description
2. Restart server and force typeclass on self
3. 'look me/self'

#### Error output / Expected result of feature
There is no error output on this, but the expected result of 'look self' should be there.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Master cdb9e329

**Comment by Griatch** [comment]
@Panzerbyte I cannot reproduce this error. 

I did these changes: 

- Added `self.add(ClothedCharacterCmdSet` to the character cmdset
- `type self = contrib.clothing.ClothedCharacter`
- reload

```
> look self
Griatch(#1)
This is User #1.

Griatch is not wearing anything.
```

Seems to work correctly. Am I missing something else needed to reproduce your issue? The Clothing contrib does not override `CmdLook` as far as I can tell.

**Comment by Panzerbyte** [comment]
So I did type self = contrib.clothing.ClothedCharacter and the look command worked again. The typeclass was the default character typeclass.
It should have loaded though, since in my Characters.py I've got class Character(ClothedCharacter). Is that not correct?

**Comment by Griatch** [comment]
You need to force-apply the new typeclass to yourself, making sure the startup hooks are re-run, since those are otherwise not run except for new objects. 

If your typeclass was DefaultCharacter (not sure if this is what you mean by "default character typeclass"), it would be because of an error in your normal typeclass making its module impossible to load (it then falls back to DefaultCharacter and puts the error in the log). 

Either way, this sounds like it can be closed.

**Comment by Panzerbyte** [comment]
Thank you Griatch.
