### ISSUE TITLE
[Feature Request] `destroy` confirmation should be explicit

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1968]
#### Is your feature request related to a problem? Please describe.
When destroying objects, the confirmation step (`are you sure you want to destroy ___?`) is too generous with its interpretation of the user's intent, especially in regards to misspelling.

`tes` is presumed to be "yes", `ni` or `n` are presumed to be "no", but something completely random like `lol` is also interpreted as "yes." 

#### Describe the solution you'd like
I'm assuming things were done this way for convenience but for a destructive operation, I don't think "yes" is a sane default.

If confirmation has not been bypassed at the class level or through use of the `force` flag, destruction of objects really ought to require an explicit affirmative from the user.

**Comment by Griatch** [comment]
It's trivial to change the check so that if you write 'lol', it will ask you what you meant - we could do this by all means. 
But the default will remain `yes`, and as such pressing return will accept the action. If a developer wants this to be more explicit for their builders they can change this for their game.
