### ISSUE TITLE
[Feature Request] Automatic `strvalue` handling by AttributeHandler

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1981]
#### Is your feature request related to a problem? 
`strvalue` is a useful and underimplemented feature that could probably be made a whole lot more intuitive at the `AttributeHandler` level. 

As it is prototypes won't take or use them and this field cannot be accessed by shortcut methods. Commands like `ex` will return null values for attributes where `strvalue` is set because they are tooled to only access the `value` field.

#### Describe the solution you'd like
Rather than giving the dev the option of which field to store data in, figure it out for them-- if the value provided is a string, store it in `strvalue`. If it's anything else, put it in `value`.

Since the two are mutually exclusive (both cannot contain data) and neither field is indexed, any generic `get()` or `obj.db.foo` for the attribute should return the first of (`value or strvalue`) without anybody being the wiser.

#### Additional context
* The search methods would need to be changed to account for searching by type-- either search both fields with an OR/`coalesce` or infer the type from the query object provided to figure out which of the two columns to search in.
* Not sure what impact this would have on the Django admin-- at simplest this would warrant a second widget for `strvalue` alongside `value` but that is ugly and confusing. I don't have any experience customizing the Admin side of Django so I don't know any solutions to compensate for this.

**Comment by strikaco** [comment]
`strvalue` support could probably be made a whole lot more intuitive at the AttributeHandler level.

Rather than giving the dev the option of which field to store data in, figure it out for them-- if the value is a string, store it in `strvalue`. If it's anything else, put it in `value`.

Since the two are mutually exclusive (both cannot contain data) and neither field is indexed, any `get` for the attribute should return the first of `(value or strvalue)` without anybody being the wiser.

The search methods would need to be changed to account for searching in kind-- either search both fields with an `OR` or apply the same logic as done on write to figure out which field to query.

**Comment by strikaco** [comment]
On further thought, an even better solution would be to drop the idea of storing *data* in the `strvalue` field at all and replace it with something that stores the *type* of what was serialized in `value`. It would be a dynamic value updated on every write to the `value` field and needs no Admin interface presence or other reaching changes since it would not user-configurable. Even lookups and searches should continue to work as they currently do, just not as optimized as they *could* be.

The result would be that when you know you're searching for a string, you can filter for `Q(db_type='str', db_value='foo')` in the queryset and iterate/unpickle just those results.

This obviates the need for the clunky either/or field system and avoids many of the potential userspace pitfalls with arbitrary casting and routing.

Since we would be doing type checking at that point, a beneficial side effect would be the ability to slipstream typechecking into Attribute locks to make them more useful as well-- set `type:str()` or `type:inherits_from('world.classes.Whatever')` on the Attribute and if the type does not match, the update is rejected.

**Comment by trhr** [comment]
I would disagree with feature as stated. strvalue can be filtered on in a queryset without using a Q, which is quite a bit more advanced than just .filter(__strvalue__icontains=), whereas a pickled field cannot be used in such a way.

I agree that it needs better support, perhaps a wrapper function in attributehandler gets the best of both worlds and allows the actual Q search to be obfuscated from the user having to write it?

**Comment by Griatch** [comment]
The `strvalue` is an optimization feature, for fast icontains-style lookups of strings not really possible with pickled fields. They are intentionally not available for prototypes because they are not there for use by builders. `strvalue` is intended for under-the-hood use if you need to use Attributes to build some custom system. 

I'm not 100% sure a `type` field is really needed either, since it's only of limited use - just because you have a type of `list` does not say anything about the content of that list - if it has multiple nested layers of iterables, for example. I guess the 'proper' alternative would be to add the full types of the [typing](https://docs.python.org/3/library/typing.html) library, but that's likely not any easier to query by ;) 

(Already today, if you want to track type with that kind of system, you can make so yourself by using  the Attribute's `db_category` - just make categories on the form `"categoryname:type"` or something and filter your Attributes with `_endswith`. )

**Comment by strikaco** [comment]
> I would disagree with feature as stated. strvalue can be filtered on in a queryset without using a Q, which is quite a bit more advanced than just .filter(__strvalue__icontains=), whereas a pickled field cannot be used in such a way.
> 
> I agree that it needs better support, perhaps a wrapper function in attributehandler gets the best of both worlds and allows the actual Q search to be obfuscated from the user having to write it?

If it sways your opinion at all, I agree with you, which means I probably wasn't clear enough. Under no circumstance should users be forced to craft Q objects; that would be obscene. The intended implication was for that to be implemented under the hood. As far as users are concerned, the current API should not change at all!

> I'm not 100% sure a type field is really needed either, since it's only of limited use - just because you have a type of list does not say anything about the content of that list

Perhaps not, but I think you're getting the wrong message as well-- limited use is the point. There is no sane way to recursively index the contents of arbitrary pickled objects without reinventing full-text search...hardly in-scope, and possibly unnecessary-- I hear Django 3 adds native support for JSON fields.

The point is that all values are pickled, so for *any* query, we can reduce the search scope of objects to UNpickle by prefiltering objects that cannot possibly match based on their known parent type. If you're searching for attributes whose value is `23` (as a proper `int`), we can immediately ignore any `str`, `dict`, `list`, etc. matches by requesting *only* `int`-type attributes. Then you're only unpickling a subset of the total attribute pool to do comparisons.

This starts to matter when there are many (~1M) objects present because the attribute pool grows at least twice as fast as the object pool by default. The amount of caching Evennia does very efficiently *hides* the problem at smaller scale but struggles once resource constraints are reached.

**Comment by Griatch** [comment]
> The point is that all values are pickled, so for any query, we can reduce the search scope of objects to UNpickle by prefiltering objects that cannot possibly match based on their known parent type. If you're searching for attributes whose value is 23 (as a proper int), we can immediately ignore any str, dict, list, etc. matches by requesting only int-type attributes. Then you're only unpickling a subset of the total attribute pool to do comparisons.

I think you are under-estimating the power of the PickledField used for the Attribute `value`. Knowing a type offers no real search advantages, because there is no need to de-serialize for querying something like the simple `int` `23`. The pickle-format is locked to a string-like format. What the Pickle-field does is simply to serialize `23` into the same string-form and run a normal text query for it. Apart from that first pickling of `23` there is no speed difference between querying `strvalue` with, say `"23"` in it as a string, or querying the `value` with a pickled `23` in it. 

The same thing is true for querying for the stored list `[2,3,4, {"foo": "bar"}, 5]` - you could do a query for this in the database and find it very efficiently since it has a unique pickled serialized string form which it will match in the database. What you _cannot_ do is to query the database for Attributes storing lists where the 2nd element is `3` ... but that you cannot do with a type either. 

As for JSON-field support, I expect it to be limited to certain databases. It will likely not be a general solution for Evennia Attributes; if it was we could certainly do something with that though; in e.g. Postgresql you can do quite interesting queries of JSON fields.

**Comment by strikaco** [comment]
Ah. I was under the impression Pickle stores data to a binary format, not string. Thanks for explaining; that does shake my conviction a little.

Before I ran into ease-of-use issues with `strvalue` it subjectively seemed to be outperforming its counterpart so I figured this "typed value" model could be extended for similar gains.
