### ISSUE TITLE
[BUG] CmdScripts - Runaway memory usage when number of scripts is high

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1994]
#### Describe the bug
When a large number of objects inheriting from the Script typeclass exist (at least 100K in my case-- I am trying to use Scripts to represent intangibles), running CmdScripts seems to want to load the entire queryset into memory before displaying them all in a single dump.

#### Expected behavior
That many results are not easy to work with in a terminal, so it would be helpful if there was some sort of breaker to filter/chunk/paginate the response in some way and lazily load it (Django .iterator() piped to evmore?).

**Comment by Griatch** [comment]
@strikaco I have made some changes to the `scripts` command so as to run it into EvMore. This will at least paginate the _display_ of the scripts in the list. Your memory issue of fetching the entire queryset at once is not addressed though. 

Proper query-pagination is tricky to do this way, since what you want is not just a gradually growing list of objects but a proper formatted list. There is a `Paginator` helper in Django but to my surprise this does not present a generator, so one would need to wrap this somehow. 
One would then need to extend EvMore to accept a line-generator function. The problem then is that you won't automatically know the size of the full list (how many pages you'll get). There could be ways around this, but it's neverthless something I've not looked more into.

**Comment by strikaco** [comment]
Awesome!

> The problem then is that you won't automatically know the size of the full list (how many pages you'll get)

This *can* be accounted for, it just requires a few extra steps made clunky by the ORM.

For any defined queryset `qs = ScriptDB.objects.all()` it should work something like:
* `num_records = qs.count()` to get the total number of records
* `pages = int( (num_records or 1) // (screen_height or paginate_by or whatever) )` to calculate the number of pages
* `for obj in qs.iterator(): render object` to load as little of the queryset into memory at once as possible

...or just use the Paginator object, like you said. Commands are basically Views so wrapping it should be straightforward; it's the rendering that's difficult.

The biggest problems I ran into when I (topically) looked at this were your point that `one would then need to extend EvMore to accept a line-generator function` and the fact that it is also passed through EvTable which too seems to require all data be present before it renders (though using EvTable here isn't *necessary*).

**Comment by trhr** [comment]
Alternatively, and perhaps more sanely, use SQL LIMIT/OFFSET queries to return smaller chunks of paged results in memory.
