### ISSUE TITLE
[BUG] CmdFind - Runaway memory usage with improper syntax

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2012]
#### Describe the bug
Was dealing with a "bug" where the `find` command was returning seemingly random results and/or dumping the entire contents of the database. Like #1994 this caused the entire queryset to be loaded into memory before rendering to the user.

It turns out the syntax I was using was incorrect but it was accepted anyway, which led to these side effects.

Ex: `find/startswith = searchterm`

Given that I did not provide a lhs and the rhs should only be a dbref/range, validating both before executing any queries would be beneficial.

#### Environment, Evennia version, OS etc
Dev

**Comment by Griatch** [comment]
@strikaco Btw, it's worth to stick with `master` branch for bugs like this; it is still the most quickly updating branch at this time.

**Comment by strikaco** [comment]
@Griatch Thanks for the pointer, but I'm a bit confused. I was under the impression `develop` was the bleeding-edge branch. Should PRs for things like this be submitted against `develop` or `master`?

**Comment by Griatch** [comment]
Generally, `master` is always for bug fixes, `develop` is for completely new features. This one definitely belongs in `master`. 

Usually though, once develop merges into master (a new release), work continues on master for a while since there are usually bugs popping up that needs to be fixed. Once switching to develop, most work will happen on that. At the moment I've not really started up working on new stuff in `develop` branch and is working on stuff in master, so it's the fastest updating branch right now.
