### ISSUE TITLE
[Documentation] Add python3-pip as a requirement

### ISSUE THREAD

**Issue by spiralofhope** [evennia/evennia#2017]
#### Documentation issue

https://github.com/evennia/evennia/wiki/Getting-Started#quick-start

Quick Start step 6 will fail if `pip` actually summons `pip2`, as with Debian 10.

``` bash
pip install -e evennia
``` 

#### Suggested change

Include `python3-pip` in [the `apt install` list](https://github.com/evennia/evennia/wiki/Getting-Started#linux-install).

Change `pip` to `pip3` in [the Quick Start](https://github.com/evennia/evennia/wiki/Getting-Started#quick-start)

``` bash
pip install -e evennia
# =>
pip3 install -e evennia
```

**Comment by Griatch** [comment]
Is this when trying to install Evennia in the global system,  rather than in a virtualenv?

We could add what you suggest,  but if you use a virtualenv with the python3.7 interpreter (as per Getting Started) it doesn't matter what pip version you install with apt - once you are in said virtualenv you should get the py3 version of pip automatically ...

**Comment by spiralofhope** [comment]
I don't understand your terminology; I'm just following the quick start guide.

All I know is I needed to install pip3 myself to get through that step.

**Comment by Griatch** [comment]
The main question is: when you run that step,  is/was your virtualenv active (that is,  did it say `(vienv)` in your terminal)?

**Comment by spiralofhope** [comment]
yes, the `(evenv)` was there.

**Comment by Griatch** [comment]
I think this is a different error, namely that you are not using the right virtualenv, or one not using python3. There are so many different distributions and OSes covered here that we cannot cover the exceptions in the quick-start - if you have issues with the quick-start you must use the full install instructions. 

I added `python3-pip` package as a suggested on to `apt`, but I think it's wrong to use this from inside the virtualenv. Using pip3 rather than pip likely leads to the issue of not getting the `evennia` command available later (in another of your tickets), so it's most likely not a good idea. 

If you have a correct virtualenv with py3, using plain `pip` in there should be enough - it should be setup (within the virtualenv) to use py3 automatically.
