### ISSUE TITLE
[BUG] turnbattle tb_magic.py returns 'TypeError' when trying to learn a spell

### ISSUE THREAD

**Issue by virgildotcodes** [evennia/evennia#2026]
#### Describe the bug
Implemented the included turnbattle contribution, specifically tb_magic.py. When attempting to learn a spell in server, you get an error on line 789 in tb_magic.py:
`Traceback (most recent call last):
  File "/home/virgil/evennia/evennia/evennia/commands/cmdhandler.py", line 631, in _run_command
    ret = cmd.func()
  File "/home/virgil/evennia/evennia/evennia/contrib/turnbattle/tb_magic.py", line 789, in func
    if spell_to_learn not in self.caller.db.spells_known:  # If the spell isn't known...
TypeError: argument of type 'NoneType' is not iterable`

#### To Reproduce
1. Follow instructions to implement tb_magic.py magic system.
2. Reboot server.
3. Attempt to learn a spell, for example `learnspell heal`.

#### Expected behavior
Should have learned the spell and received the message: `"You learn the spell '%s'!"`

#### Environment, Evennia version, OS etc
         Evennia version: 0.9.0 (rev 0056b94)
         OS: posix
         Python: 3.7.5
         Twisted: 19.10.0
         Django: 2.2.9

**Comment by Griatch** [comment]
This does not appear to be a bug - you have just not applied any of the changes from the contrib's version of the Characater class to yourself. That is why the `spells_known` Attribute does not yet exist on you. Those changes apply when the Character is first created, in the `at_object_creation()` hook (see https://github.com/evennia/evennia/blob/master/evennia/contrib/turnbattle/tb_magic.py#L337 which is where this happens). Since your Character already exists, you must tell the system to re-run the hook. 

In game, you can do this on yourself like this: 

    update self 

If you have other created Characters you need to update them by caling the hook manually. You can do this in-game too, for example like this: 

    py from typeclasses.characters import Character; [char.at_object_creation() for char in Characters.objects.all()]

I'm closing this, if you have updated yourself and the error persist, let me know and we can re-open.
