### ISSUE TITLE
[BUG] Subclasses of DefaultObject cannot be found/manipulated if they evaluate to False

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2027]
#### Describe the bug
This is less a "bug" and more just documentation of strange behavior under certain conditions.

I extended some of the base methods on child classes of `DefaultObject` (`__bool__`, `__len__`, etc.), such that I could evaluate the "value" of an object by casting it to an `int`, its "weight" through `len`, or its "presence" through `bool` (high-level overview, but the point is that certain objects could be exclusively evaluated as numeric or Boolean values).

Things worked for a while; I could see new objects with `objects` and [sort of!] work with them in the Django interface-- but the first sign that something was wrong was that for certain child classes--not all of them!--the Django interface would not show what locks were set on the object, nor would it let me delete the object from the web interface. The button and field for both were simply missing for these classes.

I hopped onto the terminal to try to `examine` these objects closer, thinking it might be an idmapper issue or something screwing up during creation that was failing to set locks--though pulling the object from `ObjectDB` and looking at its properties showed locks were set normally. `examine` was failing, yielding object not found errors despite being given a dbref that resolved correctly via `ObjectDB`.

#### Additional context
It turns out many aspects of the Evennia codebase check the validity of objects by doing 
```
if obj: 
    # assume True
``` 
and at least one of the methods I overwrote returned null/zero-values when evaluated...so something I did made it so that despite being valid object instances, `obj`s of select classes would always evaluate to `False` by default and slip through many cracks.

As far as solutions go, it would be easiest to just...not do what I tried to do here, but given that the entire framework is Django-based it would also behoove us to check for the existence of `obj.id` when determining the validity of an object-- non-persistent models are not supported, so it will *never* resolve to a `null`/`False` value (the `search` functions are pretty bad about this, as most commands rely on them).

Making `__bool__` on one of the parent classes return `True` if an id exists and `__int__` returning the id itself might also help mitigate silly situations like this one.

**Comment by Griatch** [comment]
There are side effects of such a change, because the Typeclass system does allow for things like 
`obj = Typeclass(...)`, in which case no '.id` will exist until its `.save()` method was called. Furthermore, just recently there _have_ been efforts to dynamically replace ObjectDBs with dynamic in-memory objects for non-persistent stuff. It actually works quite well due to duck-typing. 

But overall what this would do is to create a new, custom "falsy" entity in Evennia. I'd say it'd very confusing to have an object that is clearly not itself `False` or `None` fail a check like `if obj`. 

There are a few points (especially during the Typeclass initialization) where checking that `.id` is set really matters, but those points should be explicit anyway for readability. Otherwise, this is just what the Typeclass system should be handling for you. 

So no, this is not a change I'm endorsing. I'm closing this, I can open again if you want to discuss further.

**Comment by strikaco** [comment]
Fair enough. I'm also encountering other gotchas where (I think?) one of the iterator methods is used to poll object contents (`if something in container`).

I think the lesson learned here is that the magic methods should not be touched and that doing so may lead to very random and hard-to-diagnose side effects.
