### ISSUE TITLE
[BUG] Logs no longer rotating

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#2041]
#### Describe the bug
portal.log and server.log are not rotating and growing infinitely large.

#### To Reproduce
1. run game
2. ls -al ./server/logs
3. see 10 meg portal/server logs

#### Expected behavior
The log files to rotate and append old versions to them as previous.

#### Environment, Evennia version, OS etc
Evennia version: 0.9.0 (rev 9649295)
         OS: posix
         Python: 3.8.1
         Twisted: 19.10.0
         Django: 2.2.9

#### Additional context
Also had my shell session crash upon trying to tail the server log and getting garbage characters after a game freeze. Still have no idea what's in there.

**Comment by Griatch** [comment]
@TehomCD I've not investigated further, or tried to reproduce - but could this be related to the old https://github.com/evennia/evennia/issues/1758 somehow, maybe?

**Comment by Griatch** [comment]
@TehomCD So when I dug into this further, it turns out that the Twisted DailyLogger, which I based my WeeklyLogger mechanism on, _is not persistent_. That is, it will count its days-until-cycling based on how long it was the file was first opened for logging. In other words, when you reload (for server log) or reboot (for server + portal logs), the time is reset. I imagine you have done a lot of restarting and rebooting of Arx lately as part of getting the server to evennia 0.9 ...

What I have done now is that I have extended the logger to also look at the size of the file. The default is 1MB, after which it will automatically cycle. If this happens more than once in a day, additional log files will have an additional suffix `__1`, `__2` etc. 
I have also made this controllable from settings, via the new `SERVER_LOG_DAY_ROTATION` and `SERVER_LOG_MAX_SIZE` settings (and equivalent for portal too). Check it out!
