### ISSUE TITLE
[Documentation] Filenames are illegal on Windows system

### ISSUE THREAD

**Issue by blackmonkey** [evennia/evennia#2062]
#### Documentation issue
When I cloned repository evennia.wiki on Windows 10, git reports the following modifications:
```
# git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    Tutorial:--Aggressive-NPCs.md
        deleted:    Tutorial:--NPC's-listening.md
        deleted:    Tutorial:--Vehicles.md
        deleted:    Tutorial:-Searching-For-Objects.md
        deleted:    Tutorial:-Tweeting-Game-Stats.md
```
Since the colon is not allowed to be used in Windows file names, the above files are removed after clone.

And there are double dashes in the first three file names.

#### Suggested change
- Please remove the colons from the file names.
- Please replace double dashes to one.

**Comment by Griatch** [comment]
These are auto-generated file names based on the wiki titles. I would have expected Windows to use `\` to escape that ...

**Comment by blackmonkey** [comment]
Could you please rename these wiki titles like "Tutorial-World-Introduction.md"? I'm trying to study the wiki pages, but they are updated frequently. Then I realized that I can focus on certain revision of the wiki repository. And when I finish reading all the pages, I can check the latest changes from git logs. And I'm sorry that I am a Windows user.

**Comment by Griatch** [comment]
@blackmonkey We'll try to do that, it's not necessarily trivial since we would need to update all links as well (but not too difficult either).

(It is still curious that we would _have to_ though; for example, Linux does not like spaces in file name display, but it makes sure to escape them automatically so they still work. I'd have expected for git and the Windows console to do the same, regardless of the file name and what is allowed in it.)

**Comment by Griatch** [comment]
@blackmonkey The file names and links were converted. Check it out! I'm closing this, if you find any further problems, make a comment in this thread and I can reopen again.
