### ISSUE TITLE
[Documentation] evennia migrate / remove it, handle it, or document it?

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2077]
#### Documentation issue
griatch: "lets write 400,000 lines of code that makes them never have to touch the database!"
also griatch: "but lets have them run database commands as the first thing they do after installing!"

#### Suggested change
New users think "migrate" is a regular part of their evennia workflow. How should we make them think its not?

**Comment by Griatch** [comment]
Well, it needs to be a part of their workflow - it is how you update your database if we make any upstream changes. Because I'm in bug-fixing mode right now there have been no such changes lately, but with a new version there will definitely be. 
We can't really automate it on first startup either, since once you initialize your game-dir you may want to tweak the just-created settings file to use another database than the default - so `evennia migrate` needs to be a separate step. 

Do you have any suggestions as to what should change?

**Comment by trhr** [comment]
The docs refactor addresses this by splitting out sections on initial setup, upgrading the server, and reloading the server. Describing each of these processes separately likely addresses the question of where the dev-loop starts; code-reload-code-reload instead of code-migrate-reload-code-migrate-reload.
