### ISSUE TITLE
[BUG] bug in system 'scripts' command

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2117]
![image](https://user-images.githubusercontent.com/5786272/80076657-1e270280-8512-11ea-92d7-e4ff04c8e51a.png)

get_all_scripts() returns a list, but .exclude() is a queryset function.

**Comment by Griatch** [comment]
Ah, `get_all_scripts` should return a queryset; that's a bug indeed.

**Comment by Griatch** [comment]
Looking at it, `get_all_scripts()` with no arguments would in fact always return a queryset and not a list, so the particular example above seems incorrect. However, as part of investigating this it's clear that calls with a dbref argument _would_ have returned a list instead of a queryset. This has been fixed now. Closing.
