### ISSUE TITLE
[BUG] Default tests assume mygame level functions weren't overloaded

### ISSUE THREAD

**Issue by trhr** [evennia/evennia#2130]
#### Describe the bug
'evennia test evennia' tests, e.g. TestAccount, fail when functions like return_appearance have been overloaded at the mygame level

#### To Reproduce
1. Overload return_appearance in mygame.typeclasses.characters.Character to return arbitrary string
2. Run tests

#### Expected behavior
Evennia Test should not be testing against mygame classes, as there's no guarantee that mygame returns an appearance in the same format that the test expects

**Comment by trhr** [comment]
Looks like it might be localized to CommandTests.

- test_char_create calls account.CmdCharCreate and expects a return of "Created new character Test1..."
- But CmdCharCreate creates a character of mygame's base character typeclass
- mygame's character typeclass create doesn't necessarily return a string of "Created new character Test1..."

**Comment by Griatch** [comment]
While I agree in principle, checking and reworking tests for this is quite an undertaking; there are a lot of possible places where one would need to mock out the command call to make it use the vanilla version of the class. So this is potentially a pretty big project. 

At least at this time, the `evennia test evennia` tests are expected to run from a 'clean' gamedir; whereas game dirs with their own unit tests should be run with the `evennia test --settings settings.py`.

**Comment by trhr** [comment]
Related: the .call() command tests against a parameter, msg, which is a string resulting from the outputfunc "text" - e.g. what is shown on the screen. This doesn't support OOB testing.

I'm guessing a Mock.assert_called_with() solves both issues.

**Comment by Griatch** [comment]
The intent of call is to mimic text input from a user and run the associated command through the cmdhandler, something inherently tied to the `text` inputfunc.  The method also makes all sorts of assumptions about the resulting command.  

One would need to make separate helper methods for other types of inputfuncs in order to test OOB in this way, extending the `.call` is not suitable. 

Closing this - we will not mock all commands to account for any overrides in a non-vanilla gamedir and we won't be updating the .call to account for arbitrary OOB messaging. Most likely OOB testing would be customized per input type anyway.
