### ISSUE TITLE
[Feature Request] Expose INLINEFUNC_STACK_MAXSIZE in settings_default

### ISSUE THREAD

**Issue by awranthyr** [evennia/evennia#2173]
#### Is your feature request related to a problem? Please describe.
The INLINEFUNC_STACK_MAXSIZE setting is currently a bit of a hidden setting, existing only in the inlinefunc module itself.

#### Describe the solution you'd like
Add the setting to the default_settings module, so that new users will have a better chance of knowing it exists.

**Comment by Griatch** [comment]
The original reason for 'hiding' this is because there is really not that much reason to change it for the average user; disabling the limit is not a good idea for infinite-recursion reasons. But I can see the point of making it visible in `settings_default` when it's nevertheless available. So added it now.
