### ISSUE TITLE
[BUG] Reload resets the LOGIN_THROTTLE_LIMIT

### ISSUE THREAD

**Issue by TehFamine** [evennia/evennia#2223]
#### Describe the bug
I believe it's the login throttle limit, but whatever prevents a single connection (e.g.: same IP address) from creating more than a couple accounts can be circumvented by simply waiting for the MUD to reload. While this may seem silly, the point of the setting is to prevent a single IP from creating multiple accounts. Reloading seems to reset the count so if you restrict a single IP to only having 2 accounts, the reload means you can now create 4 of them.

#### To Reproduce
1. Create 2 accounts (think default throttle is 2)
2. Wait for a game reload / force a crash
3. Create 2 more accounts above the throttle

#### Expected behavior
Would expect the throttle to be persistent.

#### Environment, Evennia version, OS etc
If unsure, run `evennia -v` or get the first few lines of the `about` command in-game.

#### Additional context
This is not a huge issue, but still seems like a bug because you would expect the setting to be persistent across reloads.

**Comment by strikaco** [comment]
https://github.com/evennia/evennia/blob/367db031fa9e5727c3fbf90e624ab06bd9b6f82f/evennia/accounts/accounts.py#L54-L56

The throttle was never meant to be persistent or to permanently block anything-- only to *slow down* mass account creations. It resets itself automatically after some period of time, no reload necessary.

Until the world at large adopts ipv6, you really don't want to have a system in place that auto-bans ipv4 addresses for long periods of time anyway. It can be exploited to block/DoS other users in the same address pool (i.e. NATted users on mobile networks).

**Comment by Griatch** [comment]
@strikaco I don't think @TehFamine meant that the throttle should be persistent-persistent (as in blocking forever) but rather that it should not be auto-timing out across a reload ...

I can see the argument for consistency, but not sure it's worth the effort to implement ...

**Comment by strikaco** [comment]
> - While this may seem silly, the point of the setting is to prevent a single IP from creating multiple accounts. 
> - Reloading seems to reset the count so if you restrict a single IP to only having 2 accounts, the reload means you can now create 4 of them.
> - Would expect the throttle to be persistent.

@Griatch I did get the impression that the expectation was to hard-limit the number of accounts created per IP.

The throttle _could_ be refactored to use Django's cache instead of an internal `dict`-- and defines a "throttle" cache definition in `settings` that uses in-memory storage and brief TTLs by default (and which will continue to purge on reloads), but the user can override it to stipulate ten-thousand-year TTLs and on-disk storage. Then one would have persistent throttling across reloads to whatever extent they wish to suffer the additional overhead.

That would be a refactor for its own sake though, with the side-effect of enabling persistence.

**Comment by Griatch** [comment]
This was closed in `develop` branch, closing this issue.
