### ISSUE TITLE
[BUG] typeclasses used for prototypes that reference dice unable to find default_cmds

### ISSUE THREAD

**Issue by RianeNelson** [evennia/evennia#2232]
#### Describe the bug
When using a typeclass that imports/uses dice as a prototype for spawnable objects, evennia is unable to find 'default_cmds' in the evennia dice file.

#### To Reproduce
1. Create/edit a prototype file (I have `world.mob_prototypes_sithesia`)
1.  Create a typeclass that uses dice (I have mobs.Cmob for example) and make so that it has `from evennia.contrib import dice`
2. Create a prototype that inherits from this typeclass (I have `AGGRESSIVE_MOBS` with `"typeclass" : "typeclasses.mobs.Cmob"`
3. Ensure `PROTOTYPE_MODULES += ["world.mob_prototypes_sithesia"]` is in settings.py, reload evennia.

#### Expected behavior
Expected to simply be able to spawn 'aggressive_mobs' member. Instead I get the below error:

```
File "...mygame\world\mob_prototypes_sithesia.py", line 11, in <module>
    from typeclasses.mobs import Cmob
  File "...mygame\typeclasses\mobs.py", line 2, in <module>
    from typeclasses.characters import Character
  File "...mygame\typeclasses\characters.py", line 15, in <module>
    from evennia.contrib import dice
  File "...mygame\evennia\evennia\contrib\dice.py", line 125, in <module>
    class CmdDice(default_cmds.MuxCommand):
AttributeError: 'NoneType' object has no attribute 'MuxCommand'
```

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev 51b93c588) (rev 51b93c588)
    OS: nt
    Python: 3.8.2
    Twisted: 19.10.0
    Django: 2.2.12

#### Additional context
Also tried this in just the generic 'prototypes.py' file rather than my custom file, same error.

**Comment by Griatch** [comment]
This is a side effect of how how we must initialize Evennia and how Python package loading works. If you look at the main `__init__.py` file of Evennia (the 'flat API') you'll find that all its properties start out set to `None` until that file has been run through fully. What happens here is that your prototype file gets imported as your game dir initializes, and since your `dice` import is at the top, it pulls in `dice`, which in turn pulls in `default_cmds` from `__init__.py`, which at that point has not yet initialized and is still set to `None`. 

The solution to this is for now to make a delayed import of dice. Normally this is done my simply moving your `import` statement outside the global scope (so not in the 'root' of your module) and only fetch it when you need it: 

```
def myfunction(...):
     from evennia import foo

     foo()
```
Since the function will not fire immediately upon import of the module, `evennia.__init__` will have time to properly initiate and `foo` (or `default_cmds`) will have had time to be set to their correct values. 

You can't do an `import` inside a `dict` though (inside your prototype), so for this you need to be a little trickier in order to do a delayed load: 

```
def get_dice_module():
    from evennia.contrib import dice
    return dice 

MY_PROTOTYPE = {
    "key": ...
    "health": get_dice_module().roll_dice("2d6")
}
```

Now, this is obviously not ideal - it's a known issue that we haven't really figured out how to solve better at this point. I'll keep this issue open since it's a good example of this particular import issue; maybe we can change the load order around or try some other solution to make it harder for mygame-code to butt in on the load order.

**Comment by RianeNelson** [comment]
Ah, that totally makes sense. The one question I have then, if my prototype typeclass is mobs.Cmob and it's Cmob that's needed the dice, is there a way to properly import the dice -before- the typeclass? The dice are used in some basic functions in Cmob so I'm not sure how to go about importing the dice into the prototype itself. Unless I should just remove any mention of it from the Cmob class and somehow stuff all the functions in the prototype for... reference? I'm not sure how to go about it.

**Comment by Griatch** [comment]
If you are using db-based prototypes or are using the dice module inside your typeclass, just delay the import of `dice` in your typeclass module by importing it when you need it rather than at the top of your module.

**Comment by Griatch** [comment]
A change in the way prototypes are loaded resolved this particular issue.
