### ISSUE TITLE
[BUG] Badly-formatted typeclass attributes involving `dicts` not being stored during construction

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2236]
#### Describe the bug
I was trying to construct an object using an invalid Attribute tuple, which led to some unexpected and unpredictable behavior.

When a bad tuple containing a `dict` object is passed as an Attribute to a typeclass constructor, no errors are raised and the value stored is serialized as either an empty `dict` or `None`.

Not sure if any other classes are impacted; I noticed this on scripts in particular.

#### To Reproduce
```
from evennia.utils.test_resources import EvenniaTest
from evennia import DefaultScript


class AttributeSaverDictTest(EvenniaTest):
    
    def get_template(self):
        return {'name': None, 'rank': None, 'serial': None}
    
    def test_broken(self):
        blob = self.get_template()
        script, e = DefaultScript.create(
            'script1', 
            attributes=[
                ('blob', blob, '', ''), # INCORRECT SYNTAX! Last item should be boolean
            ]
        )
        self.assertTrue(script)
        self.assertEqual(blob, script.db.blob)
```

#### Expected behavior
Raise an error (ideally), or try to resolve the last value as `bool` and continue that way (should be `False` in my case).

As it stands I have no idea what this is being interpreted as.

#### Environment, Evennia version, OS etc
```
Evennia 0.9.5 (rev 417520d) (rev 417520d)
    OS: posix
    Python: 3.7.9
    Twisted: 20.3.0
    Django: 2.2.12
```

**Comment by Griatch** [comment]
Yes, this sounds like it should be verified better.

**Comment by Griatch** [comment]
Looking at this further, this is a user-error. The format for the attribute tuple is 

    (key, value, category, lock, default_lock_bool)

where everything after `(key, value)` is optional, but must be added in that sequence - so in your example you are setting `('blob', blob, '', '')`, that is, a category of `''` and an empty lockstring. A category other than `None` (the default) will not be picked up by `script.db`. 

(And as far as I can tell, having `''` instead of `False` works fine for the default-lock-bool tuple component too)

That said, I did find a discrepancy when trying to use `script.attributes.get("blob", category="")`. This has been fixed. This is otherwise how you must retrieve this particular attribute, and not by using `.db`.
