### ISSUE TITLE
[Feature Request] Provide a way to exit 1 from at_server_startstop.py

### ISSUE THREAD

**Issue by jerryaldrichiii** [evennia/evennia#2240]
#### Is your feature request related to a problem? Please describe.
I'm attempting to automatically do some world building during server startup. The issue is, I can't find a way to have commands like `evennia start` or `evennia istart/ipstart` exit 1 if any errors are encountered during the various startup functions in `at_server_startstop.py`.

#### Describe the solution you'd like
What I would like is that there be way to cause a command like `evennia start` to exit 1 if any errors encountered in `at_server_startstop.py`.
 
#### Describe alternatives you've considered
As a workaround I was able do something like this:

```python
# server/conf/at_server_startstop.py
...
def at_server_start():
    """
    This is called every time the server starts up, regardless of
    how it was shut down.
    """
    try:
        create_rooms()
    except Exception as e:
        print(e)
        # This will cause the server fail to start then I can 
        # `evennia status | grep 'NOT RUNNING'` during CI tests
        sys.exit(1)
```

**Comment by Griatch** [comment]
I looked into this, but it's not a very easy thing to add. The reason is that the `evennia` program is just a remote client that launches the Evennia portal/server. It can, and often do, run independently of the server/portal processes. 

One could build some infrastructure to have the server report (through the portal) if it hits on a traceback, but overall this will not kill the server but just be logged. To implement this seemingly simple feature would mean introducing some custom status to be passed from the server to the portal and then on to the launcher, just so that it can know to stop itself with a 1 or 0 result. Not to mention that something like `sys.exit(1)` messes with Twisted's process management as well. 

So at this time I don't know really of a clean way to support this functionality, unfortunately. It's not something that will be appearing in the short-term at least. 

In #2240, I have improved the logging of errors over the AMP bridge; this should at least go a long way towards seeing detailed errors such as a traceback from the `at_server_start` module.

**Comment by jerryaldrichiii** [comment]
No worries @Griatch. FWIW, it's good to know it wasn't as easy as it seemed. I tried...and failed quite a few times.

Thanks for taking a look!

**Comment by Griatch** [comment]
@jerryaldrichiii I quick and dirty solution may be to monitor the server/portal log for the term `Traceback` during upstart, now that this should properly appear in the log. It's not pretty, but you could respond to it appropriately.

**Comment by jerryaldrichiii** [comment]
Yeah, I think that is cleaner than grepping for "NOT RUNNING" in `evennia status` because the server can take a bit to start up. I'll give it a shot tonight, and if it works I'll update my workaround above. Thanks!

**Comment by Griatch** [comment]
Also `[EE]` (similarly to syslog tags) could be looked for.

**Comment by Griatch** [comment]
The initial proposal for this does not work, and a workaround was found, so closing.
