### ISSUE TITLE
[BUG] TagHandler has() method not working.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2263]
#### Describe the bug
Every time I use an if statement to check if an object has a tag,
[Example Code](https://github.com/kovitikus/hecate/blob/1c662df00da19a2e6e4a8dad87e21dab33280465/world/general_mechanics.py#L150)
```py
if obj.tags.has('stackable'):
```
it gives me an error.
`AttributeError: 'TagHandler' object has no attribute 'has'`

#### To Reproduce
1. Add an if statement to check if an object has a tag.
2. See error

#### Expected behavior
It seemed to work before, after the TagHandler had the `has()` method added. But it sure as heck don't work now. This is the second attempt I've made in recent days to use the `has()` method and getting the same error.

#### Environment, Evennia version, OS etc
    Evennia 0.9.5 (rev 9d90b5226) (rev 9d90b5226)
    OS: nt
    Python: 3.7.4
    Twisted: 20.3.0
    Django: 2.2.16

**Comment by kovitikus** [comment]
I swear I'm not insane. The TagHandler has() method seems to be missing entirely?

https://github.com/evennia/evennia/blob/master/evennia/typeclasses/tags.py#L99

It was clearly added previously: https://github.com/evennia/evennia/pull/2210

**Comment by Griatch** [comment]
This was added to `develop` branch, yes, so if you have been using `master` branch you could not have used this before. 

While we were a little lax with this rule in the last months leading up to the release of 0.9.5, _in general_, `master` is for bug fixes of existing features and new features go into `develop` branch. Since this PR was made properly against `develop`, that's where it ended up. I'd be reluctant to start backporting development features to `master` at this point. This  was added as part of the api cleanup for api consistency with AttributeHandler. You can get a similar effect with `obj.tags.get(tagname)`, which is why `.has` was not in the original spec in the first place.
