### ISSUE TITLE
[BUG] sdesc parsing in rpsystem contrib

### ISSUE THREAD

**Issue by alephate** [evennia/evennia#2265]
#### Describe the bug
An inordinate amount of lag (and at one point, a droplet server completely crashing) when sending contrib rpsystem emotes around objects that don't have sdescs and have a lot of aliases. This was predicted in the comments by the function: regex_tuple_from_key_alias

Running the profile on a clean evennia install also showed all the time going into this problem.

#### To Reproduce
1. install evennia with rpsystem contrib
2. create a lot of objects and exits with lots of aliases
3. perform emotes in that room

#### Expected behavior
ContribRPObjects and base Evennia exits to work smoothly with the rpsystem.

#### Environment, Evennia version, OS etc
0.9.5
#### Additional context

The ContribRPObject class doesn't have sdescs, so even when inherited from for created objects and exits, it doesn't solve the problem. I solved the problem in my own version of the rpsystem by adapting ContribRPObject to have sdescs like so:

https://pastebin.com/qHuK6v51

**Comment by Griatch** [comment]
I implement a cache for `regex_tuple_from_key_alias`. This leads to a speedup of ~1000 times when a regex has been calculated once (once per server reload), while still allowing for dynamic changes. This should improve performance a lot since these regexes don't need to be recalculated unless the object itself changes key/aliases.
