### ISSUE TITLE
[Documentation] Develop branch invading the 0.9.5 API

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2287]
#### Documentation issue
Both the [API](https://www.evennia.com/docs/latest/api/evennia.objects.objects.html#evennia.objects.objects.DefaultObject.contents_get) and the [source](https://www.evennia.com/docs/latest/_modules/evennia/objects/objects.html#DefaultObject.contents_get) entries for `evennia.objects.objects.DefaultObject.contents_get()` method are showing the parameter `content_type`, despite that feature not yet existing in the master branch yet.

**Comment by Griatch** [comment]
It looks like the doc builder picks up the rST files from whichever branch the build starts from (so running it from `master` branch will conversely have the develop-branch docs show the `master` version of the API. Some wires got crossed in the build process there it seems ...

**Comment by Griatch** [comment]
Man, this was a tricky one. As it turns out this is an issue with `sphinx-multiversion` itself. The issue comes down to caching of python packages within a subprocess. I have fixed this locally (including a bunch of other needed rewrites) and made [a new upstream issue](https://github.com/Holzhaus/sphinx-multiversion/issues/69) against the `sphinx-multiversion` builder.
