### ISSUE TITLE
[BUG] DefaultObject.msg_contents() sends message to all the contents, including objects and exits

### ISSUE THREAD

**Issue by blackmonkey** [evennia/evennia#2294]
#### Describe the bug
During running my own test cases, I found that DefaultObject.msg_contents() sends the message to all the contents, including objects and exits. This is unreasonable. Normally, the message should be only sent to characters (NPC or PC). If we want a player to interact with objects or exits, we should define concrete commands instead of sending messages.

#### Expected behavior
In default, DefaultObject.msg_contents() should only send messages to instances of DefaultCharacter and its subclass. If it is necessary to keep the current behavior, it is better to add a kwarg to shut it down.

#### Environment, Evennia version, OS etc
Evennia 0.9.0 (rev 50a667daa) (rev 50a667daa)
OS: nt
Python: 3.7.0
Twisted: 19.10.0
Django: 2.2.13

**Comment by kovitikus** [comment]
It's not a bug and it's not unreasonable. You can exclude objects from the msg_contents() method by supplying the kwarg `exclude=[list, of, objects]`.

**Comment by strikaco** [comment]
Yeah seconding the status quo not being unreasonable. 

Aside from sending text messages to characters, it can also be used to pass non-text "messages" (signals) to any form of object. It's a very flexible broadcasting system as implemented.

**Comment by blackmonkey** [comment]
> It's not a bug and it's not unreasonable. You can exclude objects from the msg_contents() method by supplying the kwarg `exclude=[list, of, objects]`.
> 
> I'm curious why it even matters to you that messages are sent to inanimate objects in the room? It doesn't hurt anything.

Indeed it doesn't hurt anything. But to specify `exclude=[list, of, objects]`, I need to enumerate the contents first. But if I enumerate the contents, I can directly send the message during enumerating, why would I invoke msg_contents() in this case?

**Comment by blackmonkey** [comment]
> Yeah seconding the status quo not being unreasonable.
> 
> Aside from sending text messages to characters, it can also be used to pass non-text "messages" (signals) to any form of object. It's a very flexible broadcasting system as implemented.

I understand that msg_contents() can be used to send signals either. That's why I suggest to add a kwarg, e.g. `only_chars=True`, to only broadcasting text messages to characters in the same room, which make msg_contents() more flexible.

**Comment by kovitikus** [comment]
I dunno man. I just send my message to all the objects. It doesn't harm anything for the message to be received by objects that does nothing with it, and no sessions puppeted to the object. It's a shortcut, allowing you to broadcast a message to the contents of an object (room) without having to iterate through the contents and send it out one at a time.

 Sure, you can iterate through all of the objects in the room and send one message at a time to objects that you want, or add objects you want to exclude to an exclusion list, but what's the point?

The real reason for exclude is to send out a different message for the same outcome.

As such, you could have a message saying.

`You look through the window.`

and only send this message to the person who calls the command `look window`.

But then you could have another message you send out to all other objects in the room that says

`John looks through the window.`

and in this one you would exclude John, because he gets his own message specific to his experience. The `You` message.

If the window object or the exit object or even a cabinet gets the message `John looks through the window.`, it does nothing to them, cause there's no session attached to those objects to see this message. I'm no expert, but I highly doubt it's significant to performance either.

I don't get why you are trippin' on something that ultimately doesn't impact the outcome of your interactions. Why do you care if a message gets sent into a void?

**Comment by kovitikus** [comment]
> I understand that msg_contents() can be used to send signals either. That's why I suggest to add a kwarg, e.g. `only_chars=True`, to only broadcasting text messages to characters in the same room, which make msg_contents() more flexible.

The problem with adding an `only_chars=True` is that character typeclasses are different across projects. I highly customized my character typeclass, and there's not even any rule-of-thumb that tells me I have to make a character that inherits from `DefaultCharacter` or create a `Character` typeclass at all. Don't get me wrong, there's some useful stuff in [DefaultCharacter](https://www.evennia.com/docs/latest/api/evennia.objects.objects.html#evennia.objects.objects.DefaultCharacter), but it's really just an extension of DefaultObject and I could decide to write my own Character typeclass from DefaultObject.

**Comment by davewiththenicehat** [comment]
For people reading this post during a search or looking for solutions. I recommend against omitting messages to objects. This is intended for this specifically for Blackmonkey's requirements.

You could overwrite your Objects', Exits' and Rooms' at_msg_receive to just return False. That will cause those object types to never handle a message after receiving.

You could instead overwrite msg_contents, to use [inherits_from](https://evennia.readthedocs.io/en/latest/Coding-Utils.html#utils-inherits-from) to not send to all objects that inherit from your object class (probably typeclasses.objects.Object), Than do the same with exits and rooms. It is possible for a room to contain a room.

**Comment by kovitikus** [comment]
Agreed. Write a simple function that grabs the contents of a location, filter through them to create a list of objects that do not inherit from `Character` typeclass and then send out a msg_contents, excluding non-Character objects.

```python
def msg_chars(msg, location):
    non_chars = []

    for i in location.contents:
        if not i.is_typeclass('typeclasses.characters.Character'):
            non_chars.append(i)

    location.msg_contents(msg, exclude=non_chars)
```

Now all you have to do is call msg_chars and provide it the message and the location.

**Comment by blackmonkey** [comment]
> ... I'm no expert, but I highly doubt it's significant to performance either.

I agree and understand all you mentioned. And I also

**Comment by blackmonkey** [comment]
Thank you for all your good advice! I've overridden `msg_contents` to only broadcasting messages to characters.

@kovitikus I'm trying to not do unnecessary things on the server. Receiving a message then output nothing has the same UE as not-receiving the message at all, while the former costs a little bit more than the latter for each message.

And yes, I didn't realize that we can create a brand new Character class from default ones.

Btw, `msg_contents` also enumerates the contents. Therefore, figuring out the value for parameter `exclude` then invoking `msg_contents` will enumerate the same contents twice.

@davewiththenicehat Sure, as a global framework, Evennia shouldn't support any specific requirements.

**Comment by kovitikus** [comment]
You are prematurely optimizing something that isn't even posing a risk of bogging down your performance. This is a significant flaw in your approach to coding.

Don't obsess over what-ifs. If you have solid proof that something like `msg_contents` is causing you to have serious performance issues, then you can think about finding another solution or opening a ticket about it. Right now, you're just quibbling over theoretical performance.

I say this to you because it isn't a healthy use of your time or energy to concern yourself over something like this without any certainty that it's actually an issue.

**Comment by duysqubix** [comment]
until it does become an issue and spent countless hours figuring out why. can see the other side of the coin.
