### ISSUE TITLE
[BUG] systemd service doesn't start the server

### ISSUE THREAD

**Issue by TwistedBlizzard** [evennia/evennia#2307]
#### Describe the bug
The Systemd .service file included with evennia doesn't start the service as it fails to find the twitd executable. The script then fails but the service continues running.

#### To Reproduce
1. Copy the default service file from the evennia folder.
2. Edit the file with the correct paths.
3. Enable and start the service using systemctl.
4. Service acts like it is running but it has crashed in the background.

#### Expected behavior
Both the webserver and telnet server should be running under the service.

#### Environment, Evennia version, OS etc
Evennia version 0.9.0 (rev 69fd31d4)
OS is Ubuntu 20.04.1 running on Proxmox
Python version 3.8.5
Twisted version 19.10.0
Django version 2.2.17

#### Additional context
This issue can be solved by adding the following line to the evennia.service file:
`Environment="PATH=/path/to/evenv/bin"`

**Comment by duysqubix** [comment]
It seems that when starting this service, python twisted library utilizes a binary called `twistd` conveniently located in `/path/to/venv/bin/twistd`. Upon starting a service the `twistd` isn't in the default `PATH` which is why the above can be fixed using the directions from Additional context. 

@Griatch, unless you object. I will simply add the above line to the service file and create a PR.

**Comment by Griatch** [comment]
> @Griatch, unless you object. I will simply add the above line to the service file and create a PR.

@duysqubix systemd expects Twisted to be installed globally, not in the virtualenv. The venv is not running when systemd is starting, hence the path is not set up. 

We can add the envvar addition (as a connected-out line),  sure, but the doc page for systemd should be updated too.

**Comment by Griatch** [comment]
Looks closed in PR above.
