### ISSUE TITLE
[BUG] Django (default) in-memory cache hangs server on run_async functions

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2333]
#### Describe the bug
The Django in-memory cache (`LocMemCache`) is supposed to be thread-safe, but hangs the server when accessed from a thread spawned by `run_async`.

#### To Reproduce
Pseudocode:
```
def do_stuff():
    cache.set('foo','bar')
    return cache.get('foo')

class CmdDoStuff(Command):
    def func(self):
        run_async(do_stuff)
```

This problem does not seem to occur with disk-based caches. 

Have not tried with database-backed (though expect similar behavior if the server and cache share the same sqlite db).

#### Expected behavior
`LocMemCache` is presented as thread-safe. Twisted deferreds are supposedly "threads", not "processes," so it should not hang under these conditions.

#### Additional context
Having ported this particular cache class to other non-Django projects, I think the problem here is the method of locking being used by the cache. The file-based cache locks the file using some sort of custom Django file lock and works across async requests, but the in-memory one uses locks from the `threading` library which (I'm guessing) are not being acquired or released properly by child Twisted threads. 

https://github.com/django/django/blob/876dc0c1a7dbf569782eb64f62f339c1daeb75e0/django/core/cache/backends/locmem.py#L5-L29

I have minimal grasp of parallel computing and no understanding of Twisted whatsoever, so have no idea where to even begin trying to "prove" this theory short of modifying the problematic class itself.

* Implementing a custom LocMemCache that mirrors the parent but omits the lines pertaining to locks, then setting that as the default Django cache would likely solve the problem (the LocMemCache _without_ locks would look and operate very similar to the NDB handler).
* Alternately, replacing the locks from `threading` with those from `multiprocessing` might work (have not tried).
* If a subclass of `LocMemCache` implemented Evennia's custom pickle/unpickle methods as well, it would solve some other annoyances related to serialization.

**Comment by strikaco** [comment]
Defining a custom `LocMemCache` and replacing `threading.Lock` with `threading.RLock` seems to make this work.

**Comment by strikaco** [comment]
Spoke too soon. Still hitting deadlocks when two child threads both try to access the cache.

**Comment by strikaco** [comment]
Removed locking steps from the cache class altogether; this time things seem more stable. Will continue testing.

**Comment by Griatch** [comment]
I thinks this comes from a misunderstanding of what a Twisted deferred is. A deferred does _not_ spawn in a new thread (and even if it did, in-process threading is of limited use in Python because of the Global lock (GIL)). 

All async code (like that of Twisted) operates in the same thread, it just quickly moves around in the stack to make it feel like everyone on the server can do things at the same time - all code is however in reality synchronous. In effect you are limited by the CPU speed. True parallelism is only achieved on I/O operations - and even then we need to block on DB interactions (in this case because of how Django works). I think this is why you see this working with a disk-based cache - depending on cache, it may be set up to not block. Most likely Django's in-memory cache is running the same thread and if there are locks, you will block the entire server until you release the lock. So this is not surprising.

I'll close this, I don't think it's an Evennia problem.
