### ISSUE TITLE
[Feature Request] Add a means to pass rooms across environments

### ISSUE THREAD

**Issue by TehFamine** [evennia/evennia#2335]
#### Is your feature request related to a problem? Please describe.
To put it simply, yes. The problem is being able to safely and effectively pass content such as rooms across environments such as Develop, Staging, and Production.

#### Describe the solution you'd like
Evennia needs a way to export rooms as areas to a file that can be loaded and unloaded from the database at will. The files act as a vehicle that can be passed across environments without a backup of the database. 

#### Describe alternatives you've considered
Other features would be to take a backup and load it.

#### Additional context
Evennia already has a Room typeclass. The suggestion on the table is to by default add at least a _Area_ attribute to rooms and encourage users to group rooms by areas or provide a default value that can be configured in the settings.py file.

Almost all rooms in almost all games will be tied to a physical grouping just as almost all rooms need exits. If you enforce physical groupings of rooms to the _Area_ attribute, then you can easily create an export function either as a batch file of commands or some type of Evennia area syntax that can easily load and unload areas between environments without having to force us to create backups of critical database information or encourage inexperienced users to commit their database backups or files to version control, which is not recommended.

Simply put, there needs to be a better way out the box to pass content across environments. Due to the bare bones nature of Evennia, it's not really easy to do that. Builders should be encouraged to build using Evennia commands online in a developer environment and then an admin should have a means to export what they built to a file so it can be passed and loaded in production after testing/staging.

Furthermore, exporting areas to files allows those files to be committed to version control similar to how database developers would take stored procedures, that are saved to the database server and in the backup of the database file, to export the code/syntax/script to a file, and then commit that file to version control. These days, especially referencing SQL Server, you can commit database objects to version control with like Team Foundation. We need similar to Rooms.

**Comment by Griatch** [comment]
There are a lot of variations to objects that would make it less than trivial to do this in a general sense. Also, copying _partial_ database content over (especially as this is likely to be done repeatedly as you develop/fix bugs etc) is _very_ susceptible to errors - things like  you having changed something (seemingly trivial) in one way in staging that was changed differently in prod, leading to an accidental overwrite. There are a truckload of very confusing (and worse - subtle) errors to come from this and little chance to revert them safely. 

There is a recommended way to copy resources with version control and that is to put the _instructions for how to build things_ into version control. That is, by using Evennia's in-built [batchcmd/batchcode](https://www.evennia.com/docs/latest/Batch-Processors.html) files/system.

For copying database content like this, I'm not sure this would be as much of an Evennia as as a Django/database feature. Maybe something like [Django smuggler](https://github.com/semente/django-smuggler) could be useful?

**Comment by TehFamine** [comment]
I'm not sure I follow what you are saying. If you recommend using the [batchcmd/batchcode](https://www.evennia.com/docs/latest/Batch-Processors.html) system, which essentially does similar to what I am saying with making a file with every command to rebuild the rooms, then said file can be pushed into version control and compared to existing changes correctly. Any overwrites can be rolled back because there are multiple versions of the areas/rooms committed to source control and the existing area can still be recovered from bad commits if they happen as they are two separate states of the file, right?

If the [batchcmd/batchcode](https://www.evennia.com/docs/latest/Batch-Processors.html) is recommended, why not make a way to export rooms to these commands, which as above, is the same ask. I only recommended old school .area files not in batch command form because having used large batchcmd files myself, executing large amount of codes freezes and seems a bit clunky like it could break if I recreated 10,000 rooms (e.g.: rebuilt entire world). Versus reading the entire file on the backend, and just writing/updating it to the tables. At least it sounds good in my mind! 🍡

**Comment by Griatch** [comment]
What you want is creating the game in the database and then export that into a text file that you can move to the other environment to import directly in the production database, as far as I understand. That would suggest copying a database state. What intermediary file is used is irrelevant. A django fixture or something like the django smuggler is a way to do this type of transfer.

It doesn't matter one whit what you have in version control once you applied your file (of whatever format) to the database. At that point you are dealing with a database schema structure and binary data. If the production db is a live one, reapplying such a fixture (after, say a git rollback) would risk leading to the bugs I mentioned before. It's not impossible, but it's very hard to generalize and make safe.

A batchcode/batchcmd should of course be put under version control. But the file is generally applied once after being tested exhaustively on a development server. While you could codedly make it so that it updates existing objects, this is highly dependent on situation. Overall, it's also different in that the creation of the batchcmd/batchcode file _is_ the building process, make no mistake. They exist so that you can create your game without needing to do so one-by line over a telnet interface but in a regular text editor. Building a batchcode/batchcmd file after you already created a game in the database is sort of backwards. At that point you should probably be looking at fixtures and direct binary transfer of data instead.

**Comment by davewiththenicehat** [comment]
I am genuinely curious. Normally my database work is on a small scale. Wipe and restore from a backup. Import old database into new runtime. I have not been in the situation where I wanted to migrate portions of a database into another.

Would one of the issues be dbrefs not matching to the correct objects? When you import wouldn't the existing dbrefs get overwritten? I'm guessing that is the key?
So dbref 23497, was a pair of gloves but after the import it is an exit for room 23496. The exit23497.location is that room, but character 2093 is wearing dbref 23497. Because the other fields were merged.
Character 2093 removes the gloves and places them in a sack, and the exit disappears from the room.

**Comment by Griatch** [comment]
@davewiththenicehat No, dbrefs should hopefully be consistent unless you really mess up your database (Evennia deliberately doesn't reuse dbrefs). The common confusion/bugs usually appear in changes to objects/attributes and relations happening in one environment not reflected in the fixture being applied to it.
Especially with a production database, with real people on it. A simple example would be the `.location` field of a character having changed in production but the fixture has another value for the location-relation. That one's simple to detect (the character suddenly jumps to an old location) but there are a lot of changes of much more subtle problems. The game state is a live thing in the database, and that is something your fixture will not reflect (and reverting to an older git revision is even worse) - and you will usually not be able to recover from any bugs/errors coming from that without direct SQL manipulation of the database or by restoring your database from a backup.

**Comment by TehFamine** [comment]
Unless I am vastly misunderstanding you here. The dbrefs would not be consistent across environments. Soon as I make a copy of the data from production, my dbrefs will be different with any new objects I make due to the time delay. I might have 1000 new dbrefs in production created by the time I create new dbrefs in development.

So, I kind of agree with @davewiththenicehat here in the sense that my dbrefs would not match the correct objects.

**Comment by strikaco** [comment]
> Unless I am vastly misunderstanding you here. The dbrefs would not be consistent across environments. Soon as I make a copy of the data from production, my dbrefs will be different with any new objects I make due to the time delay. I might have 1000 new dbrefs in production created by the time I create new dbrefs in development.

This should not be the case if you're re-creating these objects with their explicit primary keys (instead of letting the system choose an auto-incremented value for you).

ex. from another project:
```Python 3.7.10 (default, Feb 20 2021, 21:21:24) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from commands.models import Command

# Simulate re-creation of object-- note that I'm telling the db what id to use!
>>> c = Command.objects.create(**dict(id=666, category='foo', code='FFFF', key='bar'))                                                                                                                                                                                          
>>> c
<Command: FFFF (foo/bar)>
>>> c.save()
>>> c
<Command: FFFF (foo/bar)>
>>> c.id
666
>>> tuple(Command.objects.all())[-2:]
(<Command: xxxxx>, <Command: FFFF (foo/bar)>)

# This is the way you're probably approaching it-- see what happens?
>>> c = Command.objects.create(**dict(category='food', code='FFF0', key='bark'))                                                                                                                                                                                                                         
>>> c.id
667
```

**Comment by strikaco** [comment]
Related: #2180

**Comment by TehFamine** [comment]
> > Unless I am vastly misunderstanding you here. The dbrefs would not be consistent across environments. Soon as I make a copy of the data from production, my dbrefs will be different with any new objects I make due to the time delay. I might have 1000 new dbrefs in production created by the time I create new dbrefs in development.
> 
> This should not be the case if you're re-creating these objects with their explicit primary keys (instead of letting the system choose an auto-incremented value for you).
> 
> # This is the way you're probably approaching it-- see what happens?
> >>> c = Command.objects.create(**dict(category='food', code='FFF0', key='bark'))                                                                                                                                                                                                                         
> >>> c.id
> 667
> ```

The way I'm approaching it is similar to what Evennia suggests. Using the [Spawner ](https://evennia.readthedocs.io/en/latest/Spawner.html) from prototypes...

```
obj1, obj2 = evennia.utils.spawner.spawn({"key": "Obj1", "desc": "A test"},
                                         {"key": "Obj2", "desc": "Another test"})
```

**Comment by Griatch** [comment]
Sure, if you work with dbrefs explicitly in your batchcmd/batchcode file, then you obviously can't expect them to match when moving to another database. But using dbrefs in a batchfile was never a batchfile anyway.

I think we are talking past each other here. If you just want to rebuild using batchfiles, just use them - obviously this will create new objects at new dbrefs in the other environment.

If you want to copy over already existing database data between environments diractly you face a different problem and should use database tools/fixtures for this, which I've outlined above. A special case of this would be to add the ability to build batchfiles from database tables (a custom between-databases file format, basically), then a custom parser would need to be constructed for this. Then again you run into the issue of going out of sync between the environments and - if you update existing things due to bug fixes etc - override changed state in the target database.

**Comment by strikaco** [comment]
> The way I'm approaching it is similar to what Evennia suggests. Using the [Spawner ](https://evennia.readthedocs.io/en/latest/Spawner.html) from prototypes...

Yeah, the spawner basically calls the same command I outlined there-- the one that omits the primary key, so it always creates new objects.

Spitballing here (battery low), but try assigning your rooms/exits a secondary "PK" in the form of a UUID4 value. You can even set them arbitrarily as NDB attributes. It's not a proper PK and has no DB constraints or anything, but by nature these should be random enough to be unique across all of your object instances.

Now export all of your rooms and exits to JSON or whatever. Make sure the serialized versions include somewhere those UUIDs you assigned.

In your "clean" environment, reconstitute all of these objects as you have been but ignore the relationships (**do not specify destination or location! Set all to `None`!** All of your rooms won't exist yet-- and their IDs will absolutely not be the same!).

In a second pass over your serialized data, find each "new" room in the DB by its *UUID*, find each "new" exit in the DB by its *UUID*, and set the "new" room's destination to the "new" exit **ID**.

This should replicate your rooms and exits *and their relationships*. (Yes, yes, all of this should be handled natively, and I know it's not exactly what you're looking for--I do like your idea--but at least this solution is within reach.)

There is a case to be made for adding an instance UUID field to all object models as part of a natural key, so logical relationships can be serialized as well as attribute primitives...the integer PKs in use are storage-efficient but not at all portable.
