### ISSUE TITLE
[BUG] perm() lockstring for non-hierarchical permissions fails to allow Object permissions to pass

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2351]
#### Describe the bug
When I give a permission that _isn't_ in the hierarchy to a Character object and the character attempts to do anything locked to that permission, it fails. If I add the permission to the Account instead, it passes.

I know that for hierarchical permissions it's intended behavior to use the Account permission level to avoid escalating via puppeting. However, my understanding is that non-hierarchical permissions should be checking the Account first and if the permission isn't found, checking the acting Object next. It's clearly not checking the Object next.

#### To Reproduce
1. Create a test object and a non-superuser test character, e.g. "TestCharacter"
2. Assign the "test_perm" permission to TestCharacter.
3. Add a lock to the test object, e.g. "get:perm(test_perm)"
4. Attempt to pass the lock with TestCharacter, e.g. get the test object.
5. See error

#### Expected behavior
I expected TestCharacter, having the non-hierarchical permission "test_perm", to pass the lock and get the object.

#### Environment, Evennia version, OS etc
Output of `evennia -v`

    Evennia 0.9.5 (rev 8afa4ce02) (rev 8afa4ce02)
    OS: posix
    Python: 3.7.3
    Twisted: 20.3.0
    Django: 2.2.17

More specifically, the operating system is **Debian 10.7**

#### Additional context
I made sure to test this on a brand new cleanly-initialized game with no modifications to rule out any of my code causing the problem and confirmed that this happens.

**Comment by InspectorCaracal** [comment]
> 
> 
> You can also reproduce this with the stock perms:
> 
>     1. Create a new account with only player perms.
> 
>     2. Add Builder perm to character.
> 
>     3. Attempt to use Builder commands on that character.
> 
> 
> Won't work until you move it to the account.

The stock permissions are the "hierarchical" permissions, which are _supposed_ to work this way. They're called hierarchical because one permission gives you all of the lower permissions: Builder gives you Builder and Player; Admin gives you Admin, Builder and Player, and so on. Those are intentionally set up to use whichever level of permission the Account has so that an account can't puppet an inappropriately locked, higher-permission character and get access to commands they shouldn't have.

This issue is specific to non-hierarchical permissions, which the core Evennia code doesn't have built into any of its commands - that's why you have to make your own test permission in a fresh install.

**Comment by Griatch** [comment]
@InspectorCaracal Investigating this, this actually not a bug in the code - this is how the `perm` lockfunc works, and always worked. In the case where an object is puppeted, it requires you the `quell` in order to have object/character-level permissions take precedence over account-ones. And permissions is a on/off thing (either you have one or you don't), the Account not having the perm is in itself suggesting that it fails.

It rather appears to be a 'bug' in the documentation, because it suggests exactly the difference between hierarchical and non-hierarchical permissions that you expect above. I don't think the perm lockfunc ever worked like that, but I can see the argument for changing it. 

So I have now updated the `perm` lockfunc code in develop branch to match docs - non-hierarchical perms will first be checked on the account and then on object. If quelled, it will only be checked on the object.
