### ISSUE TITLE
[BUG] Update the building commands to have less 'common' names

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#2353]
#### Describe the bugs

After the `@` became optional, there are builder commands like `open` and `lock` that regularly collide with commands that users may want to implement themselves (open/locking doors). 

#### To Reproduce
- The `simpledoor` contrib uses an `open` command that collides with the builder `open` command.

#### Expected behavior

While we don't want to go back to `@`-prefixes, we can change the default builder commands to have less 'common' names.

**Comment by InspectorCaracal** [comment]
I'm pretty new to working with Evennia so I don't know the original rationale behind the decision, but the most straightforward solution here would be to reinstate the prefixes into the commands instead of stripping them. That would make it trivial to differentiate between game system commands and IC commands. e.g. `@open` to create Exits, freeing up `open` for IC functionality like opening doors; `@dig` to create Rooms, freeing up `dig` for IC; `@search` and `@find` to search the database for Objects, freeing up `search` and `find` for IC; etc.

**Comment by fariparedes** [comment]
> 
> 
> I'm pretty new to working with Evennia so I don't know the original rationale behind the decision, but the most straightforward solution here would be to reinstate the prefixes into the commands instead of stripping them. That would make it trivial to differentiate between game system commands and IC commands. e.g. `@open` to create Exits, freeing up `open` for IC functionality like opening doors; `@dig` to create Rooms, freeing up `dig` for IC; `@search` and `@find` to search the database for Objects, freeing up `search` and `find` for IC; etc.

I'm inclined to agree (they are traditional for a reason, after all) but apparently these prefixes confused people, which is why they were made optional in the first place.

**Comment by InspectorCaracal** [comment]
> I'm inclined to agree (they are traditional for a reason, after all) but apparently these prefixes confused people, which is why they were made optional in the first place.

Ah, I see.... That sounds like a potential can of worms that I should keep my own opinion out of. >.>

A probably more complex solution I thought of would be if the prefix was still functional, but you could define it in your game settings - in case people want to replace it with a syntax they're more familiar with, like a forward slash. But I don't know how difficult that would be to implement, so it's just a thought.

**Comment by fariparedes** [comment]
> 
> 
> > I'm inclined to agree (they are traditional for a reason, after all) but apparently these prefixes confused people, which is why they were made optional in the first place.
> 
> Ah, I see.... That sounds like a potential can of worms that I should keep my own opinion out of. >.>
> 
> A probably more complex solution I thought of would be if the prefix was still functional, but you could define it in your game settings - in case people want to replace it with a syntax they're more familiar with, like a forward slash. But I don't know how difficult that would be to implement, so it's just a thought.

Anyone can do that simply by overloading the commands and changing the key. :)

Perhaps a compromise would be to have it so that these builder commands are better designed to be overloaded; i.e. the @ remains optional until a new command with the same name is introduced, after which it automatically becomes mandatory and the displayed key is updated to match.

**Comment by InspectorCaracal** [comment]
> > > I'm inclined to agree (they are traditional for a reason, after all) but apparently these prefixes confused people, which is why they were made optional in the first place.
> > 
> > Ah, I see.... That sounds like a potential can of worms that I should keep my own opinion out of. >.>
> > A probably more complex solution I thought of would be if the prefix was still functional, but you could define it in your game settings - in case people want to replace it with a syntax they're more familiar with, like a forward slash. But I don't know how difficult that would be to implement, so it's just a thought.
> 
> Anyone can do that simply by overloading the commands and changing the key. :)

Well yes, but if that was considered a sufficient solution, this issue wouldn't be here, since you can already do that. ;)

> Perhaps a compromise would be to have it so that these builder commands are better designed to be overloaded; i.e. the @ remains optional until a new command with the same name is introduced, after which it automatically becomes mandatory and the displayed key is updated to match.

Now that is a great solution, I would wholeheartedy support it. You probably don't even need to change the keys, just use command priorities and aliases - assuming I understand how the command priorities work.

e.g. You have your builder `open` at a lower-than-default command priority with `@open` as an alias. Then when people add their own `open` command, it would take priority to the builder command, but `@open` would continue referencing the builder command.

**Comment by InspectorCaracal** [comment]
All that said:

If you want suggestions for less common-English command names, you'll probably want to get away from the more IF roots of MUD commands entirely and make the command names more explicitly connected to their mechanical function. For instance, instead of `dig`, something like `mkroom` or `makeroom`, `open` could be `mkexit`, `lock` could be `setlock` or `lockstring`, `search` could be `dbsearch`, etc.

**Comment by Griatch** [comment]
Thanks for the discussions and suggestions in this issue, @fariparedes and @InspectorCaracal! I have now (in https://github.com/evennia/evennia/commit/4f57370bc98383ae1d379a89a813f3746060387f) extended the way the prefix-ignore works in Evennia 1.0. The system will transparently use the non-prefixed command-name where possible, but fall back to separating them when there are duplicates. In practice it means that the building open command is now again `@open`, but you can still use it as `open` and help files will also show it as `open`. 

Only if you actively add a new `open` command will the system separate the two (and the help will show both commands etc). So this basically allows the default command to fall back to a @-form only when it's actually needed to differentiate with another command. 

You can read more about the feature here: 
https://www.evennia.com/docs/1.0-dev/Components/Commands.html#command-prefixes

One can of course still just replace & rename the default if one prefers. :grin:
