### ISSUE TITLE
[Feature Request] $dbref() support for set command

### ISSUE THREAD

**Issue by fariparedes** [evennia/evennia#2379]
#### Is your feature request related to a problem? Please describe.
Builders have no way to set references to other objects in an object's attributes. This is frequently a feature utilized heavily in the code, which makes it impossible for builders to interact with some systems.

#### Describe the solution you'd like
`set object/attr = $dbref(#5)` should result in object.db.attr being set to the packedobj/object reference to the typeclassed object with a dbref of #5.

**Comment by strikaco** [comment]
This is a cool idea, but referential integrity very quickly becomes a problem when creating "soft" relationships like this-- especially if you later try to move your database to another and are forced to re-create objects. We tend to have very little control over the auto-incremented primary key value in those cases. If object 5 is somehow renumbered to object 7 in the "new" database, you'll have a lot of string-processing to do--for every single attribute you've defined that refers to any other object in this way--since the numbering will likely have changed across the entire database.

Not that this can't be done--I'm all for it--but ObjectDB, ScriptDB, et al. are all basically non-relational databases. I'd again propose (@Griatch, #2335) to incorporate UUIDs into the typeclass object model and use those as a secondary (but preferred) object instance identifier behind-the-scenes where possible. (Do not _drop_ the integer pk-- backwards compatibility aside, they are much easier to manually type!)

The idea is: you may specify `dbref(#5)` but on save, it gets replaced with `dbref(ae55a121-f1e4-4062-ad4a-338e69bb6255)`. That reference may not _work_ after a botched migration, but there is (effectively) zero chance that reference will ever accidentally point to the _wrong_ object (#2350).

(...alternately, add the GenericForeignKey fields to the Attribute model so the value can directly reference another database object and referential integrity could be enforced through GenericRelations.)

**Comment by fariparedes** [comment]
Hi strikaco! This was not intended to be a soft relationship. It's intended as a way for builders to make the kind of links that code can, i.e. `object.db.attr = object2` as a direct link, to enable builders to interact with systems that utilize this feature.

**Comment by strikaco** [comment]
The "object reference that Evennia normally uses for packed objs" _is_ a soft relationship though:

https://github.com/evennia/evennia/blob/1c47bbe2ddf12aa461c5d5ffcc5457a4d255ec6b/evennia/utils/dbserialize.py#L452-L456

...it's just a tuple instead of a string.

I do understand your intent; your idea is sound, I'm only thinking a few steps ahead and suggesting that behind the scenes, storing plain UUIDs would be safer to work with all-around, especially in frontends like the CLI or Django admin.

(Strings can also be indexed for faster lookups. Reverse relationships involving stored objects are currently not scalable since you have to iterate every attribute in the database and reconstitute the value/object from a tuple to see if it matches.)

**Comment by fariparedes** [comment]
Oh, haha, that's an entirely different feature request, then, no offense. I'm only proposing a way to allow builders to make the sort of packed_dbobj references that coders already can.

**Comment by Griatch** [comment]
To go with the original request - the addition of the FuncParser in `develop` now makes it possible to add functionality like this to the `set` command without security issues. So sounds like something useful to do.

**Comment by Griatch** [comment]
Implemented in develop branch.
