### ISSUE TITLE
Task Management Command

### ISSUE THREAD

**Issue by davewiththenicehat** [evennia/evennia#2417]
#### Is your feature request related to a problem? Please describe.
No, this is mostly to provide developer's a method to look for rogue tasks.

#### Describe the solution you'd like
A command to show and manage tasks (delays) deferred.
I'd like to make it into a clickable table. Due to the volatile nature of delays, command switches may not be fast enough for managing short tasks.
This will not remove the need for switches, as I will still need to use them in the linking text tag.

I am going to:
use format `tasks/[action] [task_id]`. Where the switches were methods on the task handler.
make this an developer security command. As I could see both developers and admins wanting to use it.
put it in the admin help category.

#### Describe alternatives you've considered
A management window within the web app. I decided against this due to the short nature of a standard task.

#### Additional context
I am going to make this. I figured before I did I would see if there was interest for others to have this.
Than if there is interest, to make it in such a way that everyone is happy with it.

**Comment by Griatch** [comment]
This could be an interesting thing for `develop` branch, sure. I'm not sure how often it would be used, but having a way to get an overview of delays may be instructive. The `script/scripts` command will also get some refactoring but this is a separate functionality.

Note that `delay()` is used in many situations, including in things like the `@interactive` decorator and for `yield` operations inside the `Command.func` method. So there could be delays from a lot of sources.

**Comment by davewiththenicehat** [comment]
I am working off of `master` when I PR to `develop` is it likely to cause merge errors?
If I can I would like to avoid pulling develop.

I doubt the tasks command is used often. I see developers using it to look at tasks when they something occurring without manual calls. It will probably be used mostly just for peace of mind.

**Comment by Griatch** [comment]
Generally, you always should work off the branch you want to merge with, since you want to be able to test properly. So I recommend rebasing your work off develop branch right away. As [per the git recommendations](https://www.evennia.com/docs/latest/Version-Control.html?highlight=git#committing-fixes-to-evennia) I also strongly suggest you make a new branch of develop and work on that rather than working on your local copy of the develop (or master) branch - that's just inviting merge conflicts. Best to keep your local version of master/develop as 'pristine' 1:1 to upstream as possible.

**Comment by davewiththenicehat** [comment]
PR https://github.com/evennia/evennia/pull/2425 is merged, closing issue.
