### ISSUE TITLE
[BUG] Instance methods can no longer be pickled

### ISSUE THREAD

**Issue by fariparedes** [evennia/evennia#2439]
#### Describe the bug
After merging the last ~40 commits of the upstream branch, the functionality to automatically close my doors stopped working. It now throws a TypeError when attempting to pickle the instance method. This breaks `delay()` on any instance methods.\

```
Traceback (most recent call last):
  line 342, in add
    dbserialize(callback)
  line 751, in dbserialize
    return do_pickle(to_pickle(data))
  line 734, in do_pickle
    return dumps(data, protocol=PICKLE_PROTOCOL)
TypeError: cannot pickle 'weakref' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  line 644, in _run_command
    ret = cmd.func()
  line 56, in func
    door.open(self.caller)
  line 156, in open
    self.toggle("open", opener)
  line 120, in toggle
    self.autoclose_delay = delay(self.db.autoclose_interval, self.auto_close, persistent=True)
  line 1064, in delay
    return _TASK_HANDLER.add(timedelay, callback, *args, **kwargs)
  line 344, in add
    raise ValueError(
ValueError: the specified callback <bound method Door.auto_close of room> cannot be pickled. It must be a top-level function in a module or an instance method.
```

The method code:
```
def toggle(self, state, toggler=None):
    [...]
    self.autoclose_delay = delay(self.db.autoclose_interval, self.auto_close, persistent=True)

[...]

def auto_close(self):
    if not self.db.closed:
	    mapping = {
		    "door": self.db.door_name,
		    "exit": self.name
	    }
	    self.location.msg_contents(
		    (self.db.swing_closed_msg, {"type": "door"}),
		    from_obj=self.db.last_opened_by,
		    mapping=mapping
	    )
	    self.close()
```

#### To Reproduce
1. Create a typeclassed object
2. Add an instance method to the object
3. Call `delay()` on the instance method

#### Expected behavior
The TaskHandler object is created and returned.

#### Environment, Evennia version, OS etc
Evennia version: 0.9.5 (rev 45b99e59e)
OS: nt
Python: 3.8.5
Twisted: 20.3.0
Django: 2.2.19

**Comment by Griatch** [comment]
This one was on me, I made a last-minute refactoring of @davewiththenicehat's PR before merger that had this side effect. :swaziland:

**Comment by davewiththenicehat** [comment]
Should I write up a unit test for serializing an instance method?
Would changing the pickle protocol to 3 or 4 resolve this issue?

https://github.com/evennia/evennia/commit/f235572cac39c279fc06feef9951492219f7f2b7 added the `PickleError` catch.
How does removing the catch remove the failure to pickle? If there is a `PickleError` thrown, how was the code working.

Keep in mind before completing TaskHandler, I was serializing instances methods. I know for certain it was working.
After I learned about pickling and serialization, I switched those delay creations to non-persistent. Only because I thought it should not work. This was before the commit to catch the PickleError.

**Comment by Griatch** [comment]
@davewiththenicehat I didn't remove `PickleError` and the pickle serialization protocol is also irrelevant. The catch was just in the wrong place (because I erroneously moved it before). 
It _is_ not possible to pickle a typeclass-method directly - what we do to get around this is to pickle a tuple `(obj, "methodname")` instead. The error should only be raised if pickling this tuple _also_ fails. When unpickling later, we check if what we saved is a tuple (rather than a callable) and run `getattr(obj, "methodname")` to get the desired method back. 

A unit test is always good, by all means, if you feel like exploring the functionality. :)
