### ISSUE TITLE
[Feature Request] Traits / Rate - Cast current value to same type as `base`

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2451]
#### Describe the bug
Rate seems to be statically set to add _x_ at 1-second intervals-- with intent to "regen 1 point every 6 seconds," it follows that one might set `rate` to `1/6`.

This is the documented expectation:
https://github.com/evennia/evennia/blob/43fd533f28e4b17e33f0ab4a90372ccc6f7d723c/evennia/contrib/traits.py#L231-L234

...but come on; we don't have any options for changing the interval, and for the _string_ representation, how often is a `float` going to be meaningful?
```
>>> self.stats.stam
Stamina      78.35631567239761 /  100 ( +0)
```
#### Expected behavior
Identify what type `base` is set to and assume that as the intended _display_ type. (Comparisons should remain as precise as possible.)

In this case, `base` is `100` (an integer)-- so display the current value as an `int` by default.

If some odd case really needs every last decimal represented in the string, then `base` should be set to `100.0`. Current value should _then_ always be cast to `float`.

Neat contrib in all respects!

**Comment by Griatch** [comment]
Fair enough, that sounds like a good idea. This is not a bug though, but a feature request.

**Comment by Griatch** [comment]
> Rate seems to be statically set to add x at 1-second intervals-- with intent to "regen 1 point every 6 seconds," it follows that one might set rate to 1/6.

There is no such setting. There is nothing 'stepping' here; you can set what ever rate you like and get as precise a result as you like. It just compares the time since you set the rate to the current time and figures out what the value now should be.

Anyway, I implemented this change now - the shown datatype is based on the `base` type, rounded to closest integer when so needed.
