### ISSUE TITLE
[BUG] (Develop) Scripts - How to retain auto-delete functionality?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2455]
#### Describe the bug
There no longer seems to be a way to have scripts auto-delete themselves at stop.

Any hook called from `at_stop` that might result in self-deletion instead results in recursion errors (for obvious reasons, but still).

I might be able to do a `utils.delay` to call `delete` on it, but that's messy.

Was this functionality removed altogether?

#### Environment, Evennia version, OS etc
Develop

**Comment by Griatch** [comment]
Yes, the timer-component of the Script is no longer tied to the lifetime of the Script, since Scripts are so often used as storage containers these days. A script that deletes itself at stop should probably instead be handled by `utils.delay` or the new `utils.repeat` functions, both of which are both persistent and more light-weight.
That said, we should probably be able to add functionality allow users to delete from `at_stop` without triggering a recursion error for those that still want this.

**Comment by strikaco** [comment]
FWIW, I tried calling self.delete() through utils.delay during the at_stop hook-- it did work, though it had the side effect of running the at_stop hook twice.

**Comment by Griatch** [comment]
I added a new kwarg `Script.delete(stop_task=True)` that can be used to break the infinite recursion when deleting the Script from the  `at_stop` method.
