### ISSUE TITLE
[DEVEL] [BUG] "builtins.RuntimeError: dictionary changed size during iteration" error in clean_stale_tasks

### ISSUE THREAD

**Issue by GulliblePsychologist** [evennia/evennia#2457]
#### Describe the bug
I'm getting a "dictionary changed size during iteration" error in `clean_stale_tasks` in `taskhandler.py` in a game that uses a lot of tickers (and resets them on `at_init`)

#### Environment, Evennia version, OS etc
Evennia 1.0-dev (rev 43fd533f2) (rev 43fd533f2)
OS: nt
Python: 3.8.0
Twisted: 21.2.0
Django: 3.2.4

#### Additional context
I've patched this issue locally by editing `evennia/evennia/scripts/taskhandler.py` and editing line 271 from:

```
for task_id, (date, callback, args, kwargs, persistent, _) in self.tasks.items():
```

to

```
for task_id, (date, callback, args, kwargs, persistent, _) in list(self.tasks.items()).copy():
```

This fixes the issue for the time being, though a more complete fix may be to synchronize the `self.tasks` variable so that it isn't modified between different Python 'threads'.

**Comment by GulliblePsychologist** [comment]
Note: I previously reported a similar issue (#1992) and it looks like this was never addressed.

**Comment by Griatch** [comment]
#1992 is a similar-sounding error at a completely different location. And that was indeed addressed, both in master and develop branches.

**Comment by GulliblePsychologist** [comment]
So it has. Sorry for raising the alarm there.

I just noticed the use of `threadable.synchronize` in another file.
Maybe that's a useful fix for the taskhandler?

**Comment by Griatch** [comment]
@GulliblePsychologist Hm, where do you find `threadable.synchronize`? Evennia is an asynchronous framework and not thread-based one. But anyway, this is a simple Python issue and unrelated to any asynchronous behavior.

**Comment by davewiththenicehat** [comment]
@GulliblePsychologist you can disable stale task cleanup by setting `TASK_HANDLER.stale_timeout` to 0.
That is is happening at `clean_stale_tasks` and not `load`, `add`, or `save`. A full traceback would at be helpful to pin down when the issue is occurring.

@Griatch deep coping the tasks dictionary could be process intensive in some rare instances. When there are a lot of tasks, or the call backs are significant. It is an easy fix though.
If I create thread locks, it going to lock those threads waiting. I doubt for long though.

I don't think synchronizing will resolve changing the dictionary size during iteration. I think it just makes certain the variables match.
Also, I think global variables automatically synchronize.

**Comment by Griatch** [comment]
@davewiththenicehat There are no threads here, please use the right nomenclature - the taskhandler deals with asynchronous deferreds and there are no concept of 'thread locking' or the like here. There are no race conditions in an async system. 

The issue here is that the tickers are reset in their at_init, I suspect. I agree that it would be good if @GulliblePsychologist could provide a full traceback.

**Comment by GulliblePsychologist** [comment]
The dictionary changes during iteration because the `at_init` method is able to call a function on the `taskhandler` at the same time that `clean_stale_tasks` is running.

I don't know of any other way that you'd run two functions concurrently other than by threading, so my guess is that whatever calls `clean_stale_tasks` is running independently from whatever is loading in a new object and calling `at_init`.

Python will use some sort of pseudo-threading where it'll switch between running different threads but won't actually run them on different CPU cores due to the Global Interpreter Lock (GIL).

However, it's still possible that a dictionary is changed during iteration if Python decides to suspend the `clean_stale_tasks` function in the middle of its loop and another function (like my `at_init` implementation) then causes the dictionary to be changed.

This is why I was apprehensive about #1992 as I didn't see a change there that would synchronize that dictionary across different Python threads.

`threadable.synchronize` is used by Twisted's logging system, which I believe are in turn used by Evennia to write the `portal.log` and `server.log` files.

This function allows you to easily wrap an object instance such that its methods can only be called by one Python thread at a time.

I suspect that wrapping it around the `taskhandler` and other places like it would fix these types of issues, assuming that variables like `self.tasks` are considered private variables that aren't touched by methods outside that object.

**Comment by Griatch** [comment]
@GulliblePsychologist Again, there is no threading going on here. Evennia is an asynchronous framework, through the Twisted event-loop. Simplified, this means that the core event loop (called the `reactor` in Twisted, implemented in pure C) will quickly iterate across all server connections and 'split up' execution and execute them sequentially. By quickly rotating between execution environments the illusion of 'parallelism' is achieved. In reality everything is run sequentially. 

For things that are I/O bound (like network traffic) this is truly parallel since this makes use of the multitasking of the operating system. And for pure stateless I/O tasks (such as the log-writing you refer to, and also for the threadpool we use for serving static web pages) there can be ok to use threads. This is _not_ the case for anything happening in the game loop though - to which the taskhandler's tasks belong. 

For CPU-bound tasks, you run everything in the same process (and in the same thread, due to the GIL, Python multi-threading of CPU-bound tasks is not a good idea anyway). This is called asynchronous processing, as opposed to parallel processing you'd get from (theoretically) threading and multiprocessing (the latter of which is the only true way to do CPU-bound parallelism in Python). 

The advantage of asynchronous processing is that there is no risk of race conditions or need for things like locking. The drawback is that a single CPU is used and if you do `time.sleep()` you actually stop the server for _everyone_, not just for you - this is why we use `delay` etc - which are pause operations that make use of the central event-loop. 

Due to the lack of race conditions it makes it a lot easier to debug issues like this as well. What happens here (I suspect) is that the objects affected by these tasks are not in memory when the Taskhandler runs it cleanup task - so as part of building the loop iterator, the objects get loaded into memory, which fires `at_init` - at which point that method tells the task to stop, which in turn modifies the looping iterator (since a task suddenly goes away mid-iteration) and gives this error. One would need to investigate further, but there's nothing thread-related with it at all (because it cannot be).

**Comment by GulliblePsychologist** [comment]
I understand the way that it's _supposed_ to work, but something in me raised the alarm as I didn't feel like the `clean_stale_tasks` function could do this on its own, and that's where my confusion stems from.

When I attach a debugger to the Python process I can see that there are 4 threads:
- MainThread
- PoolThread-1775928954832-0
- Dummy-4 (appears benign)
- PoolThread-twisted.internet.reactor-0 (appears benign)

I managed to get this in a state where both the `MainThread` and the `PoolThread-1775928954832-0` are writing to `self.tasks` at the same time.

See these screenshots with two distinct stack traces:

![image](https://user-images.githubusercontent.com/56974578/123560431-f7a9ca80-d799-11eb-8778-8e3d54e96416.png)

![image](https://user-images.githubusercontent.com/56974578/123560435-fd071500-d799-11eb-9ed1-b6d86e125ef6.png)

---

The way I have been reproducing this issue is by refreshing a page in my browser that lists all the Characters under my Account.

These are the steps I used:

1. Start the portal and server.
2. Attach PyCharm to the server process.
3. Attach a breakpoint as needed to catch the RuntimeError. (In my case, I wrote a little try/catch around the for loop so I could put the breakpoint inside the `catch` block.)
4. Refresh the page in my browser. The RuntimeError will occur a couple of times before all objects are loaded into memory.

---

I haven't used Twisted extensively (only via Evennia's implementation of it) so I don't know how this is meant to work in the background, but looking at my debugger it seems to me that there are (as I predicted) two distinct threads that are messing with the TaskHandler at the same time.

If I were to guess, I think that the `MainThread` is Evennia's event loop while this `PoolThread-1775928954832-0` is part of the webserver?

I'm requesting objects within a `View` which in turn (through my implementation of `at_init`) adds a task to the TaskHandler (which in turn calls `clean_stale_tasks`) and this all appears to run next to the main thread.

Is my analysis correct? 🥺👉👈

**Comment by Griatch** [comment]
Yes, as mentioned earlier, the webserver uses a threadpool to serve static pages/views. You didn't specify that you were triggering `at_init` as part of a view - this is a so rarely considered use case that it changes the analysis quite a bit :) 

1. Out of curiosity, why are you adding a task in `at_init`, which fires every time the object is loaded into memory? 
2. Generally, the web server/admin is not meant to be used to fire game code in the running game - it's meant to primarily read data. I'm not too surprised one can mess with the game state if doing things like this from a view - it's generally something that's not tested much and you can risk ending up with inconsistent cache. Adding separate thread-protection for things like this is not something I'd be too happy to start doing (it's also very hard and cover all cases), maybe we could instead consider turning off the thread pool for those that want to expand their use of views this way.

**Comment by GulliblePsychologist** [comment]
Originally, I used `at_init` to set some attributes and (un)set tickers for objects that needed it, but I started to encounter strange issues, perhaps related to this issue. I found that using `delay` fixed my issue - probably because this shifted execution back to the MainThread where it belongs.

---

When you mentioned static web content I thought you meant the `web/static` folder and the content in there, not all views. I'm definitely going to need the ability to request game data from views. That's one of the main reasons I'm not just hosting something else next to the game right now (though with the REST API officially supported this might be easier now).

I also don't see myself as using the web server/admin to fire game code in the running game, but Django will load in objects and hooks like `at_init` will get called regardless if they are loaded by the MainThread or the web server.

Unfortunately, even stock Evennia is probably susceptible to this issue: viewing details on an object or editing one of your characters might cause those objects to be loaded in.

---

Hypothetically, If we had a subclass of `View` that pre-emptively forces all of its methods to execute on the MainThread then that would solve this problem.

**Comment by GulliblePsychologist** [comment]
I have a fix for my own use case by creating a new function under `server/utils.py` that allows me to ask the MainThread to run some code. This will cause the invoking thread to be suspended until the MainThread responds, which is sufficient for the multithreaded architecture of WSGI.

```python
def run_in_mainthread(callback):
    if threading.current_thread().name == "MainThread":
        # We're already in the MainThread, so we can just run the callback immediately.
        callback()
    else:
        # This will suspend the current thread until the callback has finished.
        result = None
        got_result = False

        def success(r):
            nonlocal result, got_result
            result = r
            got_result = True

        def error(failure):
            nonlocal result, got_result
            result = failure
            got_result = True

        d = deferLater(reactor, 0, callback)

        d.addCallback(success)
        d.addErrback(error)

        while not got_result:
            time.sleep(0)  # yield until we have result

        return result
```

Example usage (in the `get_context_data` of one of my views):
```python
characters = run_in_mainthread(lambda: [o for o in DefaultCharacter.objects.all_family()])  # "o for o in ..." is necessary to ensure that we've looped over every element
```

This allows me to work somewhat asynchronously. It's not ideal, but as long as I stick to

**Comment by Griatch** [comment]
Hm. Nice workaround, but that `while` loop is nasty. :grinning:  Couldn't you just go with Twisted's `callFromThread()` instead?

We do something like this, not specifically for the webserver, but (originally) for an experiment with workers. It's in the central idmapper system, to let `Model.save` operate in the main thread:  https://github.com/evennia/evennia/blob/develop/evennia/utils/idmapper/models.py#L443. 
Thinking about it, I remember reading that later versions of Django supports some alternatives to the WSGI container, maybe something more async-friendly is available these days ...?

**Comment by GulliblePsychologist** [comment]
Thank you for the tip. I can't use `callFromThread` here but there is a different method in Twisted called `blockingCallFromThread` that does the same thing I was doing but better (with a queue).

This is the updated version, which looks much cleaner:

```python
def run_in_mainthread(callback):
    if threading.current_thread().name == "MainThread":
        # We're already in the MainThread, so we can just run the callback immediately.
        return callback()
    else:
        # This will suspend the current thread until the callback has finished.
        return blockingCallFromThread(reactor, callback)
```

**Comment by Griatch** [comment]
@GulliblePsychologist For now, I have now added your helper function as an evennia utility in `develop`; the web tutorials will need to consider this moving forward.
