### ISSUE TITLE
[Feature Request] Examine Command - Change object category from Characters to Players.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evennia#2472]
#### Is your feature request related to a problem? Please describe.
https://github.com/evennia/evennia/blob/master/evennia/commands/default/building.py#L2611

The examine command lists objects in the room and categorizes them by Exits, Characters, and Things.
This isn't exactly accurate, as the Characters section checks to see if an object has an account, whereas characters with no account are listed under Things.

#### Describe the solution you'd like
Characters should be re-named to Players. Only players have an account and it much more accurately represents this category.

**Comment by Griatch** [comment]
This will not happen. The term `Player` has a legacy meaning in Evennia (it's the old name of 'Accounts'). Today, the "Player" is the term used for the human playing the game. Even if it was not, the RPG lingo is "Player-Character' and "Non-Player-Character" - with a focus on the Character). The Character is by no means a Player on its own. 

The examine command does this separation because _any_ entity can be puppeted (Character is just the most common one). Possibly we should rename the category in the examine command to "puppeted" and other, but not clear if that would be clearer or not. 

Nevertheless, closing this.
