### ISSUE TITLE
[BUG] Unexpected behavior when renaming objects with the same or very similar name

### ISSUE THREAD

**Issue by fire-hawk-86** [evennia/evennia#2579]
#### Describe the bug
The wrong object is being matched (renamed), instead of the one under `(please narrow target)`
There is a discrepancy between which object the "please narrow target" listing expects to be targeted when using the name "1-guest", and the actual object being targeted, which is named "guest 1" but has a different id and isn't even shown in the "narrow target" list.

#### To Reproduce
1. create three objects named: "guest 1", "guest" and "guest"
2. type `@name guest=guest 2`
3. response:
```
More than one match for 'Guest' (please narrow target):
1-guest(#62)
2-guest(#63)
```
4. type `@name 1-guest=guest 2`
5. type `@look`
6. the unexpected result: `"guest 2", "guest" and "guest"`

#### Expected behavior
I expected the object with the id `#62` being changed, instead an other object was renamed which wasn't shown in the `(please narrow target)` listing.

#### Environment, Evennia version, OS etc
Evennia 0.9.5 (rev 8822cd3cb) (rev 8822cd3cb)
OS: posix
Python: 3.8.10
Twisted: 21.7.0
Django: 3.2.8

#### Additional context
I think the mismatch has to do with the number 1 preceding in "1-guest" and the number 1 in the name of the object "guest 1".

**Comment by changemewtf** [comment]
Three objects in a room: `guest 1`, `guest`, and `guest`.

Output of `look g`, `look gu`, `look gue`, `look gues`:

```
More than one match for 'gues' (please narrow target):
1-guest 1(#48)
2-guest(#49)
3-guest(#50)
```

Output of `look guest`:

```
More than one match for 'guest' (please narrow target):
1-guest(#49)
2-guest(#50)
```

As a reminder, the bug is that everything from `look 1-g` to `look 1-guest` has the same output:

```
guest 1(#48)
You see nothing special.
```

There are situations where object search is run twice. Specifically when no initial match is found. Here's the relevant code in `evennia/objects/manager.py`:

```py
455         # Search through all possibilities.
456         match_number = None
457         # always run first check exact - we don't want partial matches
458         # if on the form of 1-keyword etc.
459         matches = _searcher(searchdata, candidates, typeclass, exact=True)
460         if not matches:
461             # no matches found - check if we are dealing with N-keyword
462             # query - if so, strip it.
463             match = _MULTIMATCH_REGEX.match(str(searchdata))
464             match_number = None
465             if match:
466                 # strips the number
467                 match_number, searchdata = match.group("number"), match.group("name")
468                 match_number = int(match_number) - 1
469             if match_number is not None or not exact:
470                 # run search again, with the exactness set by call
471                 matches = _searcher(searchdata, candidates, typeclass, exact=exact)
```

Of particular note are lines 459 and 471. The first search is *always* `exact=True`, whereas the second search can be either, `False` by default.

When you search for `g`, `gu`, `gue`, or `gues`, there are no exact matches, so the function falls through to the second non-exact search. This returns three results: `guest 1(#48)`, `guest(#49)`, and `guest(#50)`

When you search for `guest`, we have an exact match, returning only two results: `guest(#49)` and `guest(#50)`

Then, when you search for anything from `1-g` to `1-guest`, there are no exact matches, so your multimatch number is processed against the list of three results, and never the list of two results.

This is an odd bug, because if you're being lazy and just type `look g`, you'll have a successful interaction. The two objects named `guest` can be accessed as `2-guest` and `3-guest`, as indicated by the multimatch results.

However, if you're fastidious and type `look guest`, you'll enter into this unusual exact match situation, the multimatch results will tell you that `guest(#49)` can be accessed with `1-guest`, but you'll try that and look at `guest 1(#48)` instead.

Not sure yet what an appropriate fix would be!

**Comment by changemewtf** [comment]
Something like this would fix the bug, but I'm not sure if it's in line with the philosophy of how multimatch is actually supposed to be used, and would also make the `exact` argument a bit redundant.

```py
455         # Search through all possibilities.
456         match_number = None
457         # always run first check exact - we don't want partial matches
458         # if on the form of 1-keyword etc.
459         matches = _searcher(searchdata, candidates, typeclass, exact=True)
460         if not matches:
461             # no matches found - check if we are dealing with N-keyword
462             # query - if so, strip it.
463             match = _MULTIMATCH_REGEX.match(str(searchdata))
464             match_number = None
465             if match:
466                 # strips the number
467                 match_number, searchdata = match.group("number"), match.group("name")
468                 match_number = int(match_number) - 1
469             if match_number is not None: 
470                 matches = _searcher(searchdata, candidates, typeclass, exact=True)
471             if not matches:
472                 # run search again, with the exactness set by call
473                 matches = _searcher(searchdata, candidates, typeclass, exact=False)
```

**Comment by Griatch** [comment]
Thanks for the analysis! I implemented a fix similar to the one suggested by @changemewtf (in develop branch). The main thing with this kind of 'dumb' multimatch is that it's stateless though - if you use a different search query when you prepend the number (like `guest` in the first query and `1-gu` in the second, the system may will find a different set of matches for the second query. This becomes somewhat less of an issue in develop branch, where we default to `guest-1` style - it seems less likely to change the `guest` part when you can just append a number to the end than to the beginning.
