### ISSUE TITLE
[BUG] No switches in Typeclass Command

### ISSUE THREAD

**Issue by The-Archemist** [evennia/evennia#2590]
Cmd Typeclass has no attribute 'switches'.

1. Fresh Evennia installation
2. Use command 'update'
3. See error

![image](https://user-images.githubusercontent.com/73198594/142748097-6faf93ed-518a-447c-b784-dabe6db636bb.png)

**Comment by The-Archemist** [comment]
Replacing Default Command Class, even if not given any changes, breaks the above.

**Comment by Griatch** [comment]
I'm confused. The issue was closed,  yet the above comment is done after closure.  Is there an issue or not?
If so,  it also requires more clear info on exactly how to reproduce...

**Comment by The-Archemist** [comment]
> I'm confused. The issue was closed, yet the above comment is done after closure. Is there an issue or not? If so, it also requires more clear info on exactly how to reproduce...

Sorry. The comment was more of an afterthought/warning.

As far as what occurred, if the default command pointer in `settings` is changed from its stock value, CmdTypeclasses stops believing it has switches for some reason.

**Comment by The-Archemist** [comment]
Image of Base Command in `commands.command`:
![image](https://user-images.githubusercontent.com/73198594/142757447-5d1ec347-8139-46cb-ab67-621e48fd874f.png)

Image of `COMMAND_DEFAULT_CLASS` in `settings`:
![image](https://user-images.githubusercontent.com/73198594/142757468-ad4e99a5-8977-40e8-8b65-1679fae7e558.png)

Image of error:
![image](https://user-images.githubusercontent.com/73198594/142757496-ff549687-fb9e-4ce2-b4cb-907a4fe4ce40.png)

Image of update after `COMAND_DEFAULT_CLASS` removed from `settings`:
![image](https://user-images.githubusercontent.com/73198594/142757513-3c3c4999-8d43-42e9-9914-914c718f62ca.png)

**Comment by Griatch** [comment]
I see. This is not a bug, because the default commands are not inheriting from `evennia.commands.Command` but from `evennia.commands.default.muxcommand.MuxCommand`. Only MuxCommand knows anything about switches, the base Command is only `cmdname + arguments`. 
So inherit your replacement `COMMAND_DEFAULT_CLASS` from MuxCommand, or take a look at the bottom of your  `mygame/commands/command.py` where you'll find a commented-out version of `MuxCommand`. You can uncomment that and add it as your new parent to tweak.
