### ISSUE TITLE
[Feature Request] Add "mult" property to the Trait contrib

### ISSUE THREAD

**Issue by Tegiminis** [evennia/evennia#2625]
#### Is your feature request related to a problem? Please describe.
The Traits contrib notably lacks an internal way to multiply trait values, which is a common modifier done in hack-and-slash MUDs and other combat-heavy RPGs. Current, the only value modification made to default traits is additive `(base + mod)`

#### Describe the solution you'd like
1. `mult` is added as a property on traits, defaulting to 1.0
2. `value` is updated to be `(base + mod) * mult`

#### Describe alternatives you've considered
The alternative is no implementation, which leaves developers to implement it themselves. 

#### Risks
It is not a difficult implementation by any means, and if a developer has no intention of using multipliers it does affect them at all. Relatively low risk, and makes the traits contrib more robust for games that use multiplicative modifiers.

**Comment by whitenoiseoss** [comment]
I think this sort of thing belongs elsewhere. I always imagined this being done by an effect or something like that--something that would manage the calculation before sending the value to a Trait, rather than have Trait be responsible for arbitrary calculations. In my mind this would breach the single responsibility principle in a way that could create a mess.

**Comment by Griatch** [comment]
This was actually already added in https://github.com/evennia/evennia/pull/2628, this issue was just never referenced. So this should be closed.
