### ISSUE TITLE
[BUG - Develop] EvMore breaks inline coloring for HELP command.

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2646]
#### Describe the bug

Color markup gets lost in HELP output when run through `EvMore`. Only occurs if help output is long enough to require paging.

![color_bleed_bug](https://user-images.githubusercontent.com/15664651/153295203-9c7c2efe-6d64-406f-b8a3-4627c8efc86c.png)

#### To Reproduce

1. Add many help topics or commands.
2. Run command HELP
3. Observe color bleed.

#### Develop-branch commit

    Evennia 1.0-dev (rev c2f4f8568) (rev c2f4f8568)
    OS: posix
    Python: 3.10.2
    Twisted: 21.7.0
    Django: 4.0.2

**Comment by aogier** [comment]
I've noted the same, problem actually happens only when a category (ie. "Building") get a split as you can see in this shot
![help](https://user-images.githubusercontent.com/321364/183244444-09d7bdfe-7ff3-4944-a1f7-35d7403e483c.png)

that's because green formatting is applied at the end of header lines eg. [here](https://github.com/evennia/evennia/blob/9d1f35a8883a595ebf829cfbe47630b5d973d4ee/evennia/commands/default/help.py#L252) and this cannot survive subsequent splits.  
I think we have two possibilities here:

 * wrap every command name w/ proper ansi formatting
 * make evmore aware of the active formatting in the last paged line so it can reinject it after its prompt

in my opinion the second solution is the way to go cause it solve a generic EvMore problem, @Griatch what do you think?

BTW there's also a minor bleed on begin of pager input but it's simply matter of adding a `|n` at the begin of [this line](https://github.com/evennia/evennia/blob/9d1f35a8883a595ebf829cfbe47630b5d973d4ee/evennia/utils/evmore.py#L63)

**Comment by aogier** [comment]
ah, another way, maybe a bit more sustainable, could be to somehow instrument [`format_grid`](https://github.com/evennia/evennia/blob/9d1f35a8883a595ebf829cfbe47630b5d973d4ee/evennia/utils/utils.py#L1863). Still a bit of work either way tho

**Comment by Griatch** [comment]
Fixed this within the `help` command and `format_grid` as suggested. In the future, the moving of markup-to-ANSI parsing to the protocol level will likely lead to resolving this in another way.
