### ISSUE TITLE
[BUG] (webclient conversion of blank spaces unmanageable in EvForm)

### ISSUE THREAD

**Issue by alephate** [evennia/evennia#2701]
#### Describe the bug
The webclient does not show blank spaces the same way that telnet does, due to the conversion to html. An EvForm that looks perfect from mudlet might look strangely jogged around in the webclient. This is a problem majorly with EvTable and EvForm because in other situations, it can be managed by using different symbols for blank spaces. But when it comes to more dynamic content, it is difficult to predict what management might be necessary.

#### To Reproduce
1.  Use this form and command: https://pastebin.com/YiHLXEA0
2.  Connect through the webclient and run the command.
3.  Connect through mudlet and run the command.

#### Expected behavior
Blank spaces and blank rows inside of EvTables should be properly represented in EvForm format in order not to run into problems with the html conversion for the webclient.

#### Environment, Evennia version, OS etc
         Evennia version: 0.9.5 (rev 76af934fd)
         OS: nt
         Python: 3.7.9
         Twisted: 20.3.0
         Django: 2.2.5

#### Additional context
The html conversion for the webclient could be fixed to not have this problem: it seems that `|_` works better than tabs or blank spaces.

**Comment by InspectorCaracal** [comment]
Possibly related to #2677 ?

**Comment by InspectorCaracal** [comment]
I was poking around at this and while I'm not sure _how_ this would be happening, it seems as though the text2html parsing is applying to the template separately from the table as a whole, resulting in some double-spaces not being caught.

Specifically, on the line `left_table.add_row(" ", "Here is a blank space.")` and the two lines below, I noticed that the actual text in the element is 11 spaces (not including the left-border padding) while the displayed text is only 10 spaces, indicating that the first space in that element is staying ` ` instead of being converted to `&nbsp;`

I did a non-solution test where I changed the double-space replacement to replace all spaces with nbsp and confirmed it has the correct visible spacing in that situation. (It also breaks all of the html tags, so please don't try this as a fix 🤣 )

p.s. your example table isn't set to wrap lines, so the long line is being truncated with `[...]` indicating overflow instead

p.p.s. ...In further mysterious developments, I undid all of my changes to `utils/text2html.py` and restarted the server to go back to the base game state, and the spacing is somehow no longer broken when I use the `formtest` command. I have no idea why it would be behaving differently.

**Comment by Griatch** [comment]
With the PR from @InspectorCaracal merged, I see no discrepancies between telnet/webclient upon viewing this form. Closing. Feel free to reopen if there are still issues.
