### ISSUE TITLE
[BUG - Develop] funcparser breaks when args contain an odd number of apostrophe or quote marks

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2737]
#### Describe the bug
When a string with an odd number of quote or apostrophe characters is put into a funcparser function, it fails to parse the function.

#### To Reproduce
1. Put `$crop(spider silk, 5)` through the parser and verify it works (output: `spide`)
2. Put `$crop(spider's silk, 5)` through the parser: one apostrophe, output: `$crop(spider's silk, 5)`
3. Then put `$crop(spider's' silk, 5)` through the parser: two apostrophies, output: `spide`
4. Lastly, put `$crop('spider's' silk, 5)` through the parser: three apostrophes, output: `$crop('spider's' silk, 5)`

#### Expected behavior
It should successfully parse the function when it's being given a string that contains a single quote mark or apostrophe.

#### Develop-branch commit
7f4769bd9

**Comment by ChrisLR** [comment]
I see this as a limitation of how the parser is built.
It simulates what python would do and treats ' as the start of a literal string.
To avoid this, you can escape the ' so it is treated as a char.
Try
$crop(spider\\'s silk, 5)

**Comment by ChrisLR** [comment]
It could also be improved by accepting something like "spider's silk", it does not seem to accept it currently

**Comment by Griatch** [comment]
The funcparser is specifically built to support nesting of quotes; if it does not there may be a bug :)

**Comment by ChrisLR** [comment]
@Griatch problem here is the quote needs to be treated as a literal char, not as a quote

**Comment by Griatch** [comment]
Yes, it should work like Python in this case.

**Comment by InspectorCaracal** [comment]
> I see this as a limitation of how the parser is built. It simulates what python would do and treats ' as the start of a literal string. To avoid this, you can escape the ' so it is treated as a char. Try `$crop(spider\\'s silk, 5)`

Unfortunately that's one of the first things we tried - it doesn't make a difference.

**Comment by Griatch** [comment]
Better to have this here: 
It's a balance between being pythonic and easy to use; because plain python does require the quotes to denote a string while FuncParse really starts out as a string and should default to a string also if no quotes are given. 

So, 

- $func(something) is an implicit string "something"
- $func("something") is an explicit string "something"
- $func(some'thing) is an implicit string "some'thing"
- $func("some'thing") is an explicit string "some'thing"
- $func('something') is an explicit string "something" (etc, for '..."...' and so on)
- $func(\"something\") is an implicit string "\"something\"" with visible quotes

That is, if the quotes are to be explicitly visible in the string, they need to be escaped, otherwise surrounding the argument with "..." or '....' is equivalent to leaving them out. 

By the way, there is no concern of breaking backwards-compatibility here; unit tests can be updated to match behavior as needed. There is no FuncParser at all in master branch. Develop branch is not stable and people using a dev-branch accept the risks of using code that may still be in flux.

**Comment by InspectorCaracal** [comment]
Yeah, that breakdown is what I was thinking when I first posted this issue - or at least something similar. Since an unpaired quote mark isn't intended to be read by the parser as a syntactical element at all, it should be able to successfully parse a string.

That said: I think a big part of why this issue is cropping up is because of attempting to use both implicit and explicit string markers in the funcs that take strings, and it might be better to just not do that at all and just explicitly escape commas if needed? Especially since, at the moment, `$crop("spiders silk",5)` outputs `"spid`, which negates the whole using-quotes-to-mark-literals concept.

So:

* `$func(something)` receives the string `something`
* `$func("something")` receives the string `"something"`
* `$func(some'thing)` receives the string `some'thing`
* `$func(\"something\")` receives the string `"something"`

Then I believe the only things that would need to be explicitly escaped when using the funcparser are `,` and `=` since they're used for parsing args/kwargs

**Comment by Griatch** [comment]
So, if I understand you right, you are suggesting modifying the parser to drop the 'literal mode' entered when starting a `"` or `'` entirely, and just passing whatever is in the argument list as verbatim strings (except commas/equal signs)? 

I did think of this alternative in the past. And you are right that it would resolve the present `$func(some'thing, 5)` issue. 

I'm however not sure it's worth to drop the convenience and clarity of being able to do `$func("There is a red, blue and green man there, smiling.", 5)` though, having to do `$func(There is a red\, blue and green man there\, smiling., 5)`. 

It would seem better to bite the sour apple and solve this special case with a look-ahead to see if a `'` is indeed the beginning of a  a verbatim string or if it's an apostrophe.

**Comment by InspectorCaracal** [comment]
In that case, there's two issues that would need to be fixed, although the odd-count quotes is more pressing since it actually breaks the parser. The other one is that using quotes to mark string literals is, with the current funcparser, basically useless, because the quotes aren't stripped.

With the example list you gave above, the idea is that `$func(something)` and `$func("something")` should result in the arg `something`, while `$func(\"something\")` would result in the arg `"something"` with the visible quotes.

However, what actually happens is that `$func(something)` is the _only_ syntax that will result in the arg `something`. Both `$func("something")` and `$func(\"something\")` result in the arg of `"something"` - so if you don't want those enclosing quotes in your final string, you can't use them and you have to escape everything already, anyway. That's why I thought it might be more useful to just scrap the idea of using the quotes as literal string markers, since it doesn't really work at the moment anyway.

**Comment by Griatch** [comment]
Yeah, I understand what you mean, and I made the parser like that originally; but discussing and thinking about it now, I think it will be more rare to actually want to have verbatim quotes in the string than it is to want to have commas - and you should be able to 'escape' verbatim quotes they way you do it in Python, by alternating `"` and `'`, removing another need for a direct use of `\`. 

So yes, making the default be to not include the quotes would be a change of the funcparser behavior. The odd-quote case needs to be addressed, as well as properly 'nesting' double- and single quotes to escape each other (which I suspect the parser is not properly doing right now). 
As said, the feature is new to 1.0-dev and behavior is not stable, so changes like this can happen. 

(by the way, I don't expect you to work on this or anything; I can update the funcparser, it will still be a little while until I circle around to this though)

**Comment by ChrisLR** [comment]
I'm working on it btw, did some refactoring to make the fix easier, should have it working soon.

**Comment by Griatch** [comment]
Resolved in #2754

**Comment by InspectorCaracal** [comment]
Requesting this be reopened since it looks as though the merged fixes haven't fully fixed the issue.

**Comment by ChrisLR** [comment]
@Griatch oh it probably is because the ending ) is considered literal because of the stray ' which means it is never closed, and fail.
This is an edge case that requires varying degree of effort.
I see two options right now.
1- When this happen and the quote was never ended, go back to the char after and analyze as if it was not literal.

2- When this happen with a leftover quote, check the string, see if the final char was ) and consider it not literal if it was.
Easier but will surely have side effects

**Comment by Griatch** [comment]
@ChrisLR Yes, this is the exception that triggered the whole thing :) 
I don't think your 2. would be acceptable, it would lose everything after the `'` as treated literal. 
- One could either do as you suggest in your case 1, continue to the `)`, find that the `'` is still open and then go back again to run the loop again non-literal, or ...
- One could do a look-ahead to find the index positions of all `'`, `(` and `)` (you'd have to check for parenthesis too, since they could also open/close within the argument list) to determine if the current quote one has a closing match or not. This may or may not be faster, but it's also harder to reason around. 

Probably the first (your 1.) is the better solution here; it requires storing the `'`- position so you can go back to it and means a potential second pass, but the first pass is literal and thus should be quick, and it's still less complex than trying to do a comprehensive look-ahead.

**Comment by Griatch** [comment]
Investigating this further, there seems no real way to support single-quoted strings within the funcparser structure while keeping quotes optional for the user (which we want to do, for simplicitly. 

While it's possible to count single quotes to try to guess if the quote is a quote or an apostrophe, this would still make inputs like this impossible: 

    "$crop(The wizard's spider's wicked web, 5)" 

No matter what you do, `'s spider'` will be considered a literal. It doesn't matter in this particular case, but here's another: 

    "This is the $choice(spider's, devil's, mummy's, zombie's) curse!"

Here `s, devil` and `s, zombie` will be considered literal strings no matter how clever we design the `'`-parsing, because there is no way for the system to know the difference between this and 

    "This is $choice('Tiamat, queen of dragons', 'Dracula, lord of the night') we are talking about."

It seems the only way around this is to _not_ treat single quotes in funcparser funcs as literals at all - requiring double quotes. 

If I remove special treatment of single quotes, this problem goes away completely. The drawback is that it doesn't quite matches Python syntax anymore. But I think making it intuititive for this to be used matters more.
