### ISSUE TITLE
[BUG - Develop] EvForm strips *single* leading spaces on cells

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2759]
#### Describe the bug
When putting a string into an EvForm cell, if it begins with a single leading space, that space is stripped. If there is more than one leading space, all of the spaces are left intact.

#### To Reproduce & Expected Behavior
I put together a `formtest` command that demonstrates the issue: <https://pastebin.com/YdNpMdWX>

The expected form output is:
```
.-----------------------.
|       Test Form       |
|                       |
|. Hi.   . Single space |
|.       .  Double      |
|.       . Single again |
|        .              |
|                       |
 ----------------------- 
```
While the actual displayed form is this:
```
.-----------------------.
|       Test Form       |
|                       |
|.Hi.    .Single space  |
|.       .  Double      |
|.       .Single again  |
|        .              |
|                       |
 ----------------------- 
```
As you can see based on the anchor dots, the lines that are supposed to have a single leading space have _no_ leading space, while the line with the double leading space is printed correctly.

#### Develop-branch commit
f47c72317

**Comment by Griatch** [comment]
This was due to a particular way that `EvCells` calculate their alignments to better fit content in small widths. I have now refactored EvCell to make use of `utils.justify` to be more reproducible. Since the default for EvTable was `l` (left-aligned), the stripping of left whitespace is the correct result, and not-stripping two spaces is wrong. It now reliably strips in all situations. 

I made some changes to EvForm to offer more flexibility here: 
- Added the abillity to map `cells` kwarg to actual `EvCells`. This means one can pass cells with custom formatting options, so `cells = {1: EvCell(" Hi", align="a", valign="t")}`. 
-  I also added a new align kwarg to `justify` (and thus to `EvCell`)- `"a"` (absolute). The 'a' align-type aims to change as little as possible within a width - it retains all whitespace and will just crop/fill the line to `width`. This would reproduce your "expected" example above. This is particularly useful for EvCells used in EvForm.
- Updated Changelog and docstrings. Will likely write new EvForm/EvTable doc pages.
