### ISSUE TITLE
[BUG - Develop] `EvTable` adds two extra spaces to cell data

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2762]
#### Describe the bug
Regardless of width or padding settings, two extra spaces get added on to cell contents. These extra spaces get counted as part of the cell width, so it crops or wraps at len(contents)+2 instead of at len(contents).

#### To Reproduce
```py
colA = EvColumn("this","is","a","column")
colB = EvColumn("and","another","one","here",width=8) #shouldn't wrap anything, "another" is 7 long
table = EvTable(table=[colA,colB],fill_char='.',pad_char='#')
print(table)
```
#### Actual Output
```
+----------+----------+
|#this  ..#|#and     #|
|#is  ....#|#anothe  #|
|#........#|#r       #|
|#a  .....#|#one     #|
|#column  #|#here    #|
+----------+----------+
```
#### Expected Ouput
```
+--------+----------+
|#this..#|#and.....#|
|#is....#|#another.#|
|#a.....#|#one.....#|
|#column#|#here....#|
+--------+----------+
```
#### Develop-branch commit
f47c723

#### Additional context
When demonstrating the wrapping length, you can also see that it ignores the fill character when establishing width and uses a space instead. I think that caused by the same issue as #2761

**Comment by Griatch** [comment]
There were errors here, but not all of them are what it says in the ticket :) 
- The extra whitespace was weird; moving EvTable to use `utils.justify` (previous commits) already fixed this I think, I never saw this effect. 
- The `width` you provide to EvColumn is the width of the column, _including_ the padding and borders. You can see this clearer if you make a table with only one column - you then want to fit the column in a particular width (very important e.g. for EvForm) and the borders must thus also be included in it. The width available for your text is `width - padding - borders`. For a single column that's only 8 - 2 - 2 = 4. For a two-column table, the rightmost column shares a border with the column on the left and it's counted from the left, so width is 8 - 2 - 1 = 5. So there _should_ be no way for `another` (length 7) to fit on the line. The question was rather why your right column is 11 characters wide when it should be 8. 

I've fixed this now, here's what is going on, and what changed

- I did a lot more unit testing (EvTable was voefully un-tested until now; surprising - I thought it had more).
- There is no support for passing `EvColumns(table=[colA, colB])`. `table=` takes a list of lists - of strings only. It still works, because EvTable's `__str__` means it will work as a string, but this is the main reason for the extra length; the column has its own length-calculation, so when you ask it for its width, it will include more stuff than the system expects. 
- That said, it looks so natural to be able to add columns this way that it took me a long while to figure out that this is not supported behavior ... :sweat_smile: So I have now added support for it; you can now do `table=[colA, colB]` and it should work as expected. 

For completeness, the correct expected outcome is this: 
```
+--------+-------+                                                                                 
|#this..#|#and..#|                                                                                 
|#is....#|#anoth#|                                                                                 
|#......#|#er...#|                                                                                 
|#a.....#|#one..#|                                                                                 
|#column#|#here.#|                                                                                 
+--------+-------+
```
