### ISSUE TITLE
[BUG] SET command strips capitals from dictionary keys

### ISSUE THREAD

**Issue by Tegiminis** [evennia/evennia#2795]
#### Describe the bug
The default SET command strips capitals from dictionary keys, which causes it to fail when attempting to set a dictionary value which has them, instead creating a new attribute with the name `attr['key']`

#### To Reproduce
1. Create a dictionary attribute on yourself named `foo` with the key `FooCap` and the value `3` through `py` or code
2. Attempt to set the dictionary value using the SET command (`set self/foo['FooCap'] = 5`)
3. Observe creation of new attribute instead of modification of existing attribute

#### Expected behavior
SET should not strip capitals from dictionary keys.

#### Environment, Evennia version, OS etc
1.0 dev

#### Additional context
You have to go through `py` or a code path when creating the CamelCase dictionary key in order to repro this bug, as using SET to create the attribute in-client strips the capitals.

**Comment by Griatch** [comment]
I can see the issue since we do enforce Python-style for dicts, and Python is case-sensitive. So this needs to be fixed. 

(As a side note though - Python style is to use lower case for all keys, properties and variables ... and the same can be be said for keys stored in Attributes ... there's very rarely a need to use upper-case letters in any dict keys unless you are deliberately storing some item name in there ...)

**Comment by aogier** [comment]
fix implemented in #2820, should add some more tests maybe

**Comment by aogier** [comment]
fixed in 0b8c6e294dc0b8aa2ca7e908529ab35516af9a1e
