### ISSUE TITLE
[Feature Request] Incremental builds of documentation

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2893]
#### Is your feature request related to a problem? Please describe.
Building the docs takes too long and isn't incremental.

#### Describe the solution you'd like
The makefile should look at actual files that have changed and dependencies, instead of always doing a "clean" and rebuilding from scratch. The `sphinx-build` command already supports this, but it is ruined by the fact that `make local` does a `clean`.

#### Alternatives you've considered
None.

#### Additional context
Makefiles by default support the basic concept of specifying dependencies for outputs. For example, the `.html` files depend on `.rst` files and `_static` files. If any of the input files are newer than the output files, make will regenerate them using the rules described. However, the current documentation Makefile seems to be more of a way of organizing a collection of shell scripts.

If it was possible to do an incremental build, changing one `.md` file would result in only one (or maybe a few) `.html` files being built. This would speed up documentation editing/development by maybe 100x and should encourage more documentation contributions.

**Comment by audiodude** [comment]
I see now that there is a `localupdate` command. Let me experiment with that.

**Comment by audiodude** [comment]
It seems `localupdate` still takes 30 seconds to run even when I haven't updated anything. This could probably be optimized, but I'm not sure it's worth it.

**Comment by Griatch** [comment]
Since I've been the only one to build the docs so far, I've not optimized it much. There are some custom checkers and converters running before the actual sphinx builds; these do run on all docs, not only on the last-changed ones so they could in principle be optimized. Not sure it's something I'll spend time on at this time though. 
Overall, for quick tests of doc building `make localupdate` or (if you already have the api index), `make quick` are the ones to use.

**Comment by Griatch** [comment]
Some extra time is required to go through the custom checks and auto-generated files the doc system generates. It's probably not worth it to optimize this further this time, so closing this.
