### ISSUE TITLE
[BUG - Develop] Evennia can no longer create global scripts from settings.py

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2915]
#### Describe the bug
As of merging #2882 any attempt to create a new game with global scripts defined in settings does not create the script. It simply fails the assertion check and moves on without attempting to create them.

#### To Reproduce
1. Set up a new freshly-made game with `GLOBAL_SCRIPTS` defined in the settings. (I included what I used at the bottom.)
2. Attempt to start the game.

#### Expected behavior
It's supposed to automatically create the script if it doesn't exist.

#### Develop-branch commit
b0f24f997

#### Additional context
```py
# added to typeclasses/scripts.py
from evennia.utils import logger

class TestScript(DefaultScript):
    key = "global_test_script"

    def at_repeat(self):
        logger.log_msg("This just prints a nice message.")
```

```py
# added to server/conf/settings.py
GLOBAL_SCRIPTS = {
    "global_test_script": {
        "typeclass": "typeclasses.scripts.TestScript",
        "persistent": True,
        "interval": 60,
        "desc": "A simple script to test creation.",
    },
}
```

```
2022-10-08 04:42:58 [!!] Traceback (most recent call last):
2022-10-08 04:42:58 [!!]   File "./evgames/evennia/evennia/utils/containers.py", line 214, in load_data
2022-10-08 04:42:58 [!!]     assert issubclass(script_typeclass, _BASE_SCRIPT_TYPECLASS)
2022-10-08 04:42:58 [!!] AssertionError
2022-10-08 04:42:58 [!!] GlobalScriptContainer could not start import global script global_test_script. It will be removed (skipped).
```

**Comment by Henddher** [comment]
Yeap! that's due to #2882. I'll take a look.

**Comment by Henddher** [comment]
Hi @InspectorCaracal

This is the problem:

At `evennia start`, we load and "cache" `settings.BASE_SCRIPT_TYPECLASS`. However, in your example, `TestScript` does **not** derives from `typeclasses.scripts.Script` so the assertion triggers and the script gets skipped. Because your `TestScript` is subclassing `DefaultScript` which is **not** what `settings.BASE_SCRIPT_TYPECLASS` expects.

```
> /home/henddher/Documents/github/evennia/evennia/utils/containers.py(207)load_data()
-> _BASE_SCRIPT_TYPECLASS = class_from_module(settings.BASE_SCRIPT_TYPECLASS)
(Pdb) p settings.BASE_SCRIPT_TYPECLASS
'typeclasses.scripts.Script'
```
I modified your example to `class TestScript(Script): ...`, retried it and worked (as expected?). One may argue that this is WAI (I wouldn't either way :wink:)

Now, the issue at hand is the following:

Is the `assert`ion too stringent or should it be relaxed to just `assert issubclass(typeclass, DefaultScript)`?

https://github.com/evennia/evennia/blob/b0f24f9975e14fddeabef06a19b5b61575957b1c/evennia/utils/containers.py#L212-L214

Semantically, what's the meaning of `settings.BASE_SCRIPT_TYPECLASS`. Is this an unbreakable contract or a "nice" default that can be circumvented?

Maybe others want to chime in?

**Comment by InspectorCaracal** [comment]
Thanks. It looks like that's the cause for my game's code, as well.

> Semantically, what's the meaning of settings.BASE_SCRIPT_TYPECLASS. Is this an unbreakable contract or a "nice" default that can be circumvented?
To the best of my knowledge, it's intended to represent the default typeclass. If a script's typeclass module has an error, it'll load it in with that base typeclass instead, and if there's no typeclass passed when creating a script, it'll create it with that base typeclass.

That said, with the exception handling you added, I don't think the assertion is needed at all. `class_from_module` will raise an import error if it fails to import, so it'll be caught and the key will be removed.

**Comment by Henddher** [comment]
> To the best of my knowledge, it's intended to represent the default typeclass. If an already-existing script's typeclass module has an error, it'll load it in with that base typeclass instead [...]

But if the class no longer exists for an already-existing script, using a completely different class (no matter which one in the DefaultScript hierarchy) would likely produce undesired results. 

... that actually makes me wonder ... when I tried to reproduce this issue, the server started to fail loading because scripts with bad classes (badscript.py I used for testing) was no longer in my typeclasses directory. So I think it didn't try to use any other class and it just failed.

IMHO, as I hinted in the PR, the options at this point should be to either relax the `assert` or leave it as is. I would argue against removing it. I'd argue that the value of keeping it (in either flavor) would compensate for when one creates a script that is invalid (i.e. not subclassing `DefaultScript`). The fact that `class_from_module` successfully loads a class does not guarantee that the class is a `DefaultScript` (or subclass of) - which *is* a main requirement.

**Comment by InspectorCaracal** [comment]
> > To the best of my knowledge, it's intended to represent the default typeclass. If an already-existing script's typeclass module has an error, it'll load it in with that base typeclass instead [...]
> 
> But if the class no longer exists for an already-existing script, using a completely different class (no matter which one in the DefaultScript hierarchy) would likely produce undesired results.

Yes, and you get a warning/error message about it if it happens. It's not supposed to be a usable state, it's a fallback state when there's an error.

**Comment by Henddher** [comment]
The assertion in this case is also showing an error message. The only difference is that it *skips* the "bad" script and continues with all others. Technically, doesn't fall back the "bad" script to anything.

I don't have a strong preference either. I just think that the assertion adds an extra check that we didn't have before and it catches a problem much earlier than before.

TBH, I have not tried removing the assertion and using `BadScript` and/or `WorstScript` from `test_containers.py`. Worth trying and seeing what the outcome is. I agree that removing the assertion would be easier but how much would it help in this case? I'd like to try it to see what happens exactly and *when*.

**Comment by Griatch** [comment]
I missed this in the review - the assertion should be removed; BASE_SCRIPT_TYPECLASS is a fallback as @InspectorCaracal said, there should be no requirement to base all your scripts on it. 

If you provide a malformed script, it should give a traceback in log and not be loaded.

**Comment by Henddher** [comment]
I'll remove the assertion and update the PR. I might even reuse the test I added and just verify that the outcome is different (i.e. that the questionable script is *not* skipped).

I just noticed the PR was closed? I will try to repurposed it.

**Comment by Griatch** [comment]
@Henddher I closed the PR since it wouldn't merge in its state. If you prefer to rework it rather than make a new one, I can reopen the PR again.

**Comment by Henddher** [comment]
Nah, it's ok. I am pushing a new one and citing the closed one. I do wonder what's an accepted etiquette in cases like this.

I think that keeping conversations in PRs as they evolve is useful. In this case, since it's going 180 in the opposite direction, it may be a bit tricky because it might cause confusion. Although with the insights I'll provide in the new one, it may have been useful to keep all in the same PR. We'll see :smile: 

No worries @Griatch :+1:
