### ISSUE TITLE
[BUG - Develop] Commands don't replace each other if aliases differ

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2938]
#### Describe the bug
(I'm not sure if this is a bug or intentional, so I figured I'd go the safe route and report it anyway.)

When adding a command to a base cmdset that has the same key, but additional aliases, to a pre-existing command, the merge *does not* override the old command. Instead, both commands are present and indistinguishable.

#### To Reproduce
1. Start with a fresh game, and make your own `say` command. (It can just inherit from core.)
2. Give this command a key of `say` and aliases of `('"', "'", "whisper", "shout",)`
3. Add it to your default Character CmdSet
4. Reload and try to `say` something.
5. See error

#### Expected behavior
I expected my new command to override the old one since it has an identical key, regardless of having additional aliases. If there were aliases on the original command that I didn't keep on my new one, it might make sense? e.g. if I had removed the single- and double-quote aliases? But since I only added extra aliases, I feel like it *should* completely override the pre-existing command when added.

#### Develop-branch commit
b0f24f997

**Comment by Griatch** [comment]
Hm, this doesn't sound right.

**Comment by InspectorCaracal** [comment]
Yeah I didn't think it did, either.

Maybe it's an unintentional side-effect of implementing the ability to remove commands by key? _That_ works great, now.

**Comment by Griatch** [comment]
What happened here was that the new `say` command found a match and replaced the `whisper` command (which also exists) and then aborting the loop and not touching the original `say` command. I found when testing this that it _sometimes_ replaced the whisper and sometimes the `say` since both are equivalent based on key + aliases. I also found a hashing problem that meant the `set(commands)` didn't properly identify the same commands, so the duplicates were not wiped in that operation either. 

I have now made sure that the last-added command in a cmdset replaces all previous matches. Also fixed the hashing so there should be no more spurious duplicates like this.
