### ISSUE TITLE
[BUG] No way to refer to a name if it contains color codes

### ISSUE THREAD

**Issue by Oreolek** [evennia/evennia#3074]
#### Describe the bug
It is possible to use color codes and formatting in names and `sdesc`, making them fancy like  **a**d**m**i**n**

These handles become impossible to refer to because you can't eyeball which of 256 colors were used for each letter and how. (Copying strips the formatting.)

#### To Reproduce
```
name admin = |ra|ndmin
look admin
```

#### Expected behavior
Strip formatting from object names during the lookup so it would use plain UTF-8. (Unicode is still full of 0-width pitfalls but at least you can copy them.)

#### Environment, Evennia version, OS etc
Evennia 1.0.2, python 3.10.6

**Comment by InspectorCaracal** [comment]
The rpsystem contrib will strip all color codes from sdescs by default when adding them because it doesn't support color codes within the sdesc lookups - this is about the object's key having a color when there is no sdesc set.

That said, I think proper handling of colored names would be a useful feature to support.

**Comment by Griatch** [comment]
Adding color codes to an object's `key` is not a good idea overall, that will mess up your general search too. This is what the  `.get_display_name()` is for.
