### ISSUE TITLE
[BUG] nattribute (.ndb) reference to deleted object clings to life

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3087]
#### Describe the bug
Using a .ndb attribute to reference an in-game object, then deleting that object, results in the .ndb attribute 'partly' remaining. In my opinion, if it is possible to use a .ndb attribute to reference an object, the attribute should accurately map to said object.

#### To Reproduce
1. Have two items (say, yourself and an apple)
2. Set `self.ndb.apple = apple`
3. `delete apple`
4. Check `self.ndb.apple`
5. Check `self.ndb.apple.get_display_name(self)`
6. Check `self.ndb.apple.id`
7. Check `type(self.ndb.apple)`
8. Notice errors/inconsistency above: self.ndb.apple still appears to be the apple, .id returns nothing, type() returns the correct type that the apple _was_, back when it existed. 

#### Expected behavior
In this case I believe .ndb should function the same as .db, even though I know they're completely different systems; when the original object is deleted, the reference is too. 
How .db works:
1. `self.db.apple = apple`
2. Delete the apple
3. Check `self.db.apple`
4. Notice `self.db.apple` no longer exists

#### Environment, Evennia version, OS etc
1.1.0 (rev c8846eb5f5)

#### Additional context
I know that InMemoryAttributes (aka nattributes) do not have a database backend, so it seems unlikely that there's going to be an easy way to check "hey, was this in-memory attribute supposed to exist in the database in the first place - and does it still?"... I looked at the InMemoryAttribute class and haven't the foggiest idea how you'd go about fixing this.

If it's not doable, maybe in big letters in documentation somewhere put "Don't save Object References In Non-Database Attributes"

Current [attribute/nattribute documentation](https://www.evennia.com/docs/latest/Components/Attributes.html):
> "Trying to access a non-existing Attribute will never lead to an AttributeError. Instead you will get None back. [...] NAttributes [...] mimic Attributes in most things"

**Comment by Griatch** [comment]
It's very convenient to store objects in `.ndb`, but the main reason for doing it is to be able to track them (Evennia can take them into account for cache cleanup operations, and they will show up with `examine` for example. They are otherwise functionally no different from storing data in a normal Python property, `.foo = my_obj` - which would run into the same issue. 

For ndb to know that your database object was deleted, it would have to be, well, db-aware. Which would mean having to analyze the data for every retrieval (looping through all iterables recursively) to find db-objects and check if their `.pk` is still set or not. And even then, you could miss some that were "hidden" inside a custom class. 
The `.db.` handler don't cache its contents for this same reason - it checks the db every time you call it, just to make sure. The `.db` cost is known though, that's part of the cost of using it. I feel like adding the same check to `.ndb` invalidates the use of `.ndb`. 

One shouldn't discourage saving object references in ndb, there are a lot of very valid use-cases for doing so, for speed etc. I've never had an issue with this myself, but it depends on the way it's being used. We could expand in the docs that one do need to properly handle the case of deletion, or check that the object still exists if it is in risk of having been deleted in-between.

**Comment by aMiss-aWry** [comment]
Fair enough - but given that, what's the easiest way to check that the object still exists? As if you actually use the .ndb reference, to all intents and purposes it'll appear to (besides not having an .id - is that the way?)

**Comment by Griatch** [comment]
Yes, the primary key existing is the way to check: 
```python
dbobj = self.db.mydbobj 
if not dbobj.pk:
     dbobj = None 
```

**Comment by Griatch** [comment]
Mentioned this more in the docs now.
