### ISSUE TITLE
[BUG] Incorrect implementation (or docstring?) on `ServerSession.get_account` and `ServerSession.get_puppet`

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3100]
#### Describe the bug
On the `ServerSession` class, both `.get_account()` and `.get_puppet()` claim in the docstring that they return the account, or the puppet, if such a thing exists on the session.

However, the actual code returns a boolean.

Based on the names of the functions, I think this is an implementation error, not a documentation error, and the code should be updated to return account-or-None and object-or-None, respectively.

#### Additional context
https://github.com/evennia/evennia/blob/bee281f82d126482f0acb8e3ea4153cba0ad4779/evennia/server/serversession.py#L153-L171

**Comment by Griatch** [comment]
Thanks for the report! Not sure if there's some confusion here though - these methods _don't_ return just a boolean - they return either `False` _or_ the expected `Account`/`Puppet`. This is because of how logical operators work:

```python
>>> result = True and "Foo"
>>> print(result) 
Foo
```
I guess it could be considered a little more clean (and in line with `get_puppet_or_account`) to return `None` when no account/puppet is available though. So I updated it to do that. :slightly_smiling_face:
