### ISSUE TITLE
[Documentation] Incorrect tickerhandler documentation

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3148]
#### Existing page / new
[TickerHandler](https://www.evennia.com/docs/latest/Components/TickerHandler.html)

#### Documentation issue
> The full definition of the tickerhandler.add method is
> ```
>    tickerhandler.add(interval, callback, 
>                      idstring="", persistent=True, *args, **kwargs)
> ```
> Here `*args` and `**kwargs` will be passed to `callback` every `interval` seconds. **If `persistent` is `False`, this subscription will not survive a server reload.**

As per [this comment](https://github.com/evennia/evennia/issues/3147#issuecomment-1474817791), the bolded statement is incorrect and needs to be changed to indicate that it will not survive a server *shutdown*, but it will still continue to be saved across a server *reload*.

It should also, in my opinion, indicate that this behavior is unique to the tickerhandler, as other uses of "non-persistent" in the code do in fact mean it won't save across reloads, so it could be confusing to new users to come across the tickerhandler definition first and then expect e.g. `.ndb` attributes to survive across reloads.

**Comment by Griatch** [comment]
Yes, it's explained in the docstring of `TicketHandler.add` itself,  but looks like it's wrong in the docs. 

The tickers are actually in a pool, shared between all tickers - that's the optimization of using tickers in the first place. Non-persistence works like Scripts do - they always gets saved to the database, but deleted on demand on start. Since it must go through the database anyway,  making a ticker wipe on reload is is not that useful as a concept.

**Comment by InspectorCaracal** [comment]
That's fine; I was following the documentation here and it was wrong, is all.
