### ISSUE TITLE
[Documentation] Problems With EquipmentHandler Implementation In EvAdventure

### ISSUE THREAD

**Issue by Nolshine** [evennia/evennia#3151]
#### Existing page / new
[5. Handling Equipment](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Equipment.html)

#### Documentation issue
There are a couple of issues with implementations of features starting at section 5.3, which can really interfere with beginners trying to move forward. (This is for the tutorial demonstrating how to build EvAdventure specifically, not the associated contrib.)
I will describe them both here for brevity:

1. The method `EquipmentHandler.validate_slot_usage()` is called in `Equipment.Handler.add()` but the return value isn't actually used to validate anything.
2. The method `EquipmentHandler.remove()` takes in an inventory slot as an argument. In the implementation of `EquipmentHandler.move()`, it is called with an object instead, and the rest of the implementation is built on top of that.

#### Suggested change

1. `EquipmentHandler.add()` should probably use something like: 
```Python
if not self.validate_slot_usage(obj):
    return
```
2. The implementation of either `remove()` or `move()` needs to change so they are both consistent with each other.

**Comment by Griatch** [comment]
This is originally because the implementation in code is slightly more intricate than what is in the tutorial text; the `validate_slot_usage` raises an exception, which allows for showing some more details to the user; but it adds a lot of cruft to the tutorial, so it's a bit simplified there, and some things were not properly converted it seems. I have adjusted the tutorial now, thanks!
