### ISSUE TITLE
[BUG] Version conflict when running the EvAdventure commands

### ISSUE THREAD

**Issue by Markar** [evennia/evennia#3220]
#### Describe the bug
If you copy the EvAdventure directory into your project, you end up with this error: 

RuntimeError: Conflicting 'evadventurequestobject' models in application 'objects': <class
'gamedir.objects.EvAdventureQuestObject'> and <class 
'evennia.contrib.tutorials.evadventure.objects.EvAdventureQuestObject'>.

#### To Reproduce
1. Copy EvAdventure to a new fresh evennia --init project
2. Try to set type `type self = evadventure.characters.EvAdventureCharacter`
3. See conflict error.

#### Expected behavior
The EvAdventure files should be able to run as a "base mud" when copied into a new fresh Evennia install.

#### Environment, Evennia version, OS etc
Windows (WSL:Ubuntu)

#### Additional context
Resolved by renaming all EvAdventure prefixes with another prefix, then setting type to that renamed type:
`type self = evadventure.characters.MyCharacter`

Additionally, as setting the type is required for anything to work, and is only mentioned early in the tutorial, that should probably be mentioned somewhere for setup.

**Comment by Griatch** [comment]
This is not technically possible; I have not written about this explicitly in the tutorial yet, but the explanation is here: https://www.evennia.com/docs/latest/Components/Typeclasses.html#difference-between-typeclasses-and-classes. Basically this is because Typeclasses must be globally unique, so having two same-named classes (one in core Evennia, and the other copied into your game dir) will not work. 

You will need to rename the copied classes or inherit from them rather than copy things wholesale. We may offer a game-dir version of the tutorial at some point (in a separate repo), but this would still need to have differently-named classes for this reason.
