### ISSUE TITLE
[Feature Request] Support for color beyond XTERM256

### ISSUE THREAD

**Issue by 11Spades** [evennia/evennia#3248]
When I make a room or item, I like to *really* color them up. Unfortunately, XTERM256 occasionally lacks the range required for me to express my idea in full. To remedy this, I'd like to propose support for full RGB color. I've implemented this before on an LP MUD, and know that at least Mudlet can handle it nicely.

Unfortunately, I am not very familiar with the Evennia codebase, but if someone could direct me to the components that handle color code -> ansi code replacement, I'd be happy to take a crack at it myself.

**Comment by Griatch** [comment]
I think this sounds interesting. What you are talking about sounds like an extension to the `|r` and `|345` style syntax, which would be interesting to have. Some questions and points: 

- Could you give some examples for how the syntax would look, for Evennia? I take it this would be a core addition, or are you picturing it as a contrib? 
- Is there a Telnet protocol standard (well, as standard as MUD Telnet extension go) for clients to use - if so, do you have a link to the spec? 
- Webclient support would require updating / adding logic to convert this to CSS on the server level (and in the future on the client level when we get to implement the requirements of [PR 3185](https://github.com/evennia/evennia/pull/3185)).

**Comment by InspectorCaracal** [comment]
I'm not the OP, but for my game, I added full RGB support using hex code syntax, like so:

`|#ff8800this is orange text|n`
![image](https://github.com/evennia/evennia/assets/51038201/48911361-8210-498b-95ff-0da4e08baf13)

Personally I find the syntax works nicely with the existing Evennia syntax and I figure it would be easy to pick up, since virtually everyone is familiar with hex color codes by now.

(I never managed to find an answer to "what's the accepted way of sending RGB via telnet", myself, but hopefully the OP knows.)

**Comment by 11Spades** [comment]
>Could you give some examples for how the syntax would look, for Evennia? I take it this would be a core addition, or are you picturing it as a contrib?

The syntax that @InspectorCaracal is using is the syntax I had in mind -- this is most akin to how I implemented it elsewhere.

>Is there a Telnet protocol standard (well, as standard as MUD Telnet extension go) for clients to use - if so, do you have a link to the spec?

I'm unsure as to whether you're referring to a standard for figuring out whether the client supports RGB color (True Color) or a standard for displaying True Color.

In the former case, [this page](https://tintin.mudhalla.net/info/truecolor/) is as close as I can find. I've implemented this previously for another MUD, and we had users manually select their color set, so I'm afraid this territory is unfamiliar to me.

In the latter case, most modern clients (2012 and onward) should support the ANSI escape codes requisite for True Color to be displayed. I can personally confirm that Mudlet supports True Color, but CMUD/ZMUD do not.

>Webclient support would require updating / adding logic to convert this to CSS on the server level (and in the future on the client level when we get to implement the requirements of https://github.com/evennia/evennia/pull/3185).

I suspect that this would be a trivial change, but am admittedly unfamiliar with the architecture of Evennia's code. I would be happy to learn, though.

>And, while I don't *personally* have the shorthand `#f80` syntax implemented, it would be pretty easy to add in, I think?

I'd have to imagine that it'd be relatively easy to implement the shorthand alongside full hex codes. In for a penny, in for a pound.

>I never managed to find an answer to "what's the accepted way of sending RGB via telnet", myself, but hopefully the OP knows.

The only way that I am familiar with coloring text over telnet involves sending ANSI escape codes to the client, which is how I'm envisioning we go about this. If there's another way, I'd be happy to go out hunting for a way to send RGB color in a similar manner.

**Comment by Griatch** [comment]
Yes Xterm Truecolor would work fine and is in line with the existing workings of the telnet module.
For the webclient, one would need to add a dynamic remap to CSS, but yeah,  that would be simple if you already have hex notation.

I'm also fine with using a |hex notation; it also sounds like Caracal can probably help bootstrap that part of the implementation if so needed. 

So if you are up for taking this on,  I'd be happy to see it!

**Comment by 11Spades** [comment]
Stellar!

@InspectorCaracal If you'd be comfortable providing what code you already have for this, I'd love to start work from it. If not, don't sweat it.

I'll try to have a PR ready within the week -- I'm juggling a few projects right now :P

**Comment by InspectorCaracal** [comment]
Sure! [Here's a pastebin with my color handling code](https://pastebin.com/pa37qGFw).

The `ev_to_html` fits the same functional spot as the core `text2html` (which [you can find here](https://github.com/evennia/evennia/blob/2bb23b2550e731971dcb1a5393c5fab0ee655623/evennia/utils/text2html.py#L4)), but it's designed to work specifically with my custom webclient protocol. It should still be useful as a reference, however.

The main implementation difference client-side is that, rather than implementing a custom class for every single xterm color, I use variables for the core ANSI palette codes, convert XTERM256 to hex, and then apply the colors directly with the `color` and `background-color` CSS properties directly, which is much simpler to manage than swapping classes but would be a major breaking change in the webclient.

I also personally use a fallback chain on telnet (convert to xterm for the telnet protocol, then rely on evennia's handling of xterm256-to-ansi16 fallbacks if needed), rather than trying to send RGB through telnet, but if there's an ANSI code syntax for RGB colors it would be pretty trivial to add one more conversion function into the process.

**Comment by friarzen** [comment]
There is a gotcha corner case here to make sure you are aware of.

|333 Xterm-256 notation with a message that then starts with 5 digits and would *parse* like a hex color value.

**Comment by 11Spades** [comment]
> There is a gotcha corner case here to make sure you are aware of.
> 
> |333 Xterm-256 notation with a message that then starts with 3 or 5 digits and would _parse_ like a hex color value.

This is a good catch!

I intend to only parse hex values if they begin with a `#`.

**Comment by Griatch** [comment]
@11Spades Ping, just checking what the status of this one is. :)

**Comment by Griatch** [comment]
Since @11Spades is not responding, maybe someone else would be willing to take this on, maybe in Hacktoberfest?

**Comment by michaelfaith84** [comment]
I was thinking about taking this on but it looks like #3253 will address this. Thoughts?

**Comment by Griatch** [comment]
This was implemented as full RGB hex colors in #3494.
