### ISSUE TITLE
[Feature Request] A full "reboot" command in-game

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3443]
#### Is your feature request related to a problem? Please describe.
At the moment, and resisting the urge to complain about unintuitive verbs, we have three available commands regarding reloading the server from in-game:

1. `reload`, which is equivalent to `evennia reload` from command line
2. `reset`, which is equivalent to `evennia reset` from command line
3. `shutdown`, which is equivalent to `evennia stop` from command line

However, we do not have any equivalent to `evennia reboot`. In other words, there is NO way to reboot the PORTAL from within the game. Only to shut it down completely.

I consider the use for *fully rebooting the game* from within the game rather than the command line to be significantly higher than *fully shutting it down*, since the latter requires you to go back to the command line to start the game back up anyway? But we can only shut it down, not fully reboot it.

#### Describe the solution you'd like
I would like a command to be added to provide this functionality. The "fake reboot" provided may emulate a cold boot on the server, but it is completely useless for reloading the portal, and I need to reload the portal much more often than I need to pretend the server is cold starting (as the number of times I've needed to do the latter is literally zero).

#### Additional context
A bit of a side note, but relevant: the fact that "reboot" is aliased to `CmdReset`, a.k.a. the "fake reboot", and is not at all the same functionality as `reboot` is used in the command line, is confusing at best, but disingenuous and explicitly misleading at worst.

**Comment by Griatch** [comment]
This is not really possible. A reboot means a shutdown of the portal, which is the same thing you are connecting through to execute the command. If executing this from inside the game, there will be nothing left to restart the portal afterwards. 

A reboot can be done from the command line because a third process (the evennia launcher) is controlling the shutdown process - it controls that the portal shuts down and afterwards spins it up again, fascilitating the reboot. To do something similar from in-game, the portal would need to somehow spin up a new third process, offload all control to it and make sure it then reboots the portal once the old portal process has died. I suppose it's possible, but hardly worth the effort. 

I can agree that the `reboot` alias is misleading though. I'll remove that.

**Comment by InspectorCaracal** [comment]
@Griatch Ahhh, I see. So the command-line reboot is using an external process (the launcher) to do the portal shutdown and relaunch?

**Comment by Griatch** [comment]
Correct. A reboot is literally a full shutdown + a start run in sequence.
