### ISSUE TITLE
[BUG] The 'create' command does not create plural aliases on the object

### ISSUE THREAD

**Issue by chiizujin** [evennia/evennia#3473]
#### Describe the bug

When creating objects with `create` or `create/drop` the object is created with no plural aliases. These only get created when the object is referred to by other command (via `get_numbered_name`). `examine` does  not cause them to be created.

#### To Reproduce

```
>create thing
You create a new Object: thing.
>ex thing
-------------------------------------------------------------------------------------
Name/key: thing (#169)
Typeclass: Object (typeclasses.objects.Object)
(...)
```
```
>drop thing
You drop a thing.
>ex thing
-------------------------------------------------------------------------------------
Name/key: thing (#169)
Aliases: a thing,one thing
Typeclass: Object (typeclasses.objects.Object)
(...)
```
```
>create/drop another thing
You create a new Object: another thing.
>ex another thing
-------------------------------------------------------------------------------------
Name/key: another thing (#170)
Typeclass: Object (typeclasses.objects.Object)
(...)
```
#### Expected behavior

I'm not sure if the the intended behaviour or not but is does make it possible to have objects in existence that can't be referred to by their plural alias until they have been interacted with. Admittedly, it's probably not very likely that builders will leave `create/drop`ped items lying around to cause confusion.

**Comment by Griatch** [comment]
This is an intentional design originally intended to speed up creation; even looking at the object (or looking at the location with the object in it) should trigger the `get_numbered_name` and automatically create the aliases. 

I can see that it may feel arbitrary when working with these objects in code though. I have been wondering if there are better ways to do this than per-object aliases, honestly - like making the search functionality understand plural forms or something ...

**Comment by chiizujin** [comment]
That's fair enough then, at least I know it's not a bug.

I've messed about with parsing for this sort of thing before and it can get messy. I'm certainly not equipped with enough Evennia knowledge to fiddle with it here.
