### ISSUE TITLE
[Documentation] Incorrect description of AttributeProperty behavior in the Tutorial

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#3581]
#### Existing page / new
[Beginner Tutorial - In-game Objects and Items](https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Objects.html)

#### Documentation issue
The problem paragraph:
> To make this a little more efficient, we use autocreate=False. Normally when you create a new object with defined AttributeProperties, a matching Attribute is immediately created at the same time. So normally, the object would be created along with two Attributes size and value. With autocreate=False, no Attribute will be created unless the default is changed. That is, as long as your object has size=1 no database Attribute will be created at all. This saves time and resources when creating large number of objects.

This is not how AttributeProperties behave - they do *not* create a matching Attribute immediately. They only create it when accessed. There's been an ongoing issue with having to explain to new evennia devs that AttributeProperty doesn't automatically create the attribute and I suspect this paragraph is contributing to the issue.

#### Suggested change
It should instead be made clear that it's created when the property is accessed, not when the object is created.

**Comment by Griatch** [comment]
:thinking: Actually, this is a true statement because of the [init_evennia_property() method](https://github.com/evennia/evennia/blob/main/evennia/typeclasses/models.py#L345) which is called by the `at_first_save()` signal handler whenever a test is first saved (that is, created for the first time). It basically does a dummy `__getattribute__` on the property just to allow the `autocreate=True` to create a new Attribute. 

We have unit tests that shows this works, and it also works in practice: 

```python
# in typeclasses.objects
from evennia import AttributeProperty
class DummyObject(Object):
    x = AttributeProperty(default=123)
    y = AttributeProperty(default=456, autocreate=False)
```
In game
```shell
> create/drop dum:objects.DummyObject
> py self.search("dum").attributes.get("x")
123
> py.self.search("dum").attributes.get("y")
(None result)
```

I thinks this confusion could come from some other source? For example if you were to change the `default` after the object was first created, this won't update the underlying Attribute (since this is created only on first save).
