### ISSUE TITLE
[BUG] SimpleDoor example throws An untrapped error

### ISSUE THREAD

**Issue by fellanonymous** [evennia/evennia#3670]
#### Describe the bug
After following the steps included in the documentation here: https://www.evennia.com/docs/latest/Contribs/Contrib-Simpledoor.html?highlight=door I receive an AttribueError. `AttributeError: 'NoneType' object has no attribute 'locks'`

#### To Reproduce
1. Add `self.add(simpledoor.SimpleDoorCmdSet)` to `~/commands/default_cmdsets.py`
```
class CharacterCmdSet(default_cmds.CharacterCmdSet):
    # ...
    def at_cmdset_creation(self):
        # ...
        self.add(simpledoor.SimpleDoorCmdSet)
```
2. Reload server using `reload`
3. Dig a new room using `dig otherroom`
4. Create a new doorway using `@open doorway:contrib.grid.simpledoor.SimpleDoor = otherroom`
5. Open doorway using `open doorway` and close doorway using `close doorway`
6. Tying `open doorway` says `doorway is already open`, but typing close doorway throw this error at me.
```
Traceback (most recent call last):
  File "C:\Users\mdaga\AppData\Local\Programs\Python\Python312\Lib\site-packages\evennia\commands\cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "C:\Users\mdaga\AppData\Local\Programs\Python\Python312\Lib\site-packages\evennia\contrib\grid\simpledoor\simpledoor.py", line 187, in func
    door.setlock("traverse:false()")
  File "C:\Users\mdaga\AppData\Local\Programs\Python\Python312\Lib\site-packages\evennia\contrib\grid\simpledoor\simpledoor.py", line 76, in setlock
    self.db.return_exit.locks.add(lockstring)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'locks'

An untrapped error occurred.
```

#### Expected behavior
I'm not 100% clear what is supposed to happen as I've never gotten this to work, but I'm assuming it should open the door object to allow the player character to travel through the keyword `doorway`.

#### Environment, Evennia version, OS etc
```
    Evennia 4.4.1
    OS: nt
    Python: 3.12.7
    Twisted: 23.10.0
    Django: 4.2.16
```

**Comment by Griatch** [comment]
I cannot reproduce this :confused: 

I tried to reproduce by following exactly your steps (and the steps of the documentation); The only extra step is that the doorway won't work out of the box if you are a superuser (you need to `quell` if you are a superuser since the doorway works with locks which a superuser will otherwise bypass). What happens for me (and is supposed to happen) is that you `close` the doorway and then you won't be able to pass through it (from either side) until you `open` it again. 

Your error suggests that the other side's doorway didn't create properly (the `return_exit` Attribute of the door is `None`). To investigate, try `ex doorway` to see which typeclass the doorway is (and if it has a `return_exit` Attribute), then pass through to the other side and check the same for the other side. If you see the one of the sides is missing data, try to open another doorway2 and look at your logs to see if you see any errors.
