### ISSUE TITLE
Feature Request: Sex and Pronouns

### ISSUE THREAD

**Issue by n0q** [evennia/evennia#528]
It would be convenient to specify a character's gender and use it to link into a series of pronoun functions. This would be used by builders to tailor messages to an enactor's gender.

John swings his sword at the orc, but misses.
Alice falls from the sky and lands on her face.
Robotic Soldier repairs itself.

It's useful to MUDders, RPers, and talkers, and seems like it belongs in base.

Male, Female, and Neuter are sufficient, with Neuter being the default. Something simple like `@sex me=male` would suffice, and is already a real MUX command. Then we'd need a way to take advantage of the setting. For reference, this is how MUX does it, taken from `help substitutions2`:

Pronoun-related substitutions:

    %s, %S   Subjective form: he, she, it, they.  See: subj(%#)
    %o, %O   Objective form: him, her, it, them.  See: obj(%#)
    %p, %P   Possessive form: his, her, its, their.  See: poss(%#)
    %a, %A   Absolute Possessive form: his, hers, its, theirs.  See: aposs(%#)

An argument could be made for the inclusion of reflexive pronouns (himself, herself, itself), as well.

**Comment by silentartist** [comment]
I hope this gets implemented even if it is a contrib. Thanks

**Comment by VanderHuge** [comment]
I see this as a nice little extra fluff that's not really worth all the effort to implement

**Comment by tajmone** [comment]
This brings to my mind Inform7's (for text-adventures) way of handling things within say statments (and in-game strings in general): it uses square brackets and accepts also conditional statements and other stuff. Something like this:

say "You tell *[if male]*him*[else]*her*[endif]*..."

say "It's been a *[one of]*nice*[or]*long*[at random]*day!"

game variables within brackets are evalued before output.

Maybe a system like this could be implement via some kind of pre- or post-parsing function dealing only with square bracketed contents?

I think that any such system should be separate from Evennia's core, and agree with Griatch that it should go with contribs--after all, it's something which might be wanted or wanted, according to personal tastes. But the idea of having acces to a separate parsing system (independent from Evennia's { system for colors or inline funcs) fully customizable could be something to integrate into Evennia, maybe as optional and turned off by default. Anyone could use it to pre- or post-process text output in custom ways (could also come handy for webpage contents).

Square bracketing could get around the various problems with { and %, even though it might mean that printable square brackets would have to be somehow escaped in order to avoid parsing.

**Comment by Griatch** [comment]
@tajmone 

We don't use square brackets, but with [inlinefuncs](https://github.com/evennia/evennia/wiki/TextTags#inline-functions) you could achieve something similar to what you suggest without having to introduce a custom language. For example, you can define an inlinefunc `ifmale` to differentiate between male and female by looking at a `gender` Attribute and return differing result depending on the result: 

```python
def ifmale(text, *args, **kwargs):
    """
    Used as ifmale(male_text, female_text)
    (Note: Assumes there are only two genders for simplicity)
    """
    session = kwargs["session"]
    if len(args) < 2 or not session.puppet:
        return text
    male_text, female_text = args[:2]        
    return male_text if session.puppet.db.gender == "male" else female_text        
```
With this inlinefunc in place you can now use: 

    say "You tell {ifmale(him, her) that ..."

**Comment by Griatch** [comment]
The more I look at this, the less this belongs in core. 

This is simple to implement in msg() if you really need it. I wrote a simple pronoun-replacing character as an example. You can find it [here](https://github.com/evennia/evennia/blob/master/evennia/contrib/gendersub.py), it should be enough to expand on for anyone needing this.
