### ISSUE TITLE
Profiling performance

### ISSUE THREAD

**Issue by luyijun** [evennia/evennia#620]
When I use evennia, I feel it's not fast enough. So I did some tests and profiled the performance. In one test, I put in 50 bots, let them connect in (It took nearly 20 seconds. They have been created before, so in this test they just connected in.) and then did "look" every 2 seconds on average for nearly 4 minutes. They did nothing else. The cpu usage was about 45%. (In another test, I put in 100 bots and the cpu usage raised to nearly 100%)

Finally the cProfile gave me a report. It says there were 69771477 function calls (69178981 primitive calls) in 223.856 seconds, and these are first 4 functions that took most time.

    ncalls    tottime   percall cumtime percall filename:lineno(function)
    763       110.182   0.144   110.19  0.144   {select.select}
    55716     5.563     0       24.365  0       {method 'fetchmany' of 'sqlite3.Cursor' objects}
    520160    5.294     0       14.907  0       dateparse.py:61(parse_datetime)
    4161280   5.249     0       5.249   0       dateparse.py:84(<genexpr>)

I am surprised that the "select" took nearly 50% of time. It seems that the database or cache doesn't work well. Are there any issues?

I ran these tests on my local machine which is a mac mini with 2.5G core i5 cpu and 16G memory.

**Comment by Griatch** [comment]
In the threading-branch (currently only locally on my devel machine) I have implemented what at least appears to be a robust content caching mechanism that also works well with asynchronous threading-saves  (all db-saves are offloaded to separate CPU threads). The branch and its features is based off devel. It still requires more testing and there are some race-condition bugs still. And even when offloading all db-saves to threading there is still a strange freeze when connecting many players with dummyrunner - profiling is inconclusive as to why that is. But it's promising.

**Comment by luyijun** [comment]
Thank you. I'll test my case on devel. The freeze on connection seems strange, it should not take so much time. I'll test it too to find out the reason.

**Comment by luyijun** [comment]
I profiled the performance when dummyrunner login.

I did these:
```evennia --profiler start```
```evennia --dummyrunner 100```
When I saw 100 dummy connected, I stopped dummyrunner by ```ctrl-c``` and the server by ```evening --profiler stop``` 

These are functions cost most time:
 ```
50392770 function calls (50257436 primitive calls) in 172.278 seconds

                                                     ncalls   tottime  cumtime
                                                        2565   89.082   89.102  {select.select}
twisted/python/log.py:75(callWithLogger)          <-    2778    0.019   83.197  twisted/internet/selectreactor.py:93(doSelect)
			
django/utils/crypto.py:103(_bin_to_long)          <- 2400000    3.415    5.898  django/utils/crypto.py:155(F)
django/utils/crypto.py:155(F)                     <-     200    7.992   24.778  django/utils/crypto.py:120(pbkdf2)
django/utils/crypto.py:120(pbkdf2)                <-     200    0.006   24.790  django/contrib/auth/hashers.py:233(encode)
django/contrib/auth/hashers.py:233(encode)        <-     100    0.002   12.427  django/contrib/auth/hashers.py:67(make_password)
                                                         100    0.002   12.369  django/contrib/auth/hashers.py:242(verify)
                                                         
django/contrib/auth/hashers.py:67(make_password)  <-     100    0.001   12.457  django/contrib/auth/models.py:226(set_password)
django/contrib/auth/models.py:226(set_password)   <-     100    0.000   12.458  evennia/utils/create.py:315(create_player)

django/contrib/auth/hashers.py:242(verify)        <-     100    0.001   12.378  django/contrib/auth/hashers.py:44(check_password)
django/contrib/auth/hashers.py:44(check_password) <-     100    0.001   12.382  django/contrib/auth/models.py:229(check_password)
django/contrib/auth/models.py:229(check_password) <-     100    0.000   12.383  evennia/commands/default/unloggedin.py:41(func)
```

The ```{select.select}``` means idle and the ```log.py:75``` should be the actual working time. Their sum is closely equal to the total time 172.278 seconds. ```django/utils/crypto.py``` took nearly 30% time, but it seems that little we can do to solve this. And sometimes, I need to wait serval seconds to see next connection message came out. I think this may be caused by exclusive locks in db or django.

**Comment by luyijun** [comment]
The above test was made on devel and used default dummyrunner settings.

I think using another authentication model instead of ```django/contrib/auth/models.py``` may help to solve this problem.

**Comment by Griatch** [comment]
@luyijun 

Maybe change settings to use `PASSWORD_HASHERS.insert(0, 'django.contrib.auth.hashers.MD5PasswordHasher')` to see if the perceived "freeze" does go away. The MD5 hasher should supposedly be a lot faster than the default one (which is apparently deliberately slow to make it harder to crack). I did try to deactivate the authorization (`check_password`) in the `connect` command in an earlier test, and that showed no difference. But I haven't tried changing the entire algorithm (which would also affect the *creation* of players).

**Comment by luyijun** [comment]
I set ```PASSWORD_HASHERS = ('django.contrib.auth.hashers.MD5PasswordHasher',)``` in settings.py and did the above test again. The MD5 hasher is much faster. It took only 0.006 seconds in encoding, while the default PBKDF2 hasher took 24.796 seconds.
```
         21277213 function calls (21183536 primitive calls) in 106.880 seconds

                                                       ncalls  tottime  cumtime
django/contrib/auth/hashers.py:395(encode)         <-     100    0.001    0.003  django/contrib/auth/hashers.py:67(make_password)
                                                          100    0.001    0.003  django/contrib/auth/hashers.py:401(verify)

django/contrib/auth/hashers.py:67(make_password)   <-     100    0.001    0.037  django/contrib/auth/models.py:226(set_password)                                                   
django/contrib/auth/models.py:226(set_password)    <-     100    0.000    0.038  evennia/utils/create.py:315(create_player)

django/contrib/auth/hashers.py:401(verify)         <-     100    0.001    0.011  django/contrib/auth/hashers.py:44(check_password)
django/contrib/auth/hashers.py:44(check_password)  <-     100    0.001    0.015  django/contrib/auth/models.py:229(check_password)
django/contrib/auth/models.py:229(check_password)  <-     100    0.000    0.016  evennia/commands/default/unloggedin.py:41(func)
```

So it's better to use MD5 hasher especially in dummyrunner.

In this test, the server ran fast at first, but when more dummies connected (above 70 dummies), it became slow. It may be caused by other matters.

**Comment by Kelketek** [comment]
@luyijun Please note that the MD5 algorithm is severely deprecated for password hashing these days. It's not considered secure. With salting, it's probably not as bad as people make it out to be, but part of what makes a good password hasher is resilience against brute-forcing. A slow calculation is more in line with that.

Granted, when doing performance tests, it may not be what you're looking for, so when doing the dummy runner, it may be the best option. But I wouldn't recommend deploying this algorithm in production.

**Comment by luyijun** [comment]
@Kelketek I know a strong password hasher is safer. But for inner tests, the connection costs too much and affects the profiling result. In previous tests, I had to create accounts first, then ran dummyrunner without creation, and had to extend the test time to reduce the weight of connecting in total performance.

And there is another matter about safety, shall we restrict the number of account creating from a single IP in a certain period? Or someone can attack the server easily just by keeping creating a lot of junk accounts. I think verification code or verification email can be helpful.

**Comment by Griatch** [comment]
I implemented and pushed a modified dummyrunner in devel-branch now, that allows (and checks for) a  settings-mixin that sets the right permissions to Players and, more importantly, switches temporarily to the faster hashing algorithm. 

On SQLite for 100 players (`chance_of_action=0.2, chance_of_login=0.1`), this really *flies* now, and it really didn't before. I can enter commands throughout the connection of all hundred players without more than hickups .  @luyijun, I don't see a slowdown above 70 players. What you see may just be that the *rate* of players connecting goes down? If so, this is just because there is a random chance for a player connecting at any moment, and as the number of remaining un-connected players drops there is a lower and lower chance that any one of them will happen to connect a given second. 

The performance of PostgreSQL is slower than SQLite - it takes about 8 seconds after the dummyrunner starts connecting (which is when the rate of connection is the highest) until my `look` command (given at the same time) returns to me. After that it quickly improves though. 
MySQL however, is even slower - it takes 18 seconds before seeing a return on the look. I don't know why this is. 

Unfortunately it seems my threading attempts (in a separate branch) is not helping this very much - the behavior for PosgreSQL/MySQL (SQLite doesn't work well with multiple threads for me) is actually *worse* using threading than without. It's really hard to tell why, profiling this is very tricky. Since there is at no time a 100% CPU load I can only assume this is an I/O bound problem, but this is exactly what threads should be good at (also in Python). One possible reason could be the amount of deferred management I need to do to accomodate threads - for example `ManyToMany.add()` operations cannot be called until all components have been saved and thus have to be deferred until the save operation returns. Again, if this is the case it has turned out to be very hard to actually profile (it's all eaten up by Twisted's polling loop, making it unclear what it actually idles on). So the profile looks really good and fast, but in practice the threaded version of the server doesn't *feel* fast for some reason. :/

**Comment by luyijun** [comment]
I will do more tests on it.

MySQL seems too slow, but I am not familiar with it, so I cannot give you suggestions. The result of multiple threads seems not good. Maybe the db self is the bottleneck. There may be more queries and saving requests sent to the db at the same time by multiple threads, so the performance of the db become worse. The way of making queries may need improve. We need do more performance tests to tell where is the bottleneck.

**Comment by luyijun** [comment]
I have made some tests. The performance of the server is improved significantly. The slowdown above 70 players I said before may be caused by the connection and login. This time I used the latest codes. It was made on my local machine which is a mac mini with 2.5G core i5 cpu and 16G memory. The db was SQLite. I digged 20 rooms, set TIME_STEP to 2, CHANCE_OF_ACTION to 0.5. These were the same as before. The results are as follows.

1. 100 dummies, CHANCE_OF_LOGIN 0.5, 100% move.
    The cpu usage was about 45%. I did not see any delay in the game.

2. 200 dummies, CHANCE_OF_LOGIN 0.5, 100% move.
    The cpu usage was nearly 100%. I could not play the game.

3. 200 dummies (172 actually connected), CHANCE_OF_LOGIN 0.01, 100% move.
    The cpu usage was nearly 90%. I could see slight delay in the game.

4. 200 dummies, CHANCE_OF_LOGIN 0.02, 90% look, 10% move
    The cpu usage was about 55%. I did not see any delay in the game.

5. 400 dummies, CHANCE_OF_LOGIN 0.005, 90% look, 10% move
    The cpu usage was nearly 100%. I could not play the game.

6. 400 dummies (330 actually connected), CHANCE_OF_LOGIN 0.005, 90% look, 10% move
    The cpu usage was nearly 80%. I could see slight delay in the game.

7. 300 dummies (298 actually connected), CHANCE_OF_LOGIN 0.005, 90% look, 10% move
    The cpu usage was nearly 80%. I did not see any delay in the game.

Next time, I will use profile.

The CHANCE_OF_LOGIN has a problem. If I use more than 200 dummies and set CHANCE_OF_LOGIN to above 0.1, almost all dummies will connect in less than 30 seconds. These dummies are stuck in limbo, and the server is paralyzed. I think it is because nearly all dummies are in the same room and the messages of entering or leaving the room will broadcast to all characters in the room. There are too many message to send, so the server is paralyzed. But if I set CHANCE_OF_LOGIN to a very small value, such as 0.005, it takes too long time for dummies to connect. As test 3, 6 and 7, I had waited for about 30 minutes, but there were some dummies still not connected. I think it should be better to use LOGIN_IN_EVERY_XX_SECONDS instead of CHANCE_OF_LOGIN.

**Comment by Griatch** [comment]
It's an interesting observation that the CHANCE_OF_LOGIN mechanic might be hampering the performance in a weird way. It's a good idea to test some other way of distributing the logins.

**Comment by Griatch** [comment]
In the latest devel version I have introduced a throttling mechanism in the portal that limits the number of connections / second. Lowering this is currently done by modifying _CONNECTION_RATE in `evennia/server/portal/portalsessionhandler.py`. With this the CHANCE_OF_LOGIN can be set to 1.0. With a _CONNECTION_RATE of 1-5 I can connect 200 dummies with a few hickups. I do see a slowdown after some 150 logins, even if the connection rate is the same; you could be right that this is related to seeing more and more objects to echo to when connecting ... but if `msg_contents()` or the `contents` property are really the main bottleneck it sure is not showing up when profiling ...

**Comment by luyijun** [comment]
Thank you!

I made some tests and found something: If there are lots of characters in the same room, the server will be very busy. When a character calls a command, the command handler needs to get all cmdsets of all objects in the same location to merge its cmdset. So if there are many objects in the same location, the command handler needs do a lot of works.

Here are two of my tests:

I made a new command which just passes and does nothing at all. When I used c_login_nodig in ACTIONS, the cpu usage of the server was very high, but when I used c_login, the cpu usage of the server was very low. The main difference between c_login_nodig and c_login is the number of characters in same locations.

I have some ideas which may help to solve this problem.

We can classify objects' cmdset into different cmdset types. Each cmdset type has its own cmdset, and the command handler merges objects' cmdsets according to their cmdset types. If all objects in the same location are of the same cmdset type, the command handler only needs to merge one cmdset. 

And we can merged cmdset of all objects in the same location and put it on the location. When an object enters or leaves or changes its cmdset, the cmdset of the location needs update. When someone calls a command, the command handler only needs to merge the cmdset of the location.

**Comment by Griatch** [comment]
@luyijun 

Hm, I agree that the commandset processing may be to blame, but I wonder it it is the merging operation itself. The reason is that character's cmdsets are actually *not* merged when in the same room. The following operations are speeding up things in that regard:

1. All characters have the `call:false()` lock on themselves, this means that no external objects may call the commands on them (if this was not the case you would get asked about duplicates for `look` and other commands whenever you entered the same room as another Player. This is is checked here: https://github.com/evennia/evennia/blob/devel/evennia/commands/cmdhandler.py#L185
1. Once a selection of cmdsets are gathered, a hash is generated from their in-memory IDs. This hash is cached so the merger of a given combination of cmdsets can be re-used. This happens here: https://github.com/evennia/evennia/blob/devel/evennia/commands/cmdhandler.py#L258. This should have little impact in this case though, since no cmdsets from the other characters should pass the lock above. 

So the first `call:false()` lock should basically remove all other cmdsets from the merger (all in the room are Characters with the same lock after all). What could cause a slowdown might instead be the growing time needed to check the `call` lock combinations for an ever growing number of characters ... but I've not checked this.

One could of course still consider skipping a merger of two identical cmdsets, for the situations where that is relevant but it should not come into play in this instance ... unless there is a bug somewhere of course. :) 

I will do some tests throttling things to a specific command/second rate on Server side rather than throttling connections like I tried above, see if this changes the perceived performance.

**Comment by luyijun** [comment]
I found a cause, it is ```contents_get()``` as I had found before.

In ```evennia/commands/cmdhandler.py``` line 173:
```
                    local_objlist = yield (location.contents_get(exclude=obj) +
                                           obj.contents + [location])
```

I replaced it with
```
                    local_objlist = yield (obj.contents + [location])
```
and the cpu usage dropped low.

Then I replaced it with
```
                    location.contents_get(exclude=obj)
                    local_objlist = yield (obj.contents + [location])
```
I just added a useless line and the content of local_objlist did not change. The cpu usage rose by about 100%.

When doing contents_get(), the server needs to search the db. In this case, I put 100 dummies in the same room, and it costs a lot of time in doing contents_get(). I had tried to add a cache of object's content in every object before, it could speed up the server, but it sometimes lost data when other objects entered or left. Now I am thinking of copying all objects' location to memory, this may save a lot of time when doing contents_get().

**Comment by Griatch** [comment]
@luyijun: This is a useful test, thankyou! It's difficult to see these effects in the profile as it turns out, since it gets eaten by the twisted polling loop (is my best guess). Maybe testing actual code variations like you have done here is the only way to diagnose some in-practice slowdowns.

An object's location is already in memory - Django automatically cache foreignkey relations after the first query. The problem lies (I believe) in querying for the (changing) group of entities at a given location. 

I'll check if I can cherry-pick my cached `contents` handler from the threaded-save branch, see if that makes a difference.

**Comment by luyijun** [comment]
I think it is serious. The ```obj.contents``` in ```evennia/commands/cmdhandler.py``` line 174 works in the same way as ```location.contents_get```. If a character have many objects in his inventory, the ```obj.contents``` will cost a lot of time too, though he is alone in the room. This happens more often than many characters in the same room.

**Comment by Griatch** [comment]
@luyijun 

I now pushed the contents_cache handler (cherry-picked from the threaded-branch) to devel-branch. It seems you were correct on this: With this code I can now run dummyrunner with 200 dummies using "normal" usage profile and `CHANCE_OF_LOGIN=1.0`, `CHANCE_OF_ACTION=0.5` without noticing any stutter at all, neither during connect nor later. CPU is around 40% when thus handling ~100 commands/second so there is some leeway there. I also tried 250 dummies with a slight stutter but fully playable.

**Comment by luyijun** [comment]
Thank you. I think the problem of ```contents_get``` is solved. I ran 200 dummies only using the empty command and set ```CHANCE_OF_LOGIN=1.0```, ```CHANCE_OF_ACTION=0.5```, the CPU usage of the server was no more than 20%. But in the meanwhile, the portal seemed too busy. Its CPU raised to around 80%. When I tried to add more dummies, the dummyrunner told me:
```
client Dummy-xx(xx) lost connection ([Failure instance: Traceback (failure with no frames): 
<class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
```

**Comment by luyijun** [comment]
I made a mistake, it isn't portal who is too busy. I'll try to find out who uses so much resources.

**Comment by luyijun** [comment]
It's the lock system this time. These are my tests:

I ran 200 dummies only using the empty command and set CHANCE_OF_LOGIN=1.0, CHANCE_OF_ACTION=0.5, ACTIONS = ( c_login_nodig, c_logout, (1.0, c_test)). The CPU usage of the server was about 65%.

For other players' commands should not be added to the cmdset, I added
```
                    local_objlist = [o for o in local_objlist if not o.player]
```
before
```
                    local_obj_cmdsets = \
                        yield [lobj.cmdset.current for lobj in local_objlist
                           if (lobj.cmdset.current and
                           lobj.locks.check(caller, 'call', no_superuser_bypass=True))]
```
in ```evennia/commands/cmdhandler.py``` line 185.

This can filter players before the lock check. With this modification, the CPU usage of the server was just about 35%.

But when I made dummies moving around, the improvement seemed little.

I set CHANCE_OF_LOGIN=1.0, CHANCE_OF_ACTION=0.5, ACTIONS = ( c_login_nodig, c_logout, (0.6, c_move_s), (0.4, c_move_n)). Then I build 2 rooms and put 60 dummies in. The CPU usage with and without ```local_objlist = [o for o in local_objlist if not o.player]``` were nearly 65% and nearly 70% respectively. When I put 80 dummies in, both CPU usage rose to nearly 100% and could not play.

**Comment by Griatch** [comment]
I ran the test you did. On my thinkpad x201 laptop (which I suppose is a little more powerful than the computer you test on?) I could add 100 dummies walking between two rooms with the same dummy_settings without any slowdown. 110 dummies caused a slight stutter occationally (CPU jumping between 70% and 90%) whereas 120 dummies was too much with an average CPU of 100%. 

Just to test how much impact CPU power has, I ran the same test on my desktop machine. Here the upper level seems to be around 200 dummies which is not so much of an improvement considering. This would not be consistent with database access (like the actual moving operation) since its clearly CPU bound and not I/O bound. Rather it would suggest it scales with a complexity of O(n2) as more and more objects need to communicate with each other. Will run some more profiling.

**Comment by luyijun** [comment]
I made a series of tests on outputs, and seemed to find something costed a lot of CPU. It's related with twisted or the mechanism between the server and the portal, but I am not familiar with twisted and can't tell the exact reason. Here are my test.
     
I created a test command as this.
```     
class CmdTest(BaseCommand):
    """
    For test only!
    """
     
    key = "@test"
    locks = "cmd:all()"
    help_category = "General"
     
    def func(self):
        """
        """
        for i in range(100):
            self.caller.msg("TEST")
```

It outputs 100 "TEST" to the caller. I set CHANCE_OF_LOGIN=1.0, CHANCE_OF_ACTION=0.5, ACTIONS = ( c_login_nodig, c_logout, (1.0, c_test)) and used 50 dummies, so the server outputs 2500 messages per second on average. 
The server's CPU usage was about 55% and the portal's CPU usage was about 50%.
     
I inserted this to evennia/server/portal/telnet.py's data_out on line 232:
```
     if text=="TEST":
        return
```
The CPU usage only dropped a little. It was nearly 55% and nearly 50% separately.

     
I inserted this to evennia/server/amp.py's amp_msg_server2portal on line 376:
```
     if msg=="TEST":
        return {}
```
The CPU usage dropped to about 50% and about 40% separately.

But when I inserted this to evennia/server/amp.py's safe_send on line 280:
```
     if "msg" in kwargs:
        if kwargs["msg"]=="TEST":
            return
```
the CPU usage dropped to below 20% and below 5% separately.
     
So there must be something costs too much between the server and the portal.

**Comment by Griatch** [comment]
@luyijun 

This is an interesting result. It's strange that the CPU should be affected at the safe_send level, since this should not be called in an expensive unless the data being sent is very long (exceeding AMPs max message length).

I'll not looked at the profiling in a little, will see if I can find time to examine it again soon.

**Comment by Griatch** [comment]
@luyijun 

I have looked into this and as far as I can tell there is no further way to optimize the AMP connection. Evennia sends a message from the Server to the Portal when you do a `msg()` call, and all the work seems to happen in the AMP internal serializing, not in anything Evennia does. 

Attempting to simplify the command structure (for example removing their deferred return value) causes havoc with interconnectivity, especially since any traceback on either side will then lead to a Server-Portal disconnect rather than a logged error (this has a very small effect on performance anyway). 

I guess one *could* in principle try to make some sort of batch queue to cut down the amount of Server-Portal messages; one would then group messages arriving very close to each other and send them all across the wire together as one block. This would cut down on the transmission but will add a lot of extra complexity on both the Portal and Server sides. So not sure that it's worth the trouble.

**Comment by luyijun** [comment]
Thank you. I will try to improve it, for it limits the number of total output messages.

**Comment by Griatch** [comment]
@luyijun 

While optimization is all well and good (and interesting), do you realistically expect to often exceed 5000 messages/second in actual production?

**Comment by luyijun** [comment]
5000 messages/second is the max number when there is only output. If players are doing other things, the number may to declined to 2000 or 1000. 

If players are chatting in public channels or the system broadcast messages frequently, I think the total outputs could raise to a high number. In our country, broadcast is very popular. If a player kills a boss or finds a treasure or even upgrades to a certain level, the system will broadcast messages to all players to attract them.

**Comment by Griatch** [comment]
@luyijun 

Hm, I see your point.

In a private branch I implemented a batch-send in the AMP handler, just to gauge the performance. It basically checks if it was a very short while since the last command (less than 1/500th second or so). It then basically stacks commands together as densely as possible and sends off a batch of commands about 500 times per second at the fastest. I've only set it up for Server->Portal side, not Portal->Server.

The result for this simple experiment is actually very promising. I used the same "test" command setup as you use, and the same dummyrunner settings (the CPU stats bounce around a bit, this is some sort of median on my laptop):

- 50 dummies (~2500 cmds/sec): CPU: Server 15%, Portal 11%
- 100 dummies (~5000 cmds/sec): CPU: Server 30%, Portal 12% 
- 150 dummies (~7500 cmds/sec): CPU: Server 40%, Portal 17% 
- 200 dummies (~10 000 cmds/sec) CPU: Server 57%, Portal 23%
- 250 dummies (~12500  cmds/sec) CPU: Server 77%, Portal 30%

I could probably have taken it up to 300 dummies too (15000 cmds/sec) but at this point the effects of login-slowdown started to cause it to hit 100% CPU and slowing things down. 250 dummies is perfectly responsive though once everyone has logged in. 


My implementation is, as said, just experimental at this point and it has some issues - for example ithere is no mechanism to auto-send the last batched command if no more commands are forthcoming - if adding a deferred mechanism to timeout, this kills performance completely. So need to ponder that some more. 

But these preliminary numbers do sound pretty okay, no?

**Comment by Griatch** [comment]
@luyijun 

I implemented batch-sending of commands for all AMP commands between Server and Portal,  reducing the time spent sending data across the wire by a surprising amount. As mentioned above I can get up to somewhere around 12500 commands/second using the sample test suggested. 
The change is now live in master. Check it out!

**Comment by Griatch** [comment]
With no further replies on this, I'm not closing this issue (see also #746) .
