### ISSUE TITLE
Under default command set, players cannot change their own description.

### ISSUE THREAD

**Issue by AllSystemsGo** [evennia/evennia#643]
Normal players can't @desc themselves.

Also, @desc seems to add an errant space before the actual input desc starts.

**Comment by Griatch** [comment]
The "errant space" has nothing to do with `@desc` but is only how the look command formats the output with one-space indent. `@desc` is a builder-level command allowing you to change descriptions of any object, so I will add a "desc" command for this limited self-only use. 

_PS: If you refer to commands starting with `@`, please put them in tick-marks, otherwise github will interpret it as a reference to a github-user named e.g. "desc" and they will get spammed with notifications._
