### ISSUE TITLE
<character>.search() - Add Candidates?

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#644]
I can see that there is a 'candidates' field in evennia.utils.search.

But candidates is not accepted in \<character\>.search().

I am perplexed at this.

**Comment by Griatch** [comment]
`object.search` (usually `caller.search`) is a wrapper on top of the full `evennia.utils.search`; it builds the candidates list for you based on the location, inventory etc, which is what is usually needed in a command. `caller.search` is really a shortcut. 
The `utils.search` is meant to be used if you want more control outside of the room/character. What particular use-case makes you want to use `caller.search` with candidates rather than the full `utils.search`?

**Comment by volundmush** [comment]
I would like the ability to use the character's nicks and other personal resources against the 'these are the game's characters' list! (From the issue that was just solved of using tags to identify characters for easy searching...)

... am I being stupid again?

**Comment by Griatch** [comment]
No, that sounds like a valid use-case. So might be useful to add candidates to `caller.search` then.

**Comment by Griatch** [comment]
This is now implemented in devel branch. Closing this for tidyness.
