### ISSUE TITLE
Bug: Starting issue on Windows

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#681]
*(copied from mailing list [here](https://groups.google.com/forum/#!msg/evennia/qVGyQiCBJ6s/LbNcd0vDEMIJ))*

Something is not working out in Windows.

I have the usual Python + Virtualenv which worked fine with previous version.

Installation all goes fine until I get to `evennia -i start`

I get a quite long sequence of errors from evennia_runner.py, which culminate with a `WindowsError [2] impossible to find the file` (it's in italian, so I'm translating approximately). But the list also contains references to the normal python installation, so it seems that is not operating within the virtualenv as it should?

The bin/windows/evennia.bat doesn't come to aid either, it's something in the python evennia_runner file

I'll try it all over again, but I did follow instructions to the letter. I even tried different locations for the `evennia --init mygame` comand (which works in any case).

Below I've pasted the error's report from CMD shell...

```bash
(virtualEvennia) D:\MOOs\Evennia\virtualEvennia\evennia\mygame>evennia -i start

0 static files copied to 'D:\MOOs\Evennia\virtualEvennia\evennia\mygame\web\static', 73 unmodified.

(virtualEvennia) D:\MOOs\Evennia\virtualEvennia\evennia\mygame>
Starting Evennia Server (output to stdout).


Starting Evennia Portal in Daemon mode (output to portal logfile).
Traceback (most recent call last):
  File "d:\moos\evennia\virtualevennia\evennia\evennia\server\evennia_runner.py", line 331, in <module>
    main()
  File "d:\moos\evennia\virtualevennia\evennia\evennia\server\evennia_runner.py", line 328, in main
    start_services(server_argv, portal_argv)
  File "d:\moos\evennia\virtualevennia\evennia\evennia\server\evennia_runner.py", line 170, in start_services
    PORTAL = Popen(portal_argv, env=getenv())
  File "C:\Python27\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] Impossibile trovare il file specificato

(virtualEvennia) D:\MOOs\Evennia\virtualEvennia\evennia\mygame>
```

**Comment by tajmone** [comment]
I've solved it "manually": i realized that installation doesn't create the "twistd.bat" file in the "game" folder. So I took an old  "twistd.bat" I had around, edited/adapted the paths and placed it in the "game" folder I had created ... it worked.

Either something goes wrong during installation or that batch file was missed out somehow. Just the "evennia.bat" file in bin/windows is not enough...

**Comment by Griatch** [comment]
Confirmed, this didn't show up unless doing a fully clean install, maybe there was some lingering variable in the old one that hid the bug. 

It seems there is an issue with dynamically updating the `PATH` system variable in the `Popen` call under Windows (e.g. [this](http://bugs.python.org/issue8557)); the subprocess does not use changed `PATH` at all, apparently. So we will need to give the absolute path to it instead (dropping it into the game PATH, like @tajmone did works too, but I think it's better to keep the `twistd.bat` file within the evennia package proper).

**Comment by tajmone** [comment]
Mhhh. But after Evennia-startup failure to open that file, I echoed the PATH variable and it did contain the virutalenv variables added by installation. There were quite a few of them (temporarily added to the default system path), some had the drive letter in capital (C:) while other in non capital (c:) but they were all correct full absolute paths. I wouldn't know if one PATH variable was missing, but I seem to understand that the error regarding the missing file refers to the _twisted.bat_ file. I've only added that and it didn't give me any more errors.

Of course, different versions of Window might behave differently in this regard (I have Win7 64 bits). Also, consider that I have also installed pyWin32 (219-64 bits) along with Python (even though in virtualenv I have to install pypiWin because it can't see the pyWin32 DLL from within virtualenv); and I have installed MSV C++ Compiler for Python 2.7 — both of these were installed as a result of some sort of warning during previous installation of Evennia, so an environment without them could behave differently.

**Comment by Griatch** [comment]
@tajmone 

It works for you because you put your `twisted.bat` file in a place that is *already* on the system path. The twisted.bat file is created in `evennia/server/twisted.bat` and Evennia tries to add this directory to `PATH` at run-time, this is what Windows (or at least the Windows implementation of `Popen`) does not acccept. 
Anyway, I'll just make it into an absolute path when I get back home tonight, should hopefully fix this right up. :)
