### ISSUE TITLE
Task: Convert API docstrings to Google-style ones

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#709]
This issue tracks the progress on converting Evennia's API docstrings into [Google-style docstrings](http://sphinxcontrib-napoleon.readthedocs.org/en/latest/). We don't use napoleon/sphinx for this but our own `api2md` parser, but the principle is the same.

Evennia's docstring syntax is outlined in the [Code style document](https://github.com/evennia/evennia/blob/master/CODING_STYLE.md).

**Comment by tajmone** [comment]
One question arises regarding docstring of Evennia Cmds: since the AutoHelp takes their docstring for building the `help` output, show should the docstings be handled in this case?
- Should considerations for the Wiki API documentation be set aside in favour of a clean cmd-help output? In other words, ignore markdown for cmds docstrings?
- As for the Wiki,the Code style mention not exceeding 70 columns in code blocks (or inline). As for the default cmds docstrings, I gather it should be kept as close as possibile to 80 columns (not more) which would be a good standard (Evennia defaults to 78 though). That is: 80 without considering the leading python-indentation whitespaces (4 or multiples of 4) which is stripped by auto-help.
- Default cmds help output is something that every user will deal with, so it might be worth setting some explicit code style guides for it.

**Comment by Griatch** [comment]
Command docstrings are a special case and should not be modified with markdown in mind; as you say they are meant for in-game use and should be targeted for that. At any rate they are also all already formatted in a similar fashion and will look okay in the wiki anyway. 

The default style for commands is outlined in the [Policy for MUX-style commands](https://github.com/evennia/evennia/wiki/Using%20MUX%20As%20a%20Standard#documentation-policy).
