### ISSUE TITLE
About ANSI color sequences

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#725]
I have changed the Wiki page about ANSI colors as follow:

> Adding ANSI colour to in-game text is easy. You just put special markers in your text that tell Evennia when a certain colour begins and when it ends. Evennia uses lower-case letters for foreground bright colors (which are the most readable ones on a traditional black terminal background) and upper-case for the foreground darker (normal) colors. For background colors there is only the lower-case notation, which produces the equivalent foreground normal colors — ie: normal colors are specified in uppercase for foreground, and in lower case for background, therefore: `{R{[r` will produce text with same dark-red color for both foreground and background. Using upper case color letters in background ANSI sequences (eg: `{[R)` produces no results, but neither breaks-up current background color.

I've changed it because after playing around quite a while with ANSI colors I've grasped their in-and-outs, and thought the above text better explains their workings. 

Two things do jump to attention immediately, though:
- Why on earth **normal** colours have to be in uppercase for foreground declarations and yet lowercase for background?
- Also, since background colors don't distinguish between dark and bright, why are capital letter colors ignored? They produce no BG color. Couldn't upper- and lower case be both treated as normal colors in the background context?

Another thing that puzzled me is this:
- Why setting a **bright** foreground color doesn't reset the background color, and setting a **normal** FG color does? Has it got to do with emulating the way old terminals worked?

Last thing (more a question, by since I'm on the isse): the TAB sequence `{-`. It's not clear how it is handled.
- In the browser it didn't produce any visible results (there is no TAB entity in HTML after all).
- In the MUSHClient it did but it's not clear on which criteria.

Since terminals are originally fixed-font, would a TAB have a number of spaces equivalence?
Does Evennia just send a TAB entity and lets the client handle it?
Maybe a few words could be spent on the TAB in Wiki.

**Comment by Griatch** [comment]
Thanks a lot for your nice work!

It is a good point about the case for background colors; the ANSI standard doesn't support more than 8 background colors so I guess we just went with the default values. Will need to consider this one.

A "bright" color is actually a "highlight" tag + a "normal" color. In order for a "normal" color to properly switch from a "highlight" color, it must be preceeded with a "normal" tag, otherwise the "highlight" would bleed over and you could not follow a bright color with a normal one. Setting the normal color unfortunately also affects the background color. This is how the ANSI standard works, unfortunately.

Evennia actually recently added a new type of color tag that complements the normal colors - I realize I might not have actually added it to the documentation yet. It is used as `{!b` for normal blue. This has no "automatic" normalization or highlights and must thus be manually preceded with a `{h` for highlight to get the bright version or a `{n` if you are switching from bright to normal. So `{h{!b` is the same as `{b` but `{btest{Btest` produces a bright blue text directly followed by a normal-blue text whereas `{h{!btest{!btest` will produce two bright blue texts since the highlight bleeds over. This is a lot more verbose but allows for some tricks with colors that only the deprecated `%c` style color tags could handle before. Should get down to document that behavior. 

The `{-` tab is literally setting a \t character which terminals should traditionally understand. Neither tabs nor spaces have any purpose in html making this tag somewhat of a legacy thing.

**Comment by tajmone** [comment]
That explains it well. As for the `{h` and `{!` ANSI markers, I've tried them both, the former works and the latter fails (ignored, passes through to output). Could it be that `{!` is still in a dev branch?

When it comes to use, the `{n` resetting both BG and FG might be an issue regarding usability.

Couldn't there be `{n` = normal FG and `{[n` = normal BG, and a `{N` normalize both?

This could give users better control over insertions into texts which lots of ANSI markers.

As for the overall behaviour, I guess it depends a lot on wether the intent is to emulate faithfully some legacy standard or wether is about providing an Evennia specific way to handle ANSI codes in a user-friendly way. In the latter case, it might be worth ensuring that switching to a normal FG color preserver the BG color—this would prevent, for eg, having to change all the BG color declaration in a long BG-colored text when there is a change of heart regarding to it's color:
```
{W{[bA long sentence with {yblue{W{[b BG color. Every time I {ychange{W{[b
the FG color I have to redeclare the {yBG{[b color again.{n
```
if I wanted to change BG color from blue to something else, I'd have change it many places. If FG color swtiching didn't affect BG, this wouldn't be an issue at all.

In dynamically generated texts this might become a major issue, especially with recursive functions (just think of map-generators!). Is there at least some code-access to the current BG and FG colors? At the end of the day, ANSI colors is one of those things that either you love it (and use it all over the place) or either ignore it (and stick to defaults).

**Comment by Griatch** [comment]
My bad - they should be named like  `{!R` since they are normal color. So `{h{!R == {r`. They are there to handle the case of changing color over the same background, among other things. The fact is that ANSI backgrounds are expected to be used a lot more rarely than normal colored text. So normal tags are considerably more convenient to use the way they are, with the special `{!` tags intended for foreground graphics stuff.

There may be a way to reset highlight in ANSI but there is no way to only reset background colors in the ANSI standard. `{[n` is simply not possible as far as I know. The problem with the suggestion of preserving colors is that color tags are stateful, they don't really know what color the text has at the point of insertion, it just changes everything following the tag.

**Comment by Griatch** [comment]
In the latest push I have implemented the use of the `22` ANSI sequence (one can also call it directly with `{H` to contrast with the `{h` which turns on bright highlights). I use this un-brightness tag instead of the full `0` ANSI sequence (`{n`) for the upper-case (normal-intensity) colors. This should allow these colors to switch to normal-intensity mode without affecting the background color and make things work a little more intuitively. 

We can now also get bright backgrounds with e.g. `{[r` while using `{[R` to get normal-intensity backgrounds, making the syntax the same for foreground and background. Since ANSI colors doesn't actually support bright background colors, this is handled with a Xterm256 wrapper. If the client does not support Xterm256 both bright and normal will look the same in the client ('normal' intensity). 

The `{h`and `{H` tags can now be used to control `{!` style normal colors with overbleed if so needed. I have updated the color documentation to explain the differences, check it out! :)  

I think this issue can be closed now, but leaving it open for a little longer in case of further comments.

**Comment by tajmone** [comment]
I've been playing around with the new ANSI functionalities. I've noticed some strange behaviours with the new bright BGs (but then again, it might be due to the Xterm wrapping ANSI here):

`{h` has no effect when there is a birght BG:

```
say {[y{R dark red on bright yellow BG {h still dark red
say {[Y{R dark red on bright yellow BG {h now bright red
```
Also (I've put a note it in the Wiki!), after a `{*` switch `{!` will change BG color instead of FG!

Still playing around more, getting deeper into the issue, pushing the limits (so to speak).

**Comment by Griatch** [comment]
@tajmone 

What happens with `{h` on a bright background (at least in my terminal) is that it intensifies/boldens the output. As you write in the wiki, it's roughly related to `<strong>` in HTML. What happens on the yellow background is that it outputs the text bolder (probably because making the red brighter would make it stand out less): 

```
say {[y{R dark red on bright yellow BG {h now bold-font dark red
say {[Y{R dark red on dark yellow BG {h now bright red
```

Exactly what happens is probably client-specific, but at least that is what I see here.

**Comment by Griatch** [comment]
It seems to vary a bit actually. Blue on bright red background both changes hue and boldness with `{h` whereas red on bright yellow seems to only change boldness. This could come down to how easy the contrast is to spot though.

**Comment by Griatch** [comment]
Heh, scratch that. I changed the colors in my terminal to show a bigger difference between normal and intense red, and now it shows just fine as brighter red. I had set it down to make errors easier to see in vim. 
So after this I cannot replicate the issue with `{h` you report. Check so that your terminal is configured to display the differences visibly enough.

**Comment by tajmone** [comment]
I'm using MUSHClient with default settings, and I don't get any bod.
I've tried it on the webclient (my Localhost Evennia), and what I got was very BUGGY:
```
say {Rsomething
```
produces:
```
You say, "[22something"
```
(with "something" in red). This is due to the translation in Italian, which is using some older version Cmd files; something must have changes in those. This bug doesn't show on the online demo, only locally.

I'll have to replace the Cmd files with the new ones and retranslate the various keys, aliases, and docstrings! 

So, maybe some other ANSI related stuff is not showing up 100% correct locally.

**Comment by Griatch** [comment]
Yeah, the webclient is a different beast entirely. It converts the ANSI tags back to HTML. Not all tags (and none of of the latest ones) are currently supported on the webclient. I did fix the lack of the ANSI 22-tag (this is `{H`)  in the text2html converter though (fixed in latest push). 

As for why the bold text doesn't show up in MUSHclient, I don't know - it should have some setting to tweak the ANSI color output, worth checking out. Not much I can change from this end I think.

**Comment by Griatch** [comment]
I don't think there is much more to discuss on this topic, with the latest updates. Closing this now. Make a new one if there are specific color issues to address further.
