### ISSUE TITLE
Feature Request: Player hooks - at_login_success, at_login_failure

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#733]
For the purpose of making it easier to write login tracking software, I think it would be pretty easy to add some hooks for these on the DefaultPlayer that can be called by the connect command!

All it needs to pass is the attempting session and a reason for failure, right?

**Comment by Griatch** [comment]
Is this not better to handle in the connect command directly? You are going to overload that anyway if you want to add extra tracking, no?

**Comment by volundmush** [comment]
Well I'm already doing that.
Just thought this make it easier for other people.
Maybe not?

**Comment by Griatch** [comment]
The Player already has hooks for a successful login, several of them in fact at different stages of the login process. 

If the user *fails* to login though ... it is generally due to a failure to authenticate. Only after a successful authentication will a Player object be tied to the Session. How will the default command know *which* Player.at_login_failure hook to call?

**Comment by volundmush** [comment]
Well, if you successfully target a player in the first place then it would call the hook? If you target a player that doesn't exist then why would it call anything at all?
I forgot about the login success hook already existing, doh.

**Comment by Griatch** [comment]
So if you enter the right player name but the wrong password, a hook on that player object will still be run? Not something I'm adding to core I don't think. Closing this one.
