### ISSUE TITLE
Bug: Tickerhandler sometimes not accepting custom call-hook

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#744]
Occasionally the TickerHandler will not properly accept a custom call hook as assigned by `TickerHandler.add()`  but instead still try to call `at_tick` (the default hook name). The result is that an `AttributeError` is raised because `at_tick` is not found. 

This have been reported with the TutorialWorld (which uses several TickerHandler calls for its Weather system, bridge and mob) but seems to be a TickerHandler issue more than a tutorial one. 

I have seen this on the demo install and others have also seen it on their install. The problem so far is that I've not been able to reproduce it on my development machine at this time - the tutorial world runs without errors locally. More testing is needed.

**Comment by LeoWalker** [comment]
Hope this helps in reproducing this 'feature'. I experience this as well. (I do not run the tut world)

It only starts on a server that is shut down (evennia stop) and  started. It happens or it either doesnt. 
It does not happen very often but does happen sometimes.
I figured it might be an issue related to writing/reading during shutdown/startup but when I check the contents via ticker_handler.all() the custom hooks are correct (even though the feature is spamming my linux terminal it cannot find the at_tick).
I never seems to happen after a @reload And never comes up during the time a server runs. Rebooting the server does not help as well
Once it has occured deleting the object related to the handler and recreating it fixes it. (Never tried cleaning up the handler as a fix because my objects subscribe on creation)

**Comment by Griatch** [comment]
There were a few changes in 33154d4d609b8c8004964dbf610b1b44512ba30e to how the the tickerhandler state is saved for a full shutdown (it is now, didn't use to be). So far I've repeatedly created tickerhandler-controlled objects and shutdown the server repeatedly a multitude of times without seeing the AttributeError repeat. But I'll keep this open for now to see if anyone else still sees the error or if this is resolved.

**Comment by jpoge** [comment]
Think I'm getting this error now. I've got a TICKER_HANDLER.add call that's throwing this error: 

AttributeError: 'super' object has no attribute '_reschedule'

This is off a clean install from the most recent (5/23) git repo, freshly migrated DB, with my own source (based on the tutorial world) that I pulled from my Windows box to my Ubuntu box. The ticker is called through Character.py from a by way of a command that augments a character attribute.

**Comment by Griatch** [comment]
@jpoge 

I cannot replicate this; I've now rebuilt the tutorialworld on top of a fresh database a dozen time without seeing an error with the `_reschedule` call. Which database are you using? Could you give me the full traceback?

**Comment by jpoge** [comment]
Of course. This is off a fresh db migration using the default values for
the server. I've added two lines to my server's settings.py script in my
game folder:

TYPECLASS_PATHS = ['typeclasses']
PROTOTYPE_MODULES = ['world.prototypes']

Otherwise, it's the default configuration when it's cloned. That includes
the database type (SQlite?).

I also have done some extensive game mechanics development, but that all
seems to work fine without the ticker_handler.add() calls (thought I
haven't tested that extensively). It was also working previous to these
updates off an older version of the git repo.

Also, note that the second and third lines in the below traceback are print
statements I added to check the variables in the _reschedule function. So,
this is what's going into that function.


Server restarting ...
self is LoopingCall<7.0>(Ticker._callback, *(), **{})
ExtendedLoopingCall is <class 'evennia.scripts.scripts.ExtendedLoopingCall'>
Unhandled Error
Traceback (most recent call last):
  File
"C:\Users\Jim\EvenniaDevel\pythondev\pyenv\Lib\site-packages\twisted\application\app.py",
line 657, in run
    runApp(config)
  File
"C:\Users\Jim\EvenniaDevel\pythondev\pyenv\Lib\site-packages\twisted\scripts\twistd.py",
line 23, in runApp
    _SomeApplicationRunner(config).run()
  File
"C:\Users\Jim\EvenniaDevel\pythondev\pyenv\Lib\site-packages\twisted\application\app.py",
line 389, in run
    self.application = self.createOrGetApplication()
  File
"C:\Users\Jim\EvenniaDevel\pythondev\pyenv\Lib\site-packages\twisted\application\app.py",
line 454, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File
"C:\Users\Jim\EvenniaDevel\pythondev\pyenv\Lib\site-packages\twisted\application\app.py",
line 465, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File
"C:\Users\Jim\EvenniaDevel\pythondev\pyenv\Lib\site-packages\twisted\application\service.py",
line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File
"C:\Users\Jim\EvenniaDevel\pythondev\pyenv\Lib\site-packages\twisted\persisted\sob.py",
line 210, in loadValueFromFile
    exec fileObj in d, d
  File "c:\users\jim\evenniadevel\evennia\evennia\server\server.py", line
463, in <module>
    EVENNIA = Evennia(application)
  File "c:\users\jim\evenniadevel\evennia\evennia\server\server.py", line
169, in __init__
    self.run_init_hooks()
  File "c:\users\jim\evenniadevel\evennia\evennia\server\server.py", line
282, in run_init_hooks
    TICKER_HANDLER.restore()
  File
"c:\users\jim\evenniadevel\evennia\evennia\scripts\tickerhandler.py", line
278, in restore
    self.ticker_pool.add(store_key, obj, interval, *args, **kwargs)
  File
"c:\users\jim\evenniadevel\evennia\evennia\scripts\tickerhandler.py", line
183, in add
    self.tickers[interval].add(store_key, obj, *args, **kwargs)
  File
"c:\users\jim\evenniadevel\evennia\evennia\scripts\tickerhandler.py", line
144, in add
    self.validate(start_delay=start_delay)
  File
"c:\users\jim\evenniadevel\evennia\evennia\scripts\tickerhandler.py", line
134, in validate
    self.task.start(self.interval, now=False, start_delay=start_delay)
  File "c:\users\jim\evenniadevel\evennia\evennia\scripts\scripts.py", line
87, in start
    self._reschedule()
  File "c:\users\jim\evenniadevel\evennia\evennia\scripts\scripts.py", line
106, in _reschedule
    super(ExtendedLoopingCall, self)._reschedule()
exceptions.AttributeError: 'super' object has no attribute '_reschedule'


Failed to load application: 'super' object has no attribute '_reschedule'

evennia stop
Evennia: Portal stopped.
Evennia: The Server does not seem to be running.



Let me know what else I can provide to you.

**Comment by Griatch** [comment]
Bingo, I found why I could not reproduce this; it's a change in version 15.2.1 of Twisted (which all new users install automatically), and I was testing with the slightly older 15.1.0. It's interesting, changes in Twisted does not usually lead to incompatibilities. Now that I know what to look for I should be able to figure out how to resolve it though.

**Comment by jpoge** [comment]
Any progress on this?

I took a look through the code and a bit at the release notes for Twisted 15.2.0, but didn't have much time the last few days to devote to this (release notes are huge!). Maybe tonight.

One thing I was going to try was to replace the Twisted 15.2.0 in my dev area with 15.1.0. But, between the many many different parts of Twisted and only finding the twistd.bat file within the Evennia source, I'm not sure how to go about that and what parts of Twisted are used in Evennia. Is it possible to revert to a previous version using Git? (I'm more familiar with SVN.) Would this be a fairly straight forward process or is there some work involved to revert to 15.1.0? 

Is there a dependency on something or efficiency improvement with 15.2.0 that prompted the version update within Evennia? 

Was Evennia tested prior to release with 15.2.0? Perhaps there's a need for additional testing before releases. Also, are there release notes (sorry if I missed them)? Or wasn't this a formal release? How are Django and Twisted pulled into Evennia? In SVN I'd use external links. Not sure how Git works in that respect or if the source is baked into Evennia's source.

I'd really like Evennia to succeed, which is why I bring up these questions.

**Comment by frnknstn** [comment]
jpoge, Twisted is an external library used by Evennia. Depending on how you installed it, there will be different ways to downgrade it. If you used pip into a virtual environment (as per the method in the tutorials), you can downgrade by running these two command from within the virtual environment:

    pip uninstall twisted
    pip install twisted==15.1.0

**Comment by Griatch** [comment]
@jpoge 

It's very unusual to see regressions from twisted updates; for this reason our twisted version minimum had not changed for a good while. I was still running 15.1.0 here, which had no incompatibilities.

What changed from the Twisted side was an underlying API for a private method that Evennia makes use of (and since it's a private one, it doesn't need to see public notes). It's not a matter of efficiency, the twisted folks just added some more functionality and to reflect that change, they removed the old `_reschedule` method and named it something else with a different call sign (this is why you got an error for it not finding `_reschedule`). Since the underlying code works slightly differently from before I needed to rewrite the Evennia-side use of this method accordingly which is what I have been doing since I last had time to work on this since yesterday. ;)

All should work now, and this issue is closed.

**Comment by Griatch** [comment]
Oh, and you don't need to actually modify any twisted/django code. They are not in git, you install them as extrnal libraries via `pip` (if you follow the normal procedure). Downgrading to an older version of Twisted is simple, for example: 

```
pip install twisted==15.1.0
```

Google for the pip documentation if you want more help. The ease of managing dependencies is one of the great reasons we use virtualenvs an pip for this part.
