### ISSUE TITLE
No obvious way to recache individual objects

### ISSUE THREAD

**Issue by mechakin** [evennia/evennia#745]
There doesn't seem to be a way to recache objects without using `@reload` and stalling the entire MUD. This was previously fixed in https://groups.google.com/forum/#!topic/evennia-commits/rcUQkGO8ebw but seems to be un-fixed more recently.

The most immediate effect is that exits are very obnoxious to rename, as they have to be recached for the movement command to change, every time.

**Comment by Griatch** [comment]
This is fixed in latest push. It was more work than expected, the error came down to the Exit object being cached in the "contents" cache of the room it was in, meaning it held a reference even if the main database idmapper cache was flushed. Tying the contents cache directly to the idmapper cache resolves the issue and should be more consistent in the long run.
