### ISSUE TITLE
Feature Request: OOB support for Ajax web client

### ISSUE THREAD

**Issue by eidy** [evennia/evennia#761]
Currently OOB commands have been implemented for websockets but not the original Ajax COMET long polling technique.

To create a modern MU* client it is preferable to use web protocols.  Unfortunately not all client libraries support web sockets.  The original approach allows request/response to be done easily.

It would be ideal if comet could support OOB like websockets does.

**Comment by Griatch** [comment]
I'm unlikely to spend time on this anytime soon, alas - the focus is rather on updating the websocket webclient, we keep the ajax one primarily because it's cheap to just keep it in. If someone else is willing to take it on themselves to update the ajax client with OOB though, resolving this feature request is a good opportunity to help out.

**Comment by Griatch** [comment]
This will be an automatic result of the changes coming in the `wclient` devel branch. See #924.

**Comment by Griatch** [comment]
Closed as wclient branch has merged.
