### ISSUE TITLE
Something funky when typeclass __init__() is overridden

### ISSUE THREAD

**Issue by Zanetski** [evennia/evennia#762]
Create a new class that inherits from the basic Evennia Object typeclass.

```python
class NewObject(Object):
    def __init__(self):
        super(NewObject, self).__init__()
        self.variable = []
```

Launch Evennia and create an instance:

`@py evennia.create_object("typeclasses.test.NewObject")`

And this is the error that shows up:

```
<<<   File "e:\projects\python\evennia\evennia\utils\create.py", line 102, in create_object
<<<     db_typeclass_path=typeclass.path)  
<<<   File "e:\projects\python\evennia\evennia\utils\idmapper\models.py", line 65, in __call__  
<<<     return new_instance()  
<<<   File "e:\projects\python\evennia\evennia\utils\idmapper\models.py", line 58, in new_instance  
<<<     return super(SharedMemoryModelBase, cls).__call__(*args, **kwargs)  
<<< TypeError: __init__() got an unexpected keyword argument 'db_destination'
```

The original problem that spawned this bug report was that attributes created in `__init__()` weren't being recognized by Python, but apparently the problem is something deeper? I'm not fluent enough to understand what this error means.

**Comment by Griatch** [comment]
This error is unrelated to the other one we mentioned; it is due from typeclass `__init__` should accept arbitrary keyword arguments: 

```python
def __init__(self, **kwargs):
    # my content
    super(YourTypeClass, self).__init__(**kwargs)
    # my content
```

This is linked to how a database model can be initialized, by giving the field names and values as keywords - `db_destination` is one such fieldname and it fails when it cannot be supplied by the initialization functionality. 

Thinking about it, it's really quite unsafe to put the variable this way. It's even [written in the docs](https://github.com/evennia/evennia/wiki/Typeclasses) (so I gave the wrong advice to you earlier, sorry). The reason is that you can't always be sure when `__init__` gets called. Use the `at_init` hook instead, which is called when the object is cached in memory. 

You may also want to store your list in an `ndb` attribute. This is a non-persistent storage (will not hit the database and not survive a @reload) but will still tell Evennia not to re-cache this object willy-nilly and throw that ndb away. 

So, using `__init__` for typeclasses is just not a good idea and not recommended in the docs. With these changes things should work as expected. Closing this issue.
