### ISSUE TITLE
Evennia don't allows to have a class named Weapon

### ISSUE THREAD

**Issue by Nadorrano** [evennia/evennia#766]
This isn't really a big issue, but when I tried to create a class named Weapon, Evennia told me that this is not possible:
`
RuntimeError: Conflicting 'weapon' models in application 'typeclasses': <class 'evennia.contrib.tutorial_world.objects.Weapon'> and <class 'typeclasses.items.Weapon'>.
`
Should Weapon in the tutorial be renamed as TutorialWeapon, maybe?

**Comment by Griatch** [comment]
This is a very good point; not sure if this should be resolved by changing the class name(s) as suggested or if one can otherwise hide the contrib folder typeclasses from django so as to register them in some way.

**Comment by Griatch** [comment]
With this fix, there will still be a clash if defining your custom Weapon class while having the TutorialWorld installed (its Weapon typeclass will stil clash if the tutorialworld is actually loaded). We could change the contrib typeclass names but this is a potential problem due to the level of adoption of the contrib systems. We'll see if we go this way or otherwise move to separate the contrib/ folder out of the core library altogether down the line.
