### ISSUE TITLE
Locks at object creation not applying

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#770]
I just git pulled this morning so I'm running the most recent version.

For a given object, at_object_creation includes the following lines:

     self.locks.add("view:none()")
     self.locks.add("examine:none()")

But at object creation, only view:none() is getting applied. Quell or unquell, it does not matter. Format doesn't matter. I originally had it as such but it did not work either:

     self.locks.add("view:none();examine:none()")

The only way I can successfully get examine:none() to stick is if I manually apply it in-game:

    @lock obj = examine:none()

Am I not understanding something re: the usage of locks or is this a bug?

**Comment by Griatch** [comment]
The problem was that the `@create` command sets its own locks, among them `examine`; this overloads the results from `at_object_creation`. I removed this (it's set in the base object anyway so it was not necessary) which will allow you to set the `examine` lock as you want. The `@create` command also sets `control` and `delete` locks to the creating object's id - this remains the same; if you want to overload these in `at_object_creation` you need to modify the `@create` command.
