### ISSUE TITLE
Feature Request: email logins!

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#772]
Would be kinda cool if you could 'connect email password' too. Shouldn't be hard to add either. Few lines of code! I'd add it myself except...

I did the investigation but found that, for whatever reason, PlayerDB.objects.get_player_from_name() returns a single instance of PlayerDB while get_player_from_email() returns a queryset, which might be empty. Why do these two methods behave so differently?

I'm not sure why it was made this way, so don't wanna do a pull request that might break something.

**Comment by Griatch** [comment]
@volundmush 

This is the original login method of Evennia. It was removed since basically noone liked it. :) You can still find it as `contrib/email_login.py`.

There is no difference between the two methods you mention, they are both under the `@return_typeclass` decorator, which converts the result to a single None/typeclass.
