### ISSUE TITLE
Feature Request: Have evennia test also able to use game settings

### ISSUE THREAD

**Issue by apacala** [evennia/evennia#774]
I've just noticed that changing `DATABASES` in `server.conf.settings` has no effect when running `evennia test`, even though `evennia start` uses the specified database (PostgreSQL in my case). Tests are still running on `server/evennia.db3` using SQLite.

I'm using the latest git version.

**Comment by apacala** [comment]
It looks like `server.conf.settings` is not being loaded at all when running `evennia test` or `evennia test foo`.

**Comment by apacala** [comment]
Found [the code](https://github.com/evennia/evennia/blob/master/evennia/server/evennia_launcher.py#L747-L750) which always loads the default settings when running tests.

Is there a reason for that? I think I'd prefer to run game tests with the same settings as the game itself.

**Comment by Griatch** [comment]
This was intentional in order to present a uniform error standard for evennia testing. In principle it means one can check the "vanilla" library install and be sure (well, if the treat coverage was complete) that an error comes from a change you've done and can thus ease error tracking. 

The database is a special case. Sqlute3 has simply been so tremendously faster for unit testing compared to mysql or postgresql that it is an annoyance when working on Evennia. 

There is a point about using the game settings for unit testing though. To test evennia one does "evennia test evennia". Maybe one could have  something like "evennia test game" to use the settings and db of the gamedir you are running from? 
.

**Comment by apacala** [comment]
Maybe we could use `evennia.settings_default` only if running `evennia test evennia`? Applying game settings only to `evennia test game` would result with a drawback of not being able to test separate modules easily (e.g. `evennia test world.foo.bar`).

The other idea I have is not to override `DJANGO_SETTINGS_MODULE` environment variable if it exists and let users define it themselves, e.g. `DJANGO_SETTINGS_MODULE=server.conf.settings evennia test` or even `DJANGO_SETTINGS_MODULE=server.conf.test_settings evennia test`

**Comment by Griatch** [comment]
There are no unittests in the game dir by default but I think it might be a good variation to check the cmdline and use `evennia test evennia` as you suggest. PRs are welcome. 

I will not support not overriding `DJANGO_SETTINGS_MODULE` though - this is one of those things that experience tells us people will always have lots and lots and lots of issues with (some systems sets it up and others do not) and tend to lead to a truckload of support issues. Us handling `DJANGO_SETTINGS_MODULE` is one of the reasons Evennia is easy to use while integrating Django.

**Comment by Griatch** [comment]
Implemented in 4d3ea8d and docs were updated. Closing.
