### ISSUE TITLE
External API

### ISSUE THREAD

**Issue by Kelketek** [evennia/evennia#788]
Use the likes of something like the Django REST Frame to create an API for external utilities that don't require being part of the current process. This should be extensible/overridable to allow developers to add their own calls or change the existing ones.

Some example applications:
1. Collecting gamewide stats
2. Externally run scripting languages
3. Integration with external services on a push basis instead of a pull

**Comment by Griatch** [comment]
@Kelketek 

Could you elaborate some more on what you mean by this and what kind of changes your are suggesting and their effects, maybe with links to relevant django docs?

**Comment by Kelketek** [comment]
@Griatch http://www.django-rest-framework.org/ contains information about the Django REST framework. Having this would allow for more straightforward JS integration. It might be possible, since they both use JSON, to reuse OOB code in some way so that a normal game connection isn't required for certain calls. You could have a call that moves an object, sends a message, lists owned items, deletes objects, etc.

**Comment by Griatch** [comment]
@Kelketek 

Hm, that does sounds pretty nifty! 
I'm thinking I might put up a devel branch of my current reworking of the web client infrastructure for input from more people, maybe also for things like this; one still needs OOB for traditional telnet clients but the webclient is using plain JSON in my most recent implementation and who knows what other angles one might catch.

**Comment by Griatch** [comment]
@Kelketek 

I can see this being useful for allowing powerful extra features and effects on the database. I'm unsure about security though. Do you have any experience with how to do this in a safe way (can't allow just anyone to do stuff with the database after all)?

**Comment by Kelketek** [comment]
@Griatch The Django REST Framework, as linked earlier, has authentication support, with proper token handling, etc. You can plug in your own authentication and have permissions checks done based on locks if needed.

**Comment by whitenoiseoss** [comment]
Going through Django REST Framework documentation plus this tutorial here: https://code.tutsplus.com/tutorials/beginners-guide-to-the-django-rest-framework--cms-19786 gives a really nice and easy picture of how you can start building an API on top of all of the Evennia functionality.

Using DRF, everything will be 100% portable to the API. All that seems to be required is writing up the Serializers, defining exportable fields, and then editing will have to be written in. It will be a lot of code, but none of it is particularly difficult.

**Comment by whitenoiseoss** [comment]
Important features for security (looking above at Griatch's concern) are CSRF and CORS. You could also use something like JWT in place of DRF's default choices for some additional security (this would use either a private key or a secret in order to encrypt the token object).

With only tokens you run into the possibility of someone doing session hijacking potentially from links on forums or whatever.

The only complicated piece of this is when Evennia allows for multi sessions from multiple IPs, that is considered a poor security practice, but it could have to be enforced on the web as well.

**Comment by Griatch** [comment]
@whitenoiseoss So were you working on this?

**Comment by lorecrafting** [comment]
Anybody play around with GraphQL? http://graphql.org/
Here's a python-django graphQL server implementation: http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/

**Comment by Griatch** [comment]
@lorecrafting No, but graphQL looks quite nice at a glance. :)

**Comment by busbyra** [comment]
My team's boss is going to have me start working with GraphQL starting in
about March.

**Comment by lorecrafting** [comment]
From what I understand about Evennia typeclasses, there's DB and NDB attributes..  The NDB attributes are for ephemeral data..  If a layer was created to directly query the database, it wouldn't be able to query NDB data?

I'm assuming the single source of truth for the game state would be in the django models memory, and not the DB right?

If so, and an external API were to be created, and if the requirements were to make it match the exact game state at the time of query, it would have to be hooked up with the Object class?

Im just kinda asking around and throwing ideas around, ever so slowwwwly getting acquainted with GraphQL.  With GraphQL you can write your own 'resolves' which resolve data from whatever source you want, which then sends the data back to the requestor.

**Comment by Griatch** [comment]
@lorecrafting The game state does depend on in-memory data yes. I think it'd be safe to say that NDB attributes should not be something you should be able to query over an API though. But yes, stuff like cache state etc will always be a concern.

**Comment by TehomCD** [comment]
I'd like to try to do some work on this for Hacktoberfest now that I have more experience with django rest framework and GraphQL. Django Rest Framework is a very natural add for any django project that will ever have an external API. 

My experiences with Graphene have been a bit mixed - I've found it to make projects harder to maintain due to the difficulty of mapping queries to resolvers, and the learning curve for developers is steep - for a project that's welcoming to new developers graphql may not be a good fit. It's very useful when your core audience are all engineers who will use your API in unexpected ways so you aren't constantly adding more endpoints for new queries, but you can get similar flexibility with different filterset libraries for DRF even if the syntax is usually a bit more kludgy. I could add an example Graphene query/resolvers, but I think it'd be unlikely to ever be used, to be honest.

I'll probably focus on adding reasonable starting endpoints/serializers for common tasks and documenting how a developer could add more for their game.

**Comment by Griatch** [comment]
@TehomCD Cool, yes I think focusing on DRF is probably the sanest approach for our use case. 

Having thought about this, I think that this implementation should not be too hard; there are a few needs people have from such an API that needs to be considered (this is partly me thinking aloud so can be discussed): 

- Accessing/editing generic, named typeclass data in an authenticated way. The most traditional thing would be to use DRFs ModelSerializers to have one view for ObjectDBs, one for AccountDBs etc. In the typeclass system this is a little more involved - at the very least Attributes (Nicks) and Tags (Aliases) needs to be included - it'd be a pain to have to call those models separately (even though that may also be something possible to do). 
- There should ideally be a way to retrieve custom models created by the user without them having to make a new serializer/view for them. I think this must be possible to generalize (but once you go there you may also consider why you'd want separate endpoints for the default ObjectDB/AccountDB/etc at all - why not just specify exactly which datatable and typeclass you want in the call ...? 
- People making custom clients want some generic way to send commands to the server. As a first approximation, this could be a request that gets translated into an evennia `inputfunc`. Problem is the return - one could imagine the API endpoint waiting for the command to finish (really treating the Command class like a view!) and catch the `outputfunc` (sent by `msg()`) as the return value. One would then need to rework all default commands to only send one `msg()` ever. Alternatively, one could send the command, return some identifier and then have another endpoint that the caller can poll to retrieve the result. The latter will be highly inefficient though. The third option is to *not* do this kind of thing with a REST-API but to make a new (or expand the existing) websocket with a more formal API spec for people to call. I'm leaning towards the third option honestly, since Commands can be highly non-suitable for the idea of a RESTful interface (keeping state, `@interactive` mode etc). 
- Could you elaborate on which 'common' tasks you'd focus on?

**Comment by TehomCD** [comment]
Definitely agree on wanting models and Attributes to be included - they pretty much have to be due to so much data being stored there for objects.

Hmm. For the second part we could probably do something like that, creating some new serializer on the fly for an arbitrary model based on the natural key. Having all fields included by default makes me frown a little bit due to possibly exposing private data without users realizing it, but there isn't really any way to avoid that for a generic serializer that doesn't know about the model. I'll see what I can do, though a thorough how-to guide on writing their own serializers/views might be more beneficial than some sort of elaborate factory class.

I'm not sure about commands - I think the set of commands that people wouldn't mind waiting for a finish response for is probably larger than truly interactive stuff where websockets are a much better choice.

For 'common' tasks I was really just referring to standard CRUD views for the different models. I figured I'd start simple.

**Comment by Griatch** [comment]
This is now implemented in `develop` branch.

**Comment by Griatch** [comment]
Closing this issue since it's implemented in `develop` branch, for better overview.
