### ISSUE TITLE
Feature Request: Search Method Output Modification

### ISSUE THREAD

**Issue by cluebyte** [evennia/evennia#795]
The built-in search method for Objects is wonderful. But it does have some pitfalls if you ever want to change the output of search. For example, if I wanted to display "1. ball, 2.ball" instead of "1-ball, 2-ball", this requires me to change my cmdparser file and potentially miss any Evennia updates that you don't manually update yourself to your cmdparser file. Is there some way to refactor this feature to allow output modification easily without going through the entire effort of changing the cmdparser file?

Griatch had this to say about it, just so if he comments, he won't have to repeat himself!

> "Modifying how the object.search is managing its results is a pretty global thing unfortunately. While the search-in-current-room mechanism can be conveniently reached via myobject.search, what this actually does is to trigger the utils.search methods for you with some extra parameters. While I can see an argument for possibly doing something like moving the handling to a typeclass method, it's not clear this is suitable for all the situations the search is invoked. And of course, if you put the handling on a typeclass for you to overload, you wouldn't see automatic updates to your overloaded code anyway, same as now. But it's worth considering, since modifying the search result output is a pretty common thing to want to do, a typeclass method may be easier. I like the concept."

**Comment by cluebyte** [comment]
I'll lump this in here as well since it came up as an issue for my project. Is it possible for Search to specify a list of Objects for the location instead of just an Object in itself? 

For example, if a character has a few specified locations it can be on their person (their inventory or in their hands, and we've defined these as attributes), it'd be handy if you could specify the location to be location=character.db.hands or location=character.db.inv instead. This way, you won't get duplicates in your search that aren't pertinent, such as when you have two rings with identical keys in your contents, but one ring is being worn and the other ring is in your hands. You'd only want a "wear" command to see the one in your hands. 

A possible work around would simply be to flag each object as being in someone's hands so the search method would ignore it, but I figure I might as well bounce the idea.

**Comment by Griatch** [comment]
@cluebyte 

I already commented well on the first point so I'll not do it again. :) 

As for your second point, yes - the object.search method takes an optional keyword `candidates` that are basically a list of the objects you want to include in your search. You can include contents of any location you want in this list before querying.
In fact, if you don't set it (the normal operation), it's the search method itself which adds your inventory, location and contents of location to the `candidates` list. It makes for a big cutdown in search cost to limit the search this way. Note that if you supply your own `candidates` the `location` keyword has no effect. See [the API for the search function here](https://github.com/evennia/evennia/wiki/evennia.objects.objects#defaultcharactersearch).

**Comment by cluebyte** [comment]
*facepalm* I missed that completely on my second point. Thanks!

**Comment by Griatch** [comment]
@cluebyte 

With the latest revision I have cleaned up and removed two of the three plugin functions; those are not needed anymore. All error handling (for both object-searches and command-searches) is handled by the module defined by `settings.SEARCH_AT_RESULT`. 

I also added a new `settings.SEARCH_MULTIMATCH_SEPARATOR` that defaults to `-` and which the system uses to separate number-identifiers of multi-matches (like 1-box, 2-box etc). So if your only change is to want to use 1.box, 2.box, then you just need to change this setting to `'.'`. 

For futher dynamic customization, I want to point out that the on-object `search` methods since earlier accepts strings `nofound_string` and `multimatch_string` that can be used to replace the default returns for particular situations. 

With this I will close this request, it seems to address all aspects of this issue that we are likely to be able to modify.
