### ISSUE TITLE
Server crash = commandset related error

### ISSUE THREAD

**Issue by lambentLogic** [evennia/evennia#798]
Most recent error (first time for this particular merger error):
SyntaxError encountered when loading cmdset 'commands.default_cmdsets.UnloggedinCmdSet': "'return' outside function (holo_server.py, line 8)".
SyntaxError encountered when loading cmdset 'commands.default_cmdsets.UnloggedinCmdSet': "'return' outside function (holo_server.py, line 8)".
 (See log for details.)
Command '__unloggedin_look_command' is not available. Type "help" for help.

If my computer (used as server) crashes or is forced to restart while Evennia is running, a commandset syntax or merger error results when I attempt to restart the world. Deleting the database and using 'evennia migrate' again solves the issue.

**Comment by Kelketek** [comment]
@lambentLogic Where is `holo_server.py` and what are its contents?

**Comment by lambentLogic** [comment]
Apparently relevant. (Still doesn't explain the previous one, but lack a traceback for that.)

**Comment by Griatch** [comment]
@lambentLogic 
It says in your traceback what your error was - you had a `return` statement outside of a function, probably because an indent was wrongly placed. Such an error means it is not a valid Python file, which means Evennia can't load it at all. 
You generally never needs to reset your database over such coding errors, best to look at the traceback carefully.
