### ISSUE TITLE
Channels: Sanity Inquiry

### ISSUE THREAD

**Issue by volundmush** [evennia/evennia#812]
So I have a few questions regarding the channels before (or maybe right as I begin to) tear them apart and write my own typeclasses.

While the capabilities of channels - having both objects and players able to subscribe, being able to link in an external connection, having access to .db attributes and so on - are totally great, some of the design makes me headscratch.

Mainly the idea of having MULTIPLE SENDERS for the same message.

But another comes to mind. Channels are not currently terribly flexible. Yeah, there's some nifty hooks and they do a few useful things. But they are not as approachable to modify and extend as Players and Objects and etc. 

Are you sure this setup is the best approach? I am not finding it so easy to extend it without basically overloading everything to do with displaying and routing messages.

Maybe it should be revisited if you're not 100% sure that this is the way you want it shipped. I could see about some improvements?

**Comment by Griatch** [comment]
This sounds more like a forum post than an issue to be honest. :) 

Anyway: 

Multiple senders could for example be used as a way to handle reply-to-all type of messaging. In a group send environment a single person is obviously writing the message but you could picture it being sent on behalf of an entire group (like the admins). Thus the command would assign all others from that group as "senders". When the other party replies, the system could then reply-to all senders very easily. You could of course do this with some ad-hoc Attributes too but since we were changing the database table anyway, it seemed reasonable to keep maximum flexibility. 

There are a range of hooks on channels but we could certainly consider extending them or add more useful arguments to existing ones if you find the current setup to be too limiting in actual use. We are open to suggestions or PRs on it as usual.

**Comment by Griatch** [comment]
@volundmush  Without actual suggestions on what should be changed it's hard to evaluate this as a workable Feature request. Will close it now.  If you have any specific wishes / suggestions / features you feel is needed to make the channel system more "flexible", feel free to request this to be opened again.
