### ISSUE TITLE
Channel alias with plus sign (+) causes channel name to lowercase

### ISSUE THREAD

**Issue by grungies1138** [evennia/evennia#814]
When I do a @ccreate Staff;st=Staffly channel everything works fine and as expected.  When I change the command to include a new alias with a plus sign (@ccreate Staff;st;+st=Staffly channel)  everything works as expected, but the name of the channel gets lowercased.

**Comment by Griatch** [comment]
@grungies1138 

The + sign does not matter as far as I can tell, the lowercase happens whenever you add any aliases at all. This was intentional - the bug here is actually to let the non-aliased channel remain upper case. But since channel lookup is case insensitive anyway, I guess it's fine to let the channel creator select the case they want. Will change that.
