### ISSUE TITLE
Evennia Migrate Issue

### ISSUE THREAD

**Issue by Tirit** [evennia/evennia#882]
I recently tried to do a 'evennia migrate' for the future module. 

This may or may not be related to the issue I opened with my database be 'failing', Issue #856, that some how magically worked, but I figured I'll bring it up. I'm not sure if it's a bug, but I figured I would send it in as one, just in case. If not, that I'll open up a discussion on the forums. And it might be a simple fix...

I'm getting the following error on 'evennia migrate'

>    Command
      migrate
    raised an error: 'Conflicting migrations detected (0004_auto_20151101_1759,                                                0004_auto_20150907_1835 in typeclasses).
To fix them run 'python manage.py makemigrations --merge''.

When I try and do the 'python manage.py makemigrations --merge' I get tracebacks. However, I'm curious if this is suppose to be the managers.py from evennia/typeclasses, or the manage.py from my virtual environment (/home/evennia/vienv/lib/python2.7/site-packages/django/conf/project_template/manage.py)? 

From the /home/evennia/vienv/lib/python2.7/site-packages/django/conf/project_template/manage.py I get the traceback of:
>Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named {{ project_name }}.settings

From the evennia/typeclasses/managers.py I get the following traceback:
>Traceback (most recent call last):
  File "managers.py", line 9, in <module>
    from evennia.utils import idmapper
  File "/home/evennia/evennia/evennia/utils/__init__.py", line 14, in <module>
    from .utils import *
  File "/home/evennia/evennia/evennia/utils/utils.py", line 29, in <module>
    _MULTIMATCH_SEPARATOR = settings.SEARCH_MULTIMATCH_SEPARATOR
  File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/evennia/vienv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting SEARCH_MULTIMATCH_SEPARATOR, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

I'm attaching my db as a sharable link to Griatch, if anyone else need access, please pm me with an email for Google Drive.
https://drive.google.com/file/d/0B2GFUEsx6cLaWlRndElQdHZHQlU/view?usp=sharing

The following is my versions from evennia menu:
    Evennia 0.5.0 (rev 652bb02) (rev 652bb02)
    OS: posix
    Python: 2.7.6
    Twisted: 15.4.0
    Django: 1.8.5
    Evennia MUD/MUX/MU* development system

**Comment by Griatch** [comment]
@tirit 

I'm happy to report this one is easy to fix. :) Just delete  `evennia/typeclasses/migrations/0004_auto_20150907_1835.py` and you will be fine. 

### Explanation: 
The migration `0004_auto_20150907_1835 ` which you see in the traceback does not actually exist in Evennia's distribution (which is why it clashes with the "real" migration). Looking at the time stamp of the real migration 0004, it seems there was a gap there where the right migration was not included in the repo. I don't remember it being so, but if so it was my bad - I likely just forgot about adding the file to git for a while. If you then ran `makemigrations` in that gap you'd creat your own migration locally, which now clashes with the one distributed with Evennia since then. There is nothing wrong with your database otherwise, it migrates just fine.

By the way, you can see if there are spurious files in your repo by going to your evennia repo clone and running `git status` - if you do you should see `evennia/typeclasses/migrations/0004_auto_20150907_1835.py` listed prepended with `??`. This means the file is not under evennia's version control and so only exists on your machine.

Closing as resolved, post again if there are any issues.
