### ISSUE TITLE
Bug: Reloading server causes infinite-repeating scripts to duplicate tasks

### ISSUE THREAD

**Issue by MikeCPlusPlus** [evennia/evennia#890]
**Steps to Reproduce**
1. Create a simple repeating script like this:
```
class RepeatingTestScript(DefaultScript):
    def at_script_creation(self):
            "Called once, during initial creation"
            self.key = "repeat_test_script"
            self.desc = "repeats."
            self.interval = 60
            self.persistent = True
    def at_repeat(self):
        self.obj.msg("repeating...")
```

2. Attach it to a Character:
`self.scripts.add(RepeatingTestScript)`

3. Observe that the `@scripts` command shows the time remaining correctly
4. When `@scripts` shows some time remaining, for example '20s', run the command `@reload`
5. In 20 seconds the `at_repeat` of your scripts will fire, and 60 seconds later it will fire again, followed by the original task 40 seconds after the second, ad infinitum, or until cold restart.

**My Troubleshooting**
From what I understand, it looks like when the server is restarted the `_start_task` method gets called again, which ignores a pre-existing _task (ExtendedLoopingCall) and creates a new one. I put a check at the beginning of `_start_task` that is essentially a copy-paste of `_stop_task`, this prevents a second _task from getting made. 

Alternatively, we could just not make a new task if one already exists. This would have the advantage of leaving the remaining time per task correct.

See my patch below:
[scripts-patch20151203.txt](https://github.com/evennia/evennia/files/51417/scripts-patch20151203.txt)

**Comment by Griatch** [comment]
Thanks for the patch, will look it over. I'd need to examine it a little closer to fully understand what is going on here.

**Comment by Griatch** [comment]
Can confirm the behavior. The patch will however lead to the script starting over after a reload. The actual error here is that the script validation is run twice (which is ok) with force=True set (which is not ok). It is called once by the restarting server and once when the character session (re-)connects to the character. So I think this error only happens when using a script stored on a character (will test more tonight). Will see just what can be done about it.
