### ISSUE TITLE
NPC Shop: Changing evmenu causes failure

### ISSUE THREAD

**Issue by DauntlessAutumn** [evennia/evennia#896]
When I make a change to the EvMenu script in npcshop.py and reload the server, existing shops cease to function. They lose their commandset and the buy menu can't be accessed. 

The change to the file that was made was this:
> options.append({"desc": "%s (%s gold)" %

to this:

> options.append({"desc": "%s ({y%s {ngold)" %

and this has happened with every change, minor or otherwise I have attempted.

If I type/force/reset it to npcshop.NPCShop there is an error.
Error Log:
[npcshop_error_log.txt](https://github.com/evennia/evennia/files/52994/npcshop_error_log.txt)

After that, all commands cease to function and I have to stop/start the server.

Just in case, here's my complete npcshop file in .txt format:
[npcshop_debug.txt](https://github.com/evennia/evennia/files/52995/npcshop_debug.txt)

Thanks in advance for you help, it's greatly appreciated.

**Comment by Griatch** [comment]
This was nothing you did wrong but a bug in the tutorial code. The error is not due to what you think though: It has nothing to do with you updating the script. The error is simply due to the command set on the room not being saved across server reloads - you can see this by doing `examine here` when in the store, you'll find the cmdset was gone after a reload, regardless of if you modified the source or not. 
By default cmdsets you add are not saved across a server reboot. To tell Evennia to save it you need to change the line which adds the `ShopCmdSet` to the store to one of the following: 

```python
self.cmdset.add(ShopCmdSet, permanent=True)
# or 
self.cmdset.add_default(ShopCmdSet)
```

Both works the same for this simple case. See the [cmdset documentation on defining command sets](https://github.com/evennia/evennia/wiki/Command%20Sets#defining-command-sets) for information about the difference between them. 

(The error log you present I cannot replicate with `@typeclass/force/reset here` - it seems unrelated to this error report in any case. Maybe you still having the buy command in your character cmdset?)

The tutorial was updated as described above to make the cmdset properly saved. Thanks for the report! Closing.
