### ISSUE TITLE
Tutorial NPC drops object type

### ISSUE THREAD

**Issue by DauntlessAutumn** [evennia/evennia#897]
Me again.

Oh boy did I kill it good this time.

I had a simple attack command working, with variable damage and an optional crit.

Objects involved are the admin superuser (issuing the attack command) and an npc dummy created with +createnpc as per the tutorial.

I've noticed the npc drops it's typeclass and becomes DefaultObject quite regularly. Do I need to set that permanent somehow like my last issue?

I was trying to announce a death message to the objects involved (both characters), and the room (but exclude both characters) when there was an untrapped error.
[issue_error_log.txt](https://github.com/evennia/evennia/files/53063/issue_error_log.txt)

Which is all well and good, evidently "exclude=" is a little pickier than I had hoped.

The real problem is now whenever I issue seemingly any command that takes an argument in the same room as the Dummy, I get this response:

> More than one match for 'examine' (please narrow target):
1-@examine (Dummy(#3))
> 2-@examine

> More than one match for 'look' (please narrow target):
1-look (Dummy(#3))
2-look

> More than one match for '@del' (please narrow target):
1-@destroy (Dummy(#3))
2-@destroy

The server has been stopped/started since.

I'm hoping to avoid nuking my database, haha.

So ultimately:
* ~~How do I delete the Dummy character?~~
* How do I stop this from happening again?
* How do I need to edit my code to get the required exclusions?

P.S. I'm sorry if I'm abusing the issue system. Should I be putting this somewhere else?

**Comment by DauntlessAutumn** [comment]
I left the room and did some more testing with a new dummy npc and a dummy player as well.
Seems like the message is being excluded correctly with "exclude=(caller,self)". Is this an appropriate
solution or are there hidden perils?

**Comment by Griatch** [comment]
@DauntlessAutumn 

Yes, this is not an Evennia error, but intentional behavior. In the same way as the "buy" command was available to you while inside the npc shop, the commands on objects (which the NPC is) is available to you while in the same room. This is usually what you want, but if you think about it, your Character is also an Object with commands on it (the character cmdset) and multiple characters can coexist in a room without seeing each others commands.

The solution is that you must lock the NPC object's "call" lock. This controls "outside" calling. When the call lock is not passed only the object itself has access to the commands on it (and each of those commands can also have "call" locks if a particular command should for some reason be inaccessible in some situation). 

Use `@lock npc = call:false()`  to set a npc-only lock in-game or self.locks.add("call:false()")` in your npc's `at_object_creation`. Other common examples would be to lock with `call:inside()` or `call:holds()` to only get access to the object's commands if you are inside it (good for vehicles) or is holding the object in your inventory. 

See our [command set documentation about how commands are retrieved](https://github.com/evennia/evennia/wiki/Command%20Sets#command-sets-searched).

Issues that could be assumed (or mistaken) for an Evennia bug are ok here, but for asking for help in general it's better to use our [forums/mailing list](https://groups.google.com/forum/#!forum/evennia).

**Comment by Griatch** [comment]
... Oh, and it becomes DefaultObject if you have a critical syntax error in your typeclass, so your custom class cannot load - it will then fall back to DefaultObject as a safety backup. You should see the error causing this in your log.
