### ISSUE TITLE
Fails: "Idle timeout exceeded, disconnecting."

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#900]
I'm on a barely-modified revision f87d07b. I added a script to at_server_start but that's pretty much it.

Both admin and plebeian accounts, when idle, will receive the above notice repeatedly but never actually disconnect.

There are no associated error messages in the log file.

Please let me know if there is any other diagnostic information I can provide.

Thanks!

**Comment by j3b4** [comment]
Hi, can I just ask whether you have ever also had a problem with your @reload command? I just ask since I also have noticed the false timeout disconnect message with my accounts but actually disconnecting.

**Comment by Russell-Jones** [comment]
I see this as well on one of my instances, in the telnet client. How long have you had your servers up for, @j3b4 @strikaco ?

**Comment by strikaco** [comment]
@j3b4 I sometimes do, where it'll go into an infinite cycle of ellipses and just doesn't seem to come back up. I have to manually stop and start at that point.

@Russell-Jones I generally start the server and log in and as soon as the timeout period expires is when I start experiencing the issue. I've tried both reload and reset...

**Comment by orkim** [comment]
On a fresh install I am seeing this as well.

It does seem like I had to idle for a while (maybe a hour+) before it began happening though.

Even 10-30 seconds after typing a command to the server, and I had not issued a @reload or @reset command since starting the server.

At the time I saw this I had the super user account logged in, and a separate connection with a normal player.  On both of them, I've issued 'access' and 'look' commands and have received the time out message again within a minute or so. I was seeing this issue from both connected clients.

The client was tintin++ for completeness.

Nothing loaded up (no tutorial world or such). I was standing in Limbo, with no custom code (just what is generated from 'evennia --init').

**Comment by orkim** [comment]
This is definitely coming from `_portal_maintenance()` in the `evennia/server/portal/portal.py` file from my testing.

It seems that the `PORTAL_SESSIONS.disconnect(session)` is not actually disconnecting the session.  And since it fails, doing a command to the MUD is not resetting the `cmd_last` variable, so once this "hits" you get a message every minute forever.  Maybe the session object is destroyed, but the connection not actually dropped?

You can recreate this by setting a much lower `IDLE_TIMEOUT` value in settings.py (I was using 120 second timeout).

**Comment by orkim** [comment]
Setting `IDLE_TIMEOUT = 0` in your settings.py file is a workaround if you wish to keep from getting these messages before a fix is implemented.
