### ISSUE TITLE
Traceback when repeating script deletes the object it runs on

### ISSUE THREAD

**Issue by j3b4** [evennia/evennia#919]
I get the following error after running a script with a repeat of 1 which simply calls 
self.obj.delete()

I find that the object is successfully deleted and the script terminates.  But the following appears in the log file.  The first line is not part of the error but a print statement I'm using just during development that announces the script is about to delete its own object.

2016-01-25 15:57:05+0000 [-] 20 secs later. Time to clean up. Unlesss...
2016-01-25 15:57:05+0000 [-] Unhandled error in Deferred:
2016-01-25 15:57:05+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/aeon/Evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/aeon/Evennia/evennia/evennia/scripts/scripts.py", line 238, in _step_task
            return maybeDeferred(self._step_callback).addErrback(self._step_errback)
          File "/home/aeon/Evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 328, in addErrback
            errbackKeywords=kw)
          File "/home/aeon/Evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/aeon/Evennia/pyenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/aeon/Evennia/evennia/evennia/scripts/scripts.py", line 206, in _step_errback
            {"key": self.key, "dbid": self.dbid, "cname": cname,
          File "/home/aeon/Evennia/evennia/evennia/utils/idmapper/models.py", line 171, in <lambda>
            fget = lambda cls: _get(cls, fieldname)
          File "/home/aeon/Evennia/evennia/evennia/utils/idmapper/models.py", line 115, in _get
            raise ObjectDoesNotExist("Cannot access %s: Hosting object was already deleted." % fname)
        django.core.exceptions.ObjectDoesNotExist: Cannot access db_key: Hosting object was already deleted.

**Comment by kaihuang201** [comment]
I believe this error is due to the [stop](https://github.com/evennia/evennia/blob/master/evennia/scripts/scripts.py#L331) function in DefaultScript class been called twice. The stop function attempts to delete the script from the database, therefore causing the error.

First call to the stop function is [in self.obj.delete()](https://github.com/evennia/evennia/blob/master/evennia/objects/objects.py#L780), which is called in [at.repeat()](https://github.com/evennia/evennia/blob/master/evennia/scripts/scripts.py#L225), in _step_callback.

Second call to the stop function is [at the end of _step_callback](https://github.com/evennia/evennia/blob/master/evennia/scripts/scripts.py#L231)

So overall the call sequence looks like the following:

`_step_callback(...)
    ...
    self.at_repeat()
        ...
        self.obj.delete()
            ...
            script.stop()
                ...
                self.delete()    <-- delete the script itself from database.
                ...
    self.stop()
        ...
        self.delete()     <-- delete the script again which causes error`
        
        
From here on, since stop function [asserts an error](https://github.com/evennia/evennia/blob/master/evennia/scripts/scripts.py#L353), [_step_errback](https://github.com/evennia/evennia/blob/master/evennia/scripts/scripts.py#L353) is called, which attepts to format an error message but fails because the object is already deleted.

Please let me know if my interpretation contains any problem.

**Comment by Griatch** [comment]
@kaihuang201 

Yes, this seems to be a correct analysis. I think all sections are probably doing the right thing: 

1. If the object on which the script resides (`self.obj`) was deleted from elsewhere, it should definitely make sure to stop all scripts on itself (so it's correct that `self.obj.delete()` calls `self.stop()` on the script). 
2. In this particular case, where the script itself deletes the object, it must call `self.obj.delete()` to do so, there is no way around that. The problem comes, as you say, in the circular nature of this call. 

So the correct way to handle this is likely to catch the error on the Script level, in `self.stop()`, by catching the `ObjectDoesnotExist` error from `self.delete` and simply ignoring it (while swallowing errors is usually not a good idea, in this case an `ObjectDoesNotExist` error means that `delete` has already "succeeded" and is not needed a second time). This should avoid the "loop" created by this particular situation.

**Comment by Griatch** [comment]
Resolved with merge #920.
