### ISSUE TITLE
Prevent duplicate character names

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#943]
#### Brief summary of issue / Description of requested feature:

Currently duplicate player names are not permitted. Puppetable character names are not bound by any such restriction.

#### Steps to reproduce the issue / Reasons for adding feature:

In instances where a player can puppet multiple characters, there is nothing stopping griefers from creating a character that duplicates the name and attributes of another character in order to impersonate said character.

This does not affect servers where MULTISESSION_MODE is set to 0 (thus, all default installations). Since players cannot create multiple characters, their primary character name has to adhere to restrictions placed on player names.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Rev 9522a94.

Ideally PREVENT_DUPLICATE_CHARNAMES for player-puppetable characters should be a boolean in settings.py.

Non-puppetable objects should not be bound by name restrictions

**Comment by jrsteensen** [comment]
Second this, but not something I can tackle at the moment. Hopefully, the solution is an easily accessible function as well - I'm alowing character name changes in cgen, and would want to run this check during cgen.

**Comment by BlauFeuer** [comment]
It seems like a game-specific need to me.  Adding a check on character generation for uniqueness is only half of it - what happens if someone's using a character other than the player's name, then a new player comes along wanting to use the player name that the character is currently running?

Sure, Ideally it would be for that particular game situation where you've decided MULTISESSION_MODE is for your game, but not realizing that MULTISESSION_MODE is not very mature yet.

You probably want to prevent duplicate puppeting, not just characters for those who are not watching the who list to see that the player who usually runs the character or puppet is not currently active.  But some games might want several characters or puppets named "wooly rock monster" so the easiest thing at this time is to check for uniqueness when going IC into a puppet or character and looking at some sort of maturity level comparison for how long a player has been around. Most grief-givers are just not patient to play long enough to earn the ability to potentially spoof another player's character or puppet.

**Comment by Griatch** [comment]
Limiting Character names is, as @BlauFeuer points out, a game specific thing. It's not too uncommon with RP games having big rosters of ready-made characters to play. Maybe being able to jump into playing a non-descript "Palace guard" is a valid option for jumping into a scene. Also, picking a character name will block it forever (which is also a sort of griefing, as @BlauFeuer points out). And so on. I see what you mean though. I can see the advantage of offering some protection out of the box. 

Question is how to do it. It's very fragile to limit duplicates on Characters in general since different games will treat characters differently (some will let NPCs be children of Characters (and there should be possible to be duplicates of those!), others will use subclasses for classes etc). It's also not possible to limit this to non-puppetable objects since there is no such thing - puppeting is just a matter of flipping a lock and that can happen at any time (*any* Object can be puppeted).

What we could do for default is to have the `@charcreate` command check duplicates only strictly on the Character class (not its children) when it's used in MULTISESSION_MODE>1. This allows for the creation of duplicates in other situations (like by staff), just not by the default `@charcreate`.

**Comment by Griatch** [comment]
@jrsteensen 

The check itself is simple once you decide which typeclass you want to limit on. If avoiding duplicates on Characters only (not children) all you need is to query for the name before allowing it: 

```python
if Character.objects.filter(db_key__iexact=suggested_new_name):
    caller.msg("Error: A Character with this name already exists!")
    return 
```

**Comment by Griatch** [comment]
Implemented in wclient branch, will closes when it merges.

**Comment by Griatch** [comment]
Closed as wclient branch has merged.
