### ISSUE TITLE
Unable to use "l" as an option in a default EvMenu

### ISSUE THREAD

**Issue by shollen** [evennia/evennia#949]
EvMenu redisplays a node when the single letter 'l' is supplied as input to a default EvMenu node. 

1) To reproduce the "bug," set up a default node, like...
```
def node0(caller):
    caller.msg("\nWhat is your first name?")
    options = ({"key": "_default",
                "goto": "node1"})
    return 'test', options
```
2) Start your menu with the @py command: @py from evennia.utils.evmenu import EvMenu; EvMenu(self, "path to the module containing node0", startnode="node0")

Instead of moving on to node1 with 'l' as the raw_string, the code redisplays 'test' and leaves execution in node0.

I'm using the latest version of Evennia on OSX 10.11.3.

**Comment by Griatch** [comment]
I would think the string "look" causes the same effect. Also "q" and "quit" will exit the menu with this configuration. This is expected behavior with the current design: the idea being that one should always be able to re-show the node or quit the menu regardless of the state one is in. 

The automatic `q/uit` command can be turned off when initializing the evmenu, but `l/ook` currently cannot. Maybe the best way to handle this is to allow the user to turn off the auto-look in the same way. That means it's up to the menu creator to handle how nodes are re-shown.

**Comment by shollen** [comment]
Yes. You’re exactly right. I replied just as you did.

I’’ll take a look at implementing an auto-look toggle.

Thanks.

-Shan

**Comment by Griatch** [comment]
Will be closed when wclient branch merges.
