### ISSUE TITLE
Errno 13 [No Permissions]

### ISSUE THREAD

**Issue by Orrden** [evennia/evennia#991]
#### Brief summary of issue / Description of requested feature:

Attempted to install Evennia on CentOs 6.7.  Seem to be getting a Errno 13 [no permissions] error when I attempt to start the server.  

Initial install went fine.  Had no issues running evennia migrate and evennia start, it even let me create the superuser account.  However, after creating the superuser account, it popped up with the no permissions error and I've been unable to proceed since.

#### Steps to reproduce the issue / Reasons for adding feature:

1.  root@host: cd /home/rpgchaz/evennia
2.  root@host: source pyenv/bin/activate
3.  root@host: cd /home/rpgchaz/evennia/RoI
4.  root@host: evennia start

#### Error output / Expected result of feature

```
0 static files copied to '/home/rpgchaz/evennia/RoI/web/static', 70 unmodified.

Starting Evennia Server (output to stdout).

Starting Evennia Portal in Daemon mode (output to portal logfile).
[root@host /home/rpgchaz/evennia/RoI]# Traceback (most recent call last):
  File "/home/rpgchaz/evennia/evennia/evennia/server/evennia_runner.py", line 338, in <module>
    main()
  File "/home/rpgchaz/evennia/evennia/evennia/server/evennia_runner.py", line 335, in main
    start_services(server_argv, portal_argv)
  File "/home/rpgchaz/evennia/evennia/evennia/server/evennia_runner.py", line 171, in start_services
    PORTAL = Popen(portal_argv, env=getenv())
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by Griatch** [comment]
1. You should not be installing Evennia as root to begin with. You don't need root access to do any of the `pip` steps, only for installing Python itself and GIT (and possibly `pip` if you don't have it).  Evennia itself should not be run as root. 
2. The `source pyenv/bin/activate` step does not seem to have worked for you, since `(pyenv)` is not appearing on your command line. If you are not in your virtualenv you are probably trying to execute something else than you expect. 

Most likely you have installed evennia with root, and on CentOS creating binaries with root does not automatically give them execute permissions ... or something like that. I would suggest that the best way to handle this is to start over - delete your virtualenv (pyenv) folder and create a new one while *not* being root this time, and repeat your install from there. 

This is either way not an Evennia bug, so I'm closing this. You can however continue commenting in this thread if you have further comments.

**Comment by Orrden** [comment]
Alrighty.  I appreciate the advice.  My server support is being less than helpful.  I'll give your advice a try.

**Comment by Orrden** [comment]
Oddly enough, I've followed your installation instructions to a T under my sub account.  Is there a way to make source pyenv/bin/activate function?

I have noticed that my evennia start command won't even work unless I run the source pyenv/bin/activate first

**Comment by Griatch** [comment]
@Orrden 

If evennia start works, but your virtualenv is not starting, I would have suspected that you have accidentally done an install *outside* your virtualenv in the past - when you were running as root you might have installed evennia in your normal system-wide install location for python packages. This might still be the case, and it's confusing the heck out of the system if your virtualenv is not working. 

That `evennia` works *only* when you activate the virtualenv is confusing though - it suggests the virtualenv works (`evennia` is supposed to only be available in the virtualenv, so this is correct behavior. But you are saying it's not showing the `(pyenv)` prefix as it should. Never seen it lack that, so I can't help but think there must be something that you have installed in multiple places and which is mucking things up,

**Comment by Orrden** [comment]
I may have found the issue, however I'd like your input.  It appears as though 

pip install virtualenv

is installing virtualenv in my python 2.6 directory instead of my python 2.7 directory (I'm not sure why my server added another python version instead of just upgrading my previous one...).

Do you think virtualenv running in python 2.6 could be the issue?  I know it says that evennia doesn't support it, so I'm willing to bet that that might be a huge issue.

**Comment by whitenoiseoss** [comment]
`python --version`
`pip-2.7 install virtualenv`
`python -m virtualenv myvirtualenv`

**Comment by Orrden** [comment]
doesn't work, mostly because I have a python 2.6 and a python 2.7

when I run

```
python --version
```
I get 2.6.6

to check my other python version, it makes me run

```
python27 --version
```

=p working on getting this resolved now.

**Comment by Orrden** [comment]
Nevermind.  Still seem to be having this huge ongoing issue.

**Comment by whitenoiseoss** [comment]
Are you on the IRC?

**Comment by Griatch** [comment]
@Orrden 

Since you are able to use python27 (python 2.7), it seems you have it installed, just not set as the default. To make a new virtualenv use another python version than default you can do this: `virtualenv -p /usr/bin/python2.7 pyenv`. You can use `whereis python2.7` (or `python27` if that's the binary name for your distro) to check where the Python binary is.
When you start your virtualenv you will then be using the python version you specified. 

Also remember to `deactivate` your virtualenvs or start a new terminal if you delete the old pyenv folder - not sure if the old one may stay in memory otherwise.
