### ISSUE TITLE
object method at_post_puppet to be called with player and session

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#992]
#### Brief summary of issue / Description of requested feature:
Unlike `at_post_unpuppet`, `at_post_puppet` has no player and session passed to it so there's no way to message other players/sessions about the state update. This function does not know who the new player is that just joined in puppeting this object.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Puppet a character.
2.  Have another player puppet a character.
3. `at_post_puppet`'s default message "You become <character>." is sent to your session and not the recently joined player's session.

#### Error output / Expected result of feature
Error output is that message goes to wrong player session.
Results of feature allows sensible messaging where "You" means the session of the player that initiated the command.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

current master, all OS, add calls to `at_post_puppet` to be similar to `at_post_unpuppet(self, player, session=None):` and update the definition in DefaultCharacter in evennia/objects/objects.py.

##### Initial discussion:

**Griatch@#evennia:**
`There is no way to know that unless the session sends themself as an argument to said method.`
`I see that the session is indeed available in the puppet_object method (which calls at_post_puppet) so I suppose we could extend that hook with a session argument.`
`I think it may have originally been defined at a time when an object only ever had one session, so once you were puppeted you could easily retrieve it.`

**Comment by Griatch** [comment]
@BlauFeuer 

I think there was some misunderstanding in that discussion. It was never a problem knowing the *Player* currently puppeting you. From inside `at_post_puppet` you get that just with `self.player`. Similarly, you will have no problem knowing which Sessions are puppeting you, you get those with `self.sessions.get()` (or `self.sessions.all()`). This is not possible *before* you puppet or after you unpuppet, which is why those hooks include those as arguments. 

The problem I was referring to was wanting to know exactly which Session was just added because you want to message *other sessions*. This is because `self.sessions.get()` returns a list of all sessions connected to this Character. 

However, looking at it now, the latest connecting Session used for puppeting the given Object is simply the *last* Session in the list produced by `self.sessions.get()`. So that information is available too. I'll add this information to the hook doc strings then close this.

**Comment by BlauFeuer** [comment]
Last session is latest! I think that's one of the key things I didn't know.   To really test these things, it takes having two connections to see who is messaged what.

Now I have managed to extend the hook in my characters to message all sessions on `at_post_puppet` - one to tell the "You become" ... message, and the others to mention who's joined in the puppeting.
